[View in Colaboratory](https://colab.research.google.com/github/iamrajee/Data-Analysis/blob/master/harshit_data_clean.ipynb)

In [0]:
!ls

datalab  Jazz_Disc3_SJJune2018.xls  lastfinallist (1).csv  lastfinallist.csv

In [0]:
from google.colab import files
uploaded = files.upload()

Saving Jazz_Disc3_SJJune2018.xls to Jazz_Disc3_SJJune2018.xls

In [0]:
%%time
!pip install spacy
!python3 -m spacy download en
import spacy
en_nlp = spacy.load('en')

Collecting spacy
  Using cached https://files.pythonhosted.org/packages/3c/31/e60f88751e48851b002f78a35221d12300783d5a43d4ef12fbf10cca96c3/spacy-2.0.11.tar.gz
Requirement already satisfied: numpy>=1.7 in /usr/local/lib/python3.6/dist-packages (from spacy) (1.14.5)
Collecting murmurhash<0.29,>=0.28 (from spacy)
  Using cached https://files.pythonhosted.org/packages/5e/31/c8c1ecafa44db30579c8c457ac7a0f819e8b1dbc3e58308394fff5ff9ba7/murmurhash-0.28.0.tar.gz
Collecting cymem<1.32,>=1.30 (from spacy)
  Using cached https://files.pythonhosted.org/packages/f8/9e/273fbea507de99166c11cd0cb3fde1ac01b5bc724d9a407a2f927ede91a1/cymem-1.31.2.tar.gz
Collecting preshed<2.0.0,>=1.0.0 (from spacy)
  Using cached https://files.pythonhosted.org/packages/1b/ac/7c17b1fd54b60972785b646d37da2826311cca70842c011c4ff84fbe95e0/preshed-1.0.0.tar.gz
Collecting thinc<6.11.0,>=6.10.1 (from spacy)
  Using cached https://files.pythonhosted.org/packages/55/fd/e9f36081e6f53699943381858848f3b4d759e0dd03c43b98807dde34c252/thinc-6.10.2.tar.gz
Collecting plac<1.0.0,>=0.9.6 (from spacy)
  Using cached https://files.pythonhosted.org/packages/9e/9b/62c60d2f5bc135d2aa1d8c8a86aaf84edb719a59c7f11a4316259e61a298/plac-0.9.6-py2.py3-none-any.whl
Collecting pathlib (from spacy)
  Using cached https://files.pythonhosted.org/packages/ac/aa/9b065a76b9af472437a0059f77e8f962fe350438b927cb80184c32f075eb/pathlib-1.0.1.tar.gz
Collecting ujson>=1.35 (from spacy)
  Using cached https://files.pythonhosted.org/packages/16/c4/79f3409bc710559015464e5f49b9879430d8f87498ecdc335899732e5377/ujson-1.35.tar.gz
Collecting dill<0.3,>=0.2 (from spacy)
  Using cached https://files.pythonhosted.org/packages/6f/78/8b96476f4ae426db71c6e86a8e6a81407f015b34547e442291cd397b18f3/dill-0.2.8.2.tar.gz
Collecting regex==2017.4.5 (from spacy)
  Using cached https://files.pythonhosted.org/packages/36/62/c0c0d762ffd4ffaf39f372eb8561b8d491a11ace5a7884610424a8b40f95/regex-2017.04.05.tar.gz
Collecting wrapt (from thinc<6.11.0,>=6.10.1->spacy)
  Using cached https://files.pythonhosted.org/packages/a0/47/66897906448185fcb77fc3c2b1bc20ed0ecca81a0f2f88eda3fc5a34fc3d/wrapt-1.10.11.tar.gz
Collecting tqdm<5.0.0,>=4.10.0 (from thinc<6.11.0,>=6.10.1->spacy)
  Using cached https://files.pythonhosted.org/packages/93/24/6ab1df969db228aed36a648a8959d1027099ce45fad67532b9673d533318/tqdm-4.23.4-py2.py3-none-any.whl
Collecting cytoolz<0.9,>=0.8 (from thinc<6.11.0,>=6.10.1->spacy)
  Using cached https://files.pythonhosted.org/packages/0f/e6/ccc124714dcc1bd511e64ddafb4d5d20ada2533b92e3173a4cf09e0d0831/cytoolz-0.8.2.tar.gz
Requirement already satisfied: six<2.0.0,>=1.10.0 in /usr/local/lib/python3.6/dist-packages (from thinc<6.11.0,>=6.10.1->spacy) (1.11.0)
Requirement already satisfied: termcolor in /usr/local/lib/python3.6/dist-packages (from thinc<6.11.0,>=6.10.1->spacy) (1.1.0)
Collecting msgpack-python (from thinc<6.11.0,>=6.10.1->spacy)
  Using cached https://files.pythonhosted.org/packages/8a/20/6eca772d1a5830336f84aca1d8198e5a3f4715cd1c7fc36d3cc7f7185091/msgpack-python-0.5.6.tar.gz
Collecting msgpack-numpy==0.4.1 (from thinc<6.11.0,>=6.10.1->spacy)
  Using cached https://files.pythonhosted.org/packages/2e/43/393e30e2768b0357541ac95891f96b80ccc4d517e0dd2fa3042fc8926538/msgpack_numpy-0.4.1-py2.py3-none-any.whl
Requirement already satisfied: toolz>=0.8.0 in /usr/local/lib/python3.6/dist-packages (from cytoolz<0.9,>=0.8->thinc<6.11.0,>=6.10.1->spacy) (0.9.0)
Building wheels for collected packages: spacy, murmurhash, cymem, preshed, thinc, pathlib, ujson, dill, regex, wrapt, cytoolz, msgpack-python
  Running setup.py bdist_wheel for spacy ... - \ | / - \ | / - \ | / - \ |

 / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - done
  Stored in directory: /content/.cache/pip/wheels/fb/00/28/75c85d5135e7d9a100639137d1847d41e914ed16c962d467e4
  Running setup.py bdist_wheel for murmurhash ... - \ | / done
  Stored in directory: /content/.cache/pip/wheels/b8/94/a4/f69f8664cdc1098603df44771b7fec5fd1b3d8364cdd83f512
  Running setup.py bdist_wheel for cymem ... - \ done
  Stored in directory: /content/.cache/pip/wheels/55/8d/4a/f6328252aa2aaec0b1cb906fd96a1566d77f0f67701071ad13
  Running setup.py bdist_wheel for preshed ... - \ | / - \ | done
  Stored in directory: /content/.cache/pip/wheels/8f/85/06/2d132fb649a6bbcab22487e4147880a55b0dd0f4b18fdfd6b5
  Running setup.py bdist_wheel for thinc ... - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - done
  Stored in directory: /content/.cache/pip/wheels/d8/5c/3e/9acf5d9974fb1c9e7b467563ea5429c9325f67306e93147961
  Running setup.py bdist_wheel for pathlib ... - done
  Stored in directory: /content/.cache/pip/wheels/f9/b2/4a/68efdfe5093638a9918bd1bb734af625526e849487200aa171
  Running setup.py bdist_wheel for ujson ... - \ | / - \ done
  Stored in directory: /content/.cache/pip/wheels/28/77/e4/0311145b9c2e2f01470e744855131f9e34d6919687550f87d1
  Running setup.py bdist_wheel for dill ... - \ done
  Stored in directory: /content/.cache/pip/wheels/e2/5d/17/f87cb7751896ac629b435a8696f83ee75b11029f5d6f6bda72
  Running setup.py bdist_wheel for regex ... - \ | / - \ | done
  Stored in directory: /content/.cache/pip/wheels/75/07/38/3c16b529d50cb4e0cd3dbc7b75cece8a09c132692c74450b01
  Running setup.py bdist_wheel for wrapt ... - \ done
  Stored in directory: /content/.cache/pip/wheels/48/5d/04/22361a593e70d23b1f7746d932802efe1f0e523376a74f321e
  Running setup.py bdist_wheel for cytoolz ... - \ | / - \ | /

 done
  Stored in directory: /content/.cache/pip/wheels/f8/b1/86/c92e4d36b690208fff8471711b85eaa6bc6d19860a86199a09
  Running setup.py bdist_wheel for msgpack-python ... - \ | / done
  Stored in directory: /content/.cache/pip/wheels/d5/de/86/7fa56fda12511be47ea0808f3502bc879df4e63ab168ec0406
Successfully built spacy murmurhash cymem preshed thinc pathlib ujson dill regex wrapt cytoolz msgpack-python
Installing collected packages: murmurhash, cymem, preshed, wrapt, tqdm, cytoolz, plac, dill, pathlib, msgpack-python, msgpack-numpy, thinc, ujson, regex, spacy
Successfully installed cymem-1.31.2 cytoolz-0.8.2 dill-0.2.8.2 msgpack-numpy-0.4.1 msgpack-python-0.5.6 murmurhash-0.28.0 pathlib-1.0.1 plac-0.9.6 preshed-1.0.0 regex-2017.4.5 spacy-2.0.11 thinc-6.10.2 tqdm-4.23.4 ujson-1.35 wrapt-1.10.11
Collecting https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz (37.4MB)
    100% |████████████████████████████████| 37.4MB 2.5MB/s
Installing collected packages: en-core-web-sm
  Running setup.py install for en-core-web-sm ... - \

 done
Successfully installed en-core-web-sm-2.0.0

    Linking successful
    /usr/local/lib/python3.6/dist-packages/en_core_web_sm -->
    /usr/local/lib/python3.6/dist-packages/spacy/data/en

    You can now load the model via spacy.load('en')

CPU times: user 7.54 s, sys: 2.48 s, total: 10 s
Wall time: 5min 21s

In [0]:
!pip install xlrd

Requirement already satisfied: xlrd in /usr/local/lib/python3.6/dist-packages (1.1.0)

In [0]:
import pandas as pd
import xlrd
import numpy as np

In [0]:
%%time
xls = pd.ExcelFile('Jazz_Disc3_SJJune2018.xls')
df_ = []
df_.append(pd.read_excel(xls, 'albums'))
df_.append(pd.read_excel(xls, 'albums 1'))
df_.append(pd.read_excel(xls, 'albums 2'))
df_.append(pd.read_excel(xls, 'albums 3'))

values = []
values.append(df_[0]['location'].values)
values.append(df_[1]['location'].values)
values.append(df_[2]['location'].values)
values.append(df_[3]['location'].values)

for i in range(0,4):
  print(np.shape(values[i]))
  
valuesall = []
for i in range(0,4):
  for rowlist in values[i]:
    valuesall.append(rowlist)
    
print(len(valuesall))

(50000,)
(50000,)
(50000,)
(3961,)
153961
CPU times: user 27.6 s, sys: 287 ms, total: 27.9 s
Wall time: 27.9 s

In [0]:
df2 = pd.read_csv('world_cities.csv')
print(df2.columns)
subcoulist = df2['subcountry']
coulist = df2['country']
namelist = df2['name']


# subcoulist = np.unique(subcoulist)
coulist = np.unique(coulist)
namelist = np.unique(namelist)
                    
print(len(subcoulist))
print(len(coulist))
print(len(namelist))

Index(['name', 'country', 'subcountry', 'geonameid'], dtype='object')
23020
245
21942

In [0]:
df = pd.read_excel('jazz_albums.xlsx')

In [0]:
print(df.columns)

Index(['lid', 'rid', 'year', 'month', 'day', 'location', 'title',
       'carryForward', 'printDate', 'notes', 'session', 'city'],
      dtype='object')

In [0]:
citylist = df['city']
len(citylist)

153961

In [0]:
# citylist = citylist[0:100]
# print(citylist)

In [0]:
splitcitylist = []
for z,row in enumerate(citylist):
  splitcitylist.append(str(row).split('|'))

In [0]:
print(len(splitcitylist))

153961

In [0]:
%%time
#initially removing substring
newlist = []
for z,rowlist in enumerate(splitcitylist):
  templist = []
  for i,string1 in enumerate(rowlist):
    string1 = string1.strip()
    flag1 = 0
    flag2 = 0
    for j,string2 in enumerate(rowlist):
      if string1 in string2 and i != j:
        flag1 = 1
    if flag1 == 0:
      templist.append(string1)
  newlist.append(templist)
#   if z in range(115,120):
#     print(z,templist,rowlist)

CPU times: user 1.19 s, sys: 28 ms, total: 1.21 s
Wall time: 1.21 s

In [0]:
# for i,rowlist in enumerate(newlist):
#   if len(rowlist) > 1 and i < 1000:
# #     print(i+2,rowlist)

In [0]:
#removing common word and len> 3
longlist = []

commonword4 = ["empty","university","create","center","centre","date","march","holidays","holiday","same","summit","sunset","nord","orange","liberal","metro","prospect","elizabeth","papa","golden","mobile","sale","than","longview","best","state college","college"]



for i,rowlist in enumerate(newlist):
  temprow = []
  for ele in rowlist:
    ele = str(ele).lower()
    if len(ele) > 3 and ele not in commonword4 and "empty" not in ele: #ele.strip().lower() != "date" and ele.strip().lower() != "march":
      temprow.append(ele)
#     elif i < 1000:
# #       print(i+2,ele,rowlist)

  longlist.append(temprow)
 

print(len(longlist))

153961

In [0]:
i =23546
print(i,longlist[i],valuesall[i])

23546 ['los angeles'] Los Angeles, 1947

In [0]:
print(2500%1000)

500

In [0]:
%%time
#free vag subtring
vagfreelist = []

uniquelist1 = []


for i,rowlist in enumerate(longlist):
  temprow = []
  for ele1 in rowlist:
    ele1 = ele1
    flag1=0
    for token in en_nlp(str(valuesall[i])):
      if token.lower_.strip() == ele1:
        flag1 = 1
    
    counttoken = 0
    for token in en_nlp(str(ele1)):
      counttoken+=1
    if flag1 == 1 or counttoken>1 or ele1 == 'mila' or ele1 == 'chile':
      if ele1 == 'mila' and 'milan' in str(str(valuesall[i]).lower()):
        temprow.append(ele1)
      else:
        temprow.append(ele1)
    else:
      if ele1 not in uniquelist1:
        uniquelist1.append(ele1)
        print(str(i) + ") "+str(ele1) +"------>" + str(rowlist) +"-------"+ str(valuesall[i]))
  vagfreelist.append(temprow)

27) illingen------>['germany', 'illingen']-------Villingen, Germany
39) galle------>['schaffhausen', 'galle', 'switzerland']-------Vebikus Art Gallery, Schaffhausen, Switzerland
161) lingen------>['germany', 'lingen']-------Reilingen, Germany
185) west------>['west']-------Westwood, MA, April-May 1995
202) bell------>['bell', 'salem']-------LuBell Farm, South Salem
232) kent------>['fukushima', 'japan', 'kent']-------Kentfield, CA & Fukushima Concert Hall, Japan
297) vite------>['vite', 'porsgrunn']-------"Det Hvite Hus", Porsgrunn, March 9-11, 1985
312) berlin------>['ohio', 'berlin']-------Finney Chapel, Oberlin, Ohio
334) green------>['rhode island', 'green', 'west']-------West Greenwich, Rhode Island, July 27, 28 & 29, 1992
348) mateur------>['dusseldorf', 'mateur']-------Live "Deutsches Amateur Jazz Festival 1959", Dusseldorf
350) halle------>['germany', 'halle', 'hamburg']-------Live "Musikhalle", Hamburg, Germany
443) mons------>['holland', 'mons']-------Monster, Holland
497) cham------>['finland', 'cham']-------Live "Kuhmo Chamber Music Festival", Finland
504) uran------>['uran']-------Restaurang Applet, Umel Folkets Hus, Nordic Swing Festival
737) basti------>['basti']-------San Sebastien
859) oran------>['oran', 'stockholm']-------Stockholm & St. Goran's Chapel, Jesater, spring, 1991
862) lund------>['lund', 'deva']-------Lundevad
862) deva------>['lund', 'deva']-------Lundevad
1012) chin------>['chin', 'stockholm']-------Live "Jazzclub Fasching", Stockholm
1166) lage------>['lage', 'new york']-------Live "Village Gate", New York
1266) arhus------>['arhus']-------Aarhus
1272) pala------>['paris', 'pala']-------Live "Palais des Congres", Paris
1318) chur------>['chur', 'helsinki']-------Live "Temppeliaukio Church", Helsinki
1322) iona------>['germany', 'iona', 'moers']-------Live "Moers International New Jazz Festival", Germany
1351) beli------>['beli', 'new york']-------Make Believe Ballroom Jam Session, New York
1353) turda------>['turda', 'new york']-------"Saturday Night Swing Club", New York
1554) basel------>['westminster', 'colorado', 'basel']-------Westminster, Golden & Basels, Colorado
1588) roth------>['roth']-------Live "The Ritz", Rothesay
1596) asino------>['basel', 'asino']-------"Stadtcasino", Basel
1692) nadi------>['toronto', 'nadi']-------Native Canadian Centre, Toronto
1779) salto------>['salto']-------Cessalto, June 3, 4, 17 & 18, 1995
1893) oulu------>['oulu', 'helsinki']-------"Kauppakorkeakoulu", Helsinki
2022) tura------>['euclid', 'tura', 'ohio']-------Shore Cultural Centre, Euclid, Ohio, September 18 & 19, 1992
2029) bury------>['bury', 'connecticut']-------Southbury, Connecticut
2041) luzern------>['luzern']-------Luzerne, August 17 & 18 and September, 1987
2057) tata------>['mila', 'magna', 'tata']-------Live "Aula Magna Univ. Statale", Milan
2077) zion------>['zion', 'indi', 'rome']-------Concert, "Alpheus Club", Controindicazioni 5. Festival, Rome
2077) indi------>['zion', 'indi', 'rome']-------Concert, "Alpheus Club", Controindicazioni 5. Festival, Rome
2087) anta------>['italy', 'noci', 'chur', 'anta', 'chia']-------Europa Jazz Festival, Church of Santa Chiara, Noci, Italy
2087) chia------>['italy', 'noci', 'chur', 'anta', 'chia']-------Europa Jazz Festival, Church of Santa Chiara, Noci, Italy
2115) mori------>['mori', 'japan', 'oria', 'tokyo']-------Live "Hitomi Memorial Hall", Tokyo, Japan
2115) oria------>['mori', 'japan', 'oria', 'tokyo']-------Live "Hitomi Memorial Hall", Tokyo, Japan
2157) everett------>['everett']-------Leverett, MA
2166) east------>['east', 'tauranga']-------21st Tauranga Jazz Festival, Easter 1983
2400) gien------>['germany', 'east', 'gien', 'dresden']-------Concert "Hygiene-Museum", Dresden, East Germany
2446) chas------>['copenhagen', 'chas']-------SteepleChase digital recording studio, Copenhagen ?
2547) lier------>['lier']-------Schlieren, December 5 & 6, 1984
2606) horst------>['horst']-------Nederhorst den Berg, March 22 & 23, April 13, 1972
2700) rubi------>['rubi']-------Rubigen, Switerland
2783) essen------>['essen']-------Diessen, Ammersee
2787) tena------>['tena']-------Chantenay-Villedieu
2796) aubagne------>['aubagne', 'france']-------Live "Theatre d'Aubagne", Yerre, France
2798) pace------>['villeurbanne', 'pace', 'tonk']-------l'Espace Tonkin de Villeurbanne
2798) tonk------>['villeurbanne', 'pace', 'tonk']-------l'Espace Tonkin de Villeurbanne
2848) amberg------>['vienna', 'amberg']-------Vienna, November 1983 & Bisamberg, December 1983
3062) para------>['new york', 'para', 'arad']-------rehearsal for "Your Hit Parade", New York
3062) arad------>['new york', 'para', 'arad']-------rehearsal for "Your Hit Parade", New York
3113) labo------>['new york', 'labo']-------CBS Broadcast "Jazz Laboratory", New York

3185) nema------>['paris', 'nema', 'cine', 'london']-------BBC Broadcast, Paris Cinema Studio, London
3185) cine------>['paris', 'nema', 'cine', 'london']-------BBC Broadcast, Paris Cinema Studio, London
3390) vera------>['vera', 'new york']-------New York, several dates
3416) slovakia------>['slovakia', 'oslo', 'prague']-------Prague, Czechoslovakia, October 10-14, 1977
3416) oslo------>['slovakia', 'oslo', 'prague']-------Prague, Czechoslovakia, October 10-14, 1977
3434) aron------>['aron']-------Aaron Bridges apartment, 1981-1984
3552) ende------>['montreal', 'quebec', 'ende']-------The Rendez-Vous, Montreal, Quebec
3573) chor------>['chor', 'islington', 'london']-------"Hope & Anchor", Islington, London
3615) lala------>['lala']-------Bratislalava
3790) allen------>['norway', 'halle', 'bergen', 'allen']-------Greighallen, Bergen, Norway, November-December 1990
3835) palin------>['palin', 'lausanne']-------Epalinges, Lausanne
3890) hesse------>['hesse', 'essen']-------Wilhelmbad-Hessen, April 24 & 25, 1979
3892) buchen------>['hanover', 'buchen']-------"Wachenbuchen", Hanover
3922) rano------>['france', 'bergerac', 'rano']-------Centre Cyrano de Bergerac, Val d'Oise, France
4120) erie------>['kitchener', 'erie', 'ontario', 'sens']-------Live, CKCO TV series "Swing Sensation", Kitchener, Ontario
4120) sens------>['kitchener', 'erie', 'ontario', 'sens']-------Live, CKCO TV series "Swing Sensation", Kitchener, Ontario
4228) hame------>['hame', 'finland', 'helsinki']-------Helsinki and Hameenfinna, Finland, April 1982 & July 1983
4403) edinburg------>['edinburg']-------Concert "Queen's Hall", Edinburgh
4416) palo------>['palo', 'santa cruz']-------Live "Palookaville", Santa Cruz, CA, January 24-26, 1995
4419) larne------>['larne', 'san francisco']-------Live "Blarney Castle", San Francisco, CA
4483) basi------>['east', 'new york', 'basi']-------Live "Basin Street East", New York
4525) concord------>['concord', 'england', 'southampton']-------Live "Concorde Club", Southampton, England
4654) salo------>['paris', 'salo', 'france']-------Live "Le Crazy Horse Saloon", Paris, France c. 1964
4694) melo------>['new york', 'melo']-------"Melody and Madness" show, rehearsal transcription, New York
4765) carlet------>['boston', 'carlet']-------Radio Broadcast, Ritz Carleton, Boston, Mass
4872) nava------>['nava', 'san diego', 'pita']-------Radio show "Spotlight Bands", Naval Hospital, San Diego, CA
4872) pita------>['nava', 'san diego', 'pita']-------Radio show "Spotlight Bands", Naval Hospital, San Diego, CA
5167) mason------>['san francisco', 'mason']-------Concert "Masonic Auditorium", San Francisco, CA
5230) ilion------>['concord', 'ilion']-------Live "Concord Pavilion", Concord, CA
5281) agra------>['agra', 'magna']-------Magnagraphics Studio, unidentified city
5281) magna------>['agra', 'magna']-------Magnagraphics Studio, unidentified city
5329) trat------>['trat', 'rath', 'birmingham']-------Live "Strathallan Hotel", Birmingham
5329) rath------>['trat', 'rath', 'birmingham']-------Live "Strathallan Hotel", Birmingham
5515) parnas------>['paris', 'parnas', 'asse']-------Live "Petit Journal Montparnasse", Paris, June 5 & 6, 1996
5515) asse------>['paris', 'parnas', 'asse']-------Live "Petit Journal Montparnasse", Paris, June 5 & 6, 1996
5609) neral------>['indiana', 'neral', 'bury', 'pita', 'wakema']-------"Camp Atterbury, Wakeman General Hospital", Indiana
5609) wakema------>['indiana', 'neral', 'bury', 'pita', 'wakema']-------"Camp Atterbury, Wakeman General Hospital", Indiana
5767) keta------>['keta', 'tokyo']-------Live "Aketa's Shop", Tokyo
5836) asahi------>['japan', 'asahi', 'tokyo']-------Live "Asahiseimei Hall", Tokyo, Japan
6170) orai------>['orai', 'royan']-------Royan, Francia, Festival de Musique Contemporaine
6173) vari------>['vari']-------various locations, Europe
6176) axim------>['paris', 'erie', 'axim']-------Galerie Maximilien, Guiol, Paris
6285) valle------>['valle']-------"Bull Valley Inn", Port Costa, CA
6407) brooklyn------>['brooklyn']-------North Haven, Conn., Aug 15, 1985/Brooklyn, NY, Jan 10, 1986
6476) anna------>['anna', 'anda']-------Annandale, c. early 1990's
6476) anda------>['anna', 'anda']-------Annandale, c. early 1990's
6789) cali------>['los angeles', 'cali']-------Royce Hall, University of Californa, Los Angeles
6846) genc------>['cincinnati', 'ohio', 'genc']-------Live "Hyatt Regency Hotel", Cincinnati, Ohio
7129) eden------>['eden', 'holland']-------Cafe Sint Joris, St. Oedenrode, Holland
7792) winterhude------>['germany', 'winterhude', 'hamburg']-------"Winterhuder Fahrhaus", Hamburg, Germany
8761) tema------>['new york', 'tema']-------WJZ Broadcast "Paul Whiteman Show", New York, 9:45pm

8965) male------>['paris', 'male', 'france', 'normal']-------"L'ecole Normale de Musique", Paris, France
8965) normal------>['paris', 'male', 'france', 'normal']-------"L'ecole Normale de Musique", Paris, France
9080) acre------>['italy', 'acre']-------Live "Acreale Jazz Festival", Acreale, Italy
9158) lebu------>['vermont', 'bury', 'lebu']-------Concert Hall *, Middlebury, Vermont, August 18, 19, 20, 1993
9320) mandi------>['nanterre', 'mandi']-------Live "Theatre des Amandiers", Nanterre
9322) ouest------>['paris', 'ouest']-------Concert "Theatre de L'Ouest Parisien", Paris
9340) antibes------>['antibes']-------Live "Jazzfestival d'Antibes", Juan-les-Pins
9417) erba------>['erba', 'maassluis']-------Live "De Toverbal", Maassluis
9428) york------>['england', 'sheffield', 'york']-------Sheffield, South Yorkshire, England, Nov 1995 & Feb 1996
9430) fords------>['england', 'fords', 'luton']-------Luton, Befordshire, England, November 1995 & February 1996
9570) bear------>['bear']-------Bearsville, NY
9587) arta------>['denver', 'arta']-------Live "Vartan Jazz", Denver, CO
9700) tanda------>['hollywood', 'tanda']-------Standard transcriptions, Hollywood, CA, c. early Sept, 1944
9702) tual------>['hollywood', 'tual']-------KHJ Mutual Network Broadcast, Hollywood, CA
9716) auch------>['france', 'tours', 'auch']-------Live "Petit Faucheux", Tours, France, March 27-29, 1992
9729) herat------>['herat', 'monterey']-------Live "Monterey Sheraton Hotel", Monterey, CA
9751) uden------>['uden']-------Live, Bar "De Heksenketel", Udenhout
9915) ovalle------>['ovalle']-------Scantinato di Morrovalle
9924) hermitage------>['hermitage', 'montreal']-------L'Hermitage, Montreal
10286) palmer------>['palmer']-------Palmero, April 13 & 14, 1991
10494) attleboro------>['vermont', 'chelsea', 'attleboro']-------Live "Chelsea House", Brattleboro, Vermont
10508) leon------>['hame', 'leon', 'san francisco', 'cham']-------Live "Chameleon", San Francisco, CA
10614) pali------>['pali', 'vancouver']-------Vancouver, BC & Pacific Palisades, CA
10732) barra------>['paris', 'barra', 'france']-------Dufayel Barracks, Paris, France
10782) bria------>['bria', 'uran']-------Live "The Hamlet Restaurant", Cambria, CA, July 1-2, 1994
11034) ahal------>['india', 'ahal']-------Taj Mahal & Karla Caves, India, February/March 1980
11073) hilo------>['hilo', 'chur']-------Old St. Hilory's Church, Tiburon, CA, Sept, 1977 & Jan, 1978
11305) lyon------>['lyon', 'york']-------Lyons Concert Hall, York University
11485) marks------>['marks', 'copenhagen', 'denmark']-------Denmarks Radio, Studio 3, Copenhagen
11485) denmark------>['marks', 'copenhagen', 'denmark']-------Denmarks Radio, Studio 3, Copenhagen
11498) kungalv------>['kungalv']-------Kungalve
11626) ausa------>['ausa']-------Sausalito, CA, June 11 & 12, 1992
11761) ewing------>['ewing']-------Newington, Conn.
12146) ozar------>['ozar', 'praha']-------"Mozarteum Studio", Praha
12232) ales------>['germany', 'ales', 'iona', 'dresden']-------Internationales Dixieland-Festival, Dresden, Germany
12241) bali------>['bali']-------Torokbalint
12242) boli------>['boli']-------Torokbolint, summer 1990
12382) london------>['london']-------Londong
12744) france------>['france', 'tours', 'auch']-------Live "au Petit Faucheux", Tours, Frances, March 18-20, 1993
12756) enkoping------>['enkoping']-------Enkopings Old Courthouse, March & April 1998
12882) pila------>['luzern', 'pila', 'switzerland']-------Pilatus Festival, Luzern, Switzerland
13009) ames------>['kingston', 'hame', 'ames']-------Kingston-Upon-Thames
13061) yushu------>['yushu']-------Kyushu
13246) bern------>['bern', 'switzerland']-------Jazz Festival, Berne, Switzerland
13253) fuji------>['concord', 'japan', 'fuji', 'tokyo']-------Live "Fujitsu-Concord Jazz Festival", Tokyo, Japan
13298) hede------>['germany', 'hede', 'heidelberg']-------Live "Heidelberg Jazz Festival", Hedelberg, Germany
13586) aspe------>['colorado', 'aspe']-------Live (*), Aspen, Colorado, February 27 & 29, 1968
13606) hayward------>['hayward', 'england']-------Live "Fox and Hounds", Haywards Heath, Sussex, England
13759) naka------>['japan', 'naka', 'tokyo']-------Live "Nakana Sun Plaza Hall", Tokyo, Japan, June 20, 1980

13822) anan------>['anan', 'stockholm']-------Live "Kagelbanan", Stockholm
13825) wedi------>['wedi']-------The Swedish Radio, Gothenburg
14051) kandi------>['kandi', 'uppsala']-------Live, Skandia Theatre, Uppsala
14112) worcester------>['worcester']-------Bewdley, Worcestershire, late August 1977
14164) arai------>['arai', 'finland', 'para']-------Villa Riner, Parainen, Finland
14208) bergen------>['bergen']-------Spitsbergen
14215) tala------>['florida', 'tala', 'asse']-------Talahasse, Florida, spring 1995
14251) layton------>['layton']-------prob. Laytonsville, MD
14265) loos------>['loos']-------Live, Jachthaven Van Dijk, Oud-Loosdrecht
14337) alba------>['alba', 'wettingen']-------Live "Saalbau Tagerhard", Wettingen
14339) eger------>['eger']-------Live "Jazz Club Aegerten", Aegerten, late October 1984
14569) dour------>['hollywood', 'dour', 'badou']-------Live "The Troubadour", Hollywood, CA, early 1972
14569) badou------>['hollywood', 'dour', 'badou']-------Live "The Troubadour", Hollywood, CA, early 1972
14835) inza------>['inza', 'tokyo']-------Live "Ginza Hall", Tokyo
14865) tsukuba------>['tsukuba']-------Tsukubagakuen, City, December 12 & 13, 1985
15190) idil------>['idil', 'vilnius', 'dili']-------Live "Vaidilios", Vilnius
15190) dili------>['idil', 'vilnius', 'dili']-------Live "Vaidilios", Vilnius
15206) verl------>['verl']-------Silverlake, CA
15454) pati------>['washington', 'pati']-------Broadcast "Olivia's Patio Lounge", Washington DC
15470) choco------>['choco', 'england', 'london']-------Chocolate Factory, London, England
15594) onda------>['france', 'onda', 'vence']-------Concert "Fondation Maeght", St Paul de Vence, France
15872) fontaine------>['france', 'fontaine']-------Pernes Les Fontaines, France, September 17, 18 & 19, 1992
15899) isser------>['isser', 'switzerland', 'zurich']-------Live "Weisser Wind", Zurich, Switzerland
16005) agar------>['agar', 'new york']-------Broadcast "Jack Teagarden Show", New York
16165) porto------>['porto', 'serra']-------Live "Casa de Serralves", Oporto
16165) serra------>['porto', 'serra']-------Live "Casa de Serralves", Oporto
16435) arles------>['iowa', 'arles']-------Fine Arts Festival, Charles City, Iowa, Mar 19-May 19, 1973
16485) contai------>['uster', 'contai', 'switzerland']-------Live "Jazzclub Container", Uster, Switzerland
16559) amiens------>['amiens']-------La Maison de la Culture D'amiens, January 26, 27 & 28, 1991
16567) mati------>['thailand', 'bangkok', 'mati']-------Bangkok, Thailand, c. mid December 1956, matinee
16588) marte------>['copenhagen', 'marte']-------Live, Montmarte, Copenhagen
16594) orsha------>['orsha']-------Thorshavn, Farao Islands
17309) leigh------>['concord', 'east', 'england', 'leigh']-------Live "Concorde Club", Eastleigh, Hampshire, England
17326) lins------>['lins']-------Colinsville & Sappington, Ill., early 1960's
17658) leme------>['leme']-------Live, Thornhill Elementary School, unidentified city
17669) wesel------>['wesel', 'connecticut']-------"Weseley University", Connecticut
17916) pisco------>['pisco', 'savannah', 'chur']-------Christ Episcopal Church, Savannah, GA
17960) oman------>['rockland', 'oman']-------PianoMania, Rockland, CA, November 15-18, 1993
17977) gava------>['gava']-------Morgongava
18427) susa------>['nagano', 'susa', 'usak']-------Live "Susaka-City Mesena Hall", Nagano
18427) usak------>['nagano', 'susa', 'usak']-------Live "Susaka-City Mesena Hall", Nagano
18655) leek------>['ottawa', 'leek']-------Vankleek Hill Auditorium, Ottawa
18668) nehe------>['nehe']-------Toneheim, Ridabu
18751) bato------>['bato', 'san lorenzo']-------San Lorenzo di Sebato, BZ
18884) mari------>['germany', 'mari', 'gelsenkirchen']-------Live, Hotel Maritim, Gelsenkirchen, Germany
19145) cimin------>['cimin', 'catania']-------"La Ciminiera", Catania
19269) timon------>['timon', 'maryland']-------Timonium, Maryland
19349) kulu------>['kulu', 'zagreb']-------Live "GSP Kulusic", Zagreb, Yugoslavia
19363) arlington------>['arlington', 'england']-------Live "Darlington Arts Centre", England
19460) saco------>['geneva', 'saco']-------Right Side Jazz Club, Grand-Saconnex/Geneva
19485) lens------>['lens']-------Glenside, PA
19490) ahaus------>['ahaus', 'germany', 'munich']-------Amerikahaus, Munich, Germany

19764) chios------>['mila', 'chios']-------Live "Teatro dei Chiostri", Milan
19887) elst------>['germany', 'esslingen', 'elst', 'asse']-------Live "Dieselstrasse", Esslingen, Germany
19899) hama------>['japan', 'hama']-------Live, 2nd Yamaha Festival Hamatsu, Japan
19970) luce------>['prague', 'luce']-------"Lucerna Hall", Prague, October 13-16, 1965
20087) imperial------>['genoa', 'imperial']-------Parco di Villa Imperiale, Genoa
20328) rees------>['rees', 'shreveport']-------Live at "Humpfrees", Shreveport, LA.
20499) meta------>['meta']-------Metarie, LA, April 17 & June 6, 1987
20575) multan------>['multan', 'newark']-------Simultaneous Radio/TV Cast, Newark, N.J.
20648) hurst------>['hurst']-------Chiselhurst Caves
20777) kemi------>['kemi']-------Live "Watchung View Inn", Pluckemin, N.J.
20873) mali------>['indi', 'mali']-------"Indigo Ranch", Malibu, CA
20922) come------>['paris', 'come', 'cham']-------Comedie Des Champs Elysees, Paris
20928) rades------>['rades']-------Live, Prades-Le-Lez
21235) oyama------>['oyama', 'tokyo']-------Live "Aoyama Town Hall", Tokyo
21236) ruma------>['tokyo', 'ruma']-------Live "Iruma City Hall", Tokyo (?)
21348) hagen------>['hagen', 'resen', 'hattingen']-------Live, Fresenhagen, summer 1983 & Hattingen
21348) resen------>['hagen', 'resen', 'hattingen']-------Live, Fresenhagen, summer 1983 & Hattingen
21358) nice------>['nice', 'mamou']-------Mamou & Eunice, La.
21428) oral------>['oral', 'miami']-------Gusman Concert Hall, University Of Miami, Coral Cables, Fa.
21606) walker------>['walker', 'switzerland']-------Live "Moonwalker Club", Aarburg, Switzerland
21802) baar------>['baar']-------Baarm
22116) ondo------>['new york', 'ondo']-------Live "Eddie Condon's", New York
22433) opole------>['new york', 'opole']-------"Metropole Cafe", New York
22715) garland------>['garland', 'texas']-------Goree State Farm, Sugarland, Texas, c. April 1934
22749) adam------>['adam', 'plantation', 'columbia']-------Brevard Plantation, Adams Hill, Columbia, 1939
22816) oxford------>['england', 'fords', 'oxford']-------Oxfordshire, England, November 12 or December 11, 1974
23286) beek------>['beek']-------Oosterbeek
23303) etampes------>['paris', 'etampes']-------"Theatre d'Etampes", Paris April 15 & 20, 1976
23313) dreieich------>['dreieich']-------Live "Burg", Dreieichenhain
23441) charlotte------>['charlotte']-------Charlottesville
23951) cocoa------>['cocoa', 'new york']-------"Cocoanut Groove", Hotel Ambassador, New York
24384) gent------>['gent', 'denmark']-------Gentofte, Denmark
24493) ucar------>['ucar', 'pala']-------"S.R. Palace Concert Hall", Bucarest
24500) doka------>['tokyo', 'doka']-------Budokan, Tokyo
25325) selm------>['selm']-------San Anselmo Ca., c. early 1980's
25539) hamme------>['hamme', 'london', 'pala']-------"Hammersmith Palace", London
25741) agen------>['england', 'agen', 'essex']-------Dagenham, Essex, England
25818) elsdorf------>['austria', 'elsdorf']-------Nickelsdorf Konfrontationen, Nickelsdorf, Austria
25820) leverkusen------>['leverkusen']-------Live "Leverkusener Jazztage '89"
26074) konz------>['halle', 'wertheim', 'konz']-------"Konzerthalle", Wertheim
26076) asten------>['frankfurt', 'asten']-------"Sinkkasten", Frankfurt am Main
26600) asti------>['asti']-------Broadcasts "Macquarie Broadcasting Network", 1949
26888) rama------>['rama', 'paris']-------"Jazzorama TV-Show", Paris, c. June 1958
26921) bradley------>['bradley', 'new york']-------"Bradleys", New York
27146) bush------>['bush', 'sydney']-------"Homebush", Sydney
27489) lamin------>['los angeles', 'lamin']-------Flamingo Hotel, Los Angeles
27583) sarno------>['budapest', 'sarno']-------"Sportcsarnok", Budapest
27974) sete------>['sete', 'oslo']-------Live, "Sporten", Frognerseteren, Oslo
28535) huizen------>['huizen']-------Zevenhuizen
28780) bals------>['bals']-------"Fidergardsskilan", Balsta, March 4-5, 1978
29477) tula------>['tula', 'new orleans']-------"McAllister Hall", Tulane, Univ., New Orleans
29721) raver------>['raver', 'michigan']-------Traverse City, Michigan

29778) uray------>['ann arbor', 'uray']-------Ann Arbor, Januray 29/February 1, 1961
30258) paris------>['paris', 'new orleans']-------"Parisian Room", New Orleans
30688) ranst------>['derby', 'ranst']-------"Granstand Hotel", Derby
30702) duiven------>['duiven']-------Duivendrecht
30703) istra------>['amsterdam', 'istra']-------Live, Spuistraat, Amsterdam
30734) brak------>['brak', 'amsterdam']-------Live "Theater De Brakke Grond", Amsterdam
30747) brugge------>['brugge']-------Baambrugge, September 4, 5, 6 & 7, 1978
30752) vreden------>['utrecht', 'vreden']-------"Vredenburg Music Centre", Utrecht
30992) arvi------>['arvi']-------Arvika, August 26-28, 1983
31212) godo------>['godo']-------Godorf
31508) aiken------>['hirosaki', 'japan', 'aiken']-------Hirosaki Shiminkaiken, Japan
32000) umbria------>['umbria', 'england']-------Live "The Outgate Inn", Nr. Hawkshead, Cumbria, England
33478) agde------>['agde', 'toronto', 'chur', 'canada', 'mary']-------The Church of St. Mary Magdelene, Toronto, Canada
34131) tera------>['mori', 'oria', 'detroit', 'tera']-------"Veterans Memorial Building Ballroom", Detroit
34719) roman------>['italy', 'roman', 'verona']-------Live "Teatro Romano", Verona, Italy
34981) catu------>['catu', 'illinois']-------Live, Dacatur, Illinois, January 30-31, & February 1, 1976
35539) munster------>['munster']-------Munstergeleen
35992) colon------>['ohio', 'colon', 'dayton']-------Live "Colony Club", Dayton, Ohio, unknown date, 1970's ?
36496) mutuali------>['mutuali', 'paris', 'france']-------Live "Salle de la Mutualite", 2nd set, Paris, France
36644) elmina------>['dongen', 'elmina']-------Live "Zaal Wilhelmina", Dongen
36665) bedford------>['fords', 'bedford']-------Bedfordshire
36770) olympia------>['paris', 'olympia']-------Live "Theatre De L'Olympia", Paris, November 18, 1961
36809) tivoli------>['copenhagen', 'tivoli']-------"Tivolis Koncertsal", Copenhagen
36943) arish------>['paris', 'england', 'chur', 'arish']-------Saffron Walden Parish Church, England
36945) eagle------>['london', 'eagle', 'blackheath']-------Eaglesfield School, Blackheath, London
38015) aden------>['freiburg', 'aden']-------Live "Arkadenhof, Alte Universitat", Freiburg
38071) most------>['udine', 'most', 'palamos']-------"Palamostra Auditorium", Udine
38071) palamos------>['udine', 'most', 'palamos']-------"Palamostra Auditorium", Udine
38202) quimper------>['quimper']-------"Hotte House", Quimperle
39418) maur------>['maur', 'toronto', 'canada']-------"DuMaurier Jazz Festival", Toronto, Canada, July 1990
39986) kant------>['martin', 'kassel', 'kant']-------Kantorei an St Martin, Kassel
40229) villeta------>['france', 'villeta']-------Villetaneuse, France
40527) tete------>['tete', 'uppsala']-------Broadcast "Universitetets Aula", Uppsala, Sweden
40780) ware------>['atlanta', 'ware']-------Live, "Ruby Red's Warehouse, Underground Atlanta", Atlanta
40783) merida------>['merida']-------Meridan, Conn.
40793) assis------>['assis']-------Live "Bratwursthaus, Manassis Festival", Va., December 1972
40798) manasa------>['virginia', 'manasa']-------Manasas, Virginia
40913) cove------>['london', 'cove']-------Live "Covent Garden Jazz Saxophone Festival", London
41277) bari------>['bari']-------"Tabaris Dancing", Den Haag, 1936
41563) borne------>['borne']-------Bornerbroek
41699) lakes------>['lakes', 'toronto']-------Live "Lakeshore Inn", Toronto
41713) much------>['much']-------Muchen, May 4-6, 1984
41809) schio------>['schio']-------Live "Maschio Angioino", Napels
41930) emmen------>['emmen', 'leuven']-------Live "Lemmens Instituut", Leuven
41965) meda------>['meda', 'leme']-------Alemeda, CA, January-February, 1983
42167) fussa------>['fussa', 'austria']-------Fussach, Austria, December 1982 & January 1983
42423) gonen------>['gonen', 'umea']-------"Dragonen", Umea
43627) marin------>['marin']-------Marine Transcriptions, c. December 1950
43742) sylvania------>['sylvania', 'new york']-------Broadcast "Cafe Rouge, Hotel Pannsylvania", New York
43889) india------>['india']-------Indiantown Cap, Pa.
44424) norman------>['norman', 'france', 'mandi']-------Normandie, France

44906) fili------>['fili', 'stockholm']-------"Filial of the Museum of Modern Art", Stockholm, Sweden
45245) einbeck------>['einbeck', 'hamburg']-------Hamburg/Reinbeck
45609) stoughton------>['cambridge', 'stoughton']-------Cambridge, Aug 2/Sept 27, 1987,Stoughton, Mass, Jan 31, 1988
45726) uman------>['uman', 'ucar']-------Bucarest, Roumania
45731) loni------>['salo', 'greece', 'loni']-------Thessalonika, Greece, January 22 & 23, 1990
46598) amli------>['chur', 'amli']-------Hamline United Methodist Church, July 5 & 6, 1986
46899) gloucester------>['gloucester']-------Inglestone Common, Gloucestershire, c. summer 1971
46960) george------>['new york', 'chur', 'george']-------"St. Georges Church", New York
47417) boom------>['boom', 'new york']-------Live "At Boomers", New York, May 14-15, 1976
47570) nardo------>['bern', 'nardo', 'hollywood', 'mesa', 'kearny']-------Rancho Bernardo, Kearny Mesa & Hollywood, June'86/April 1987
47624) thun------>['las vegas', 'thun', 'nevada']-------Live "The Thunderbird", Las Vegas, Nevada, poss c. 1960's
47925) adoni------>['adoni']-------"Theater Adonis", IH' Dimitria
47926) vise------>['vise', 'thessaloniki']-------Live "2nd Jazz & Improvised Music Festival", Thessaloniki
48270) enzan------>['italy', 'enzan']-------Calenzano, Italy, September 25 to December 10, 1987
49047) union------>['union']-------Unionville, CT
49384) erbil------>['george', 'erbil']-------"George Vanderbilt Hotel", Ashville, N.C.
49772) amsterdam------>['amsterdam', 'berlin']-------Berlin ?/Amsterdam ? c. 1938
49990) dresden------>['ales', 'iona', 'dresden', 'pala']-------"Internationales Dixieland Festival Dresden","Kulterpalast"
50193) haarlem------>['holland', 'haarlem']-------Live "Haarlemse Jazzclub", Haalem, Holland
50535) egra------>['egra', 'england', 'london', 'conway']-------"Club Integral - Conway Hall", London, England
50700) lisle------>['lisle', 'cali']-------Calisle, MA
50806) silvan------>['silvan']-------Montesilvano
50833) shima------>['chur', 'shima', 'osaka']-------Live "Shimanouchi Church", Osaka
50871) alesund------>['norway', 'alesund']-------Aalesund, Norway, c. 1992
51995) upata------>['italy', 'bologna', 'upata']-------Live "Fabbrika Occupata", Bologna, Italy
52820) champa------>['champa']-------Champagnac, (Ardeche), September 23-27, 1992
52902) adrian------>['adrian', 'italy', 'rome']-------Live "Adriano Theatre", Rome, Italy
53148) meaux------>['hame', 'meaux']-------Magny-les-Hameaux, June 28, 29 & 30, 1984
53508) andes------>['germany', 'munster', 'andes', 'west']-------Live "Landesmuseum", Munster, West Germany
53550) victoria------>['melbourne', 'victoria']-------Live "Victorian Jazz Club", Melbourne
53569) ostend------>['ostend', 'belgium', 'ende']-------Live "De Artiest", Oostende, Belgium
54607) adler------>['england', 'adler']-------Live "Lilian Baylis Theatre", Sadlers Wells, England
54838) amur------>['japan', 'amur', 'tokyo']-------Live "Bunkamura Theatre Cocoon", Tokyo, Japan
55311) northeast------>['boston', 'northeast']-------Northeaster Univ. Boston, spring 1969
55408) mitte------>['mitte']-------"Jazzkoncert Mitternacht in Munchen", Munchen
56219) buka------>['buka']-------Bukarest
56259) mora------>['mora']-------Bollmora, spring 1956
56430) yuki------>['japan', 'hiroshima', 'yuki']-------Live "Miyuki-kaikan", Hiroshima, Japan
56436) lome------>['hilo', 'france', 'lome']-------"Chapelle Sainte Philomene", Puget-Ville, France
57522) hamm------>['hamm']-------Hallstahammar, October 1980 & February 1981
57807) enem------>['germany', 'enem', 'gien', 'dresden']-------"Kongressaal Hygienemuseum", Dresden, Germany
57816) losal------>['vasteras', 'losal']-------Hasslosalen, Vasteras, Sweden
59341) buri------>['buri', 'italy']-------"White Room", Castel Burio, Italy, May 27 & 28, 1990
59397) rura------>['madrid', 'spain', 'rura']-------Madrid, Spain, late Februrary 1968
59747) lisse------>['pirmasens', 'lisse']-------Live "Neue Kulisse, Pirmasens"
60521) pinner------>['pinner']-------"Alte Ravensberger Spinnerei", Bielfeld, Oct 29-30, 1990
61193) ticul------>['london', 'ticul', 'tura']-------"Horticultural Hall", London

61622) arrah------>['nevada', 'arrah']-------Live "Harrah's Club", Lake Tahoe, Nevada
61800) lere------>['florida', 'lere']-------Cleremont, Florida
61948) assen------>['germany', 'bremen', 'assen', 'tera']-------Live "Weserterassen", 211th Dacapo Concert, Bremen, Germany
62533) aral------>['aral']-------Recorded at the home of Saralee Halprin, concert pianist
62903) pori------>['pori']-------"Emporium of Jazz", Mendota, Minn., 1970
62925) ruse------>['germany', 'ruse', 'frankfurt']-------Frankfurt & Oberusel, Germany, November 3 & 8, 1981
63331) piro------>['los angeles', 'piro']-------Artie Shapiro's home, Los Angeles
63676) kota------>['japan', 'kota']-------Live, Yokota, Japan
63819) laur------>['laur']-------Valauris
63892) anjo------>['anjo']-------El Canjon, CA.
63958) stow------>['stow', 'canada', 'vancouver']-------Live at Gastown, Vancouver, Canada
65142) chester------>['chester', 'england', 'london']-------"Dorchester Hotel", London, England
65737) davie------>['san francisco', 'davie']-------Live "Davies Symphony Hall", San Francisco, CA
66025) radnor------>['radnor']-------Knighton, Radnorshire
66126) marka------>['germany', 'marka']-------Pfarrkirche Markau, Germany, August 24-28, 1992
66197) lede------>['anan', 'belgium', 'lede']-------Live "Banana Peel", Ruiselede, Belgium
66411) ghana------>['ghana']-------Live, Ferghana
66521) hale------>['hale', 'miami']-------Live "Swiss Chalet", Miami, FL.
67004) stockholm------>['stockholm']-------Stockholmm
67025) kunda------>['kunda', 'gambia']-------Suso family compound, Serekunda, The Gambia
67757) levis------>['levis', 'new york']-------Television broadcast, "Ed Sullivan Show", New York
67850) frankfurt------>['frankfurt']-------Frankfurter Jazzfestival
68176) osan------>['osan']-------Talosani, April 13 & 14, 1984
68177) napo------>['napo', 'leon']-------"Fort Napoleon", Seine-sur-Mer, June 28-30, 1985
68185) marseille------>['marseille']-------Marseilles, June 4 & 5, 1992
68494) franca------>['paris', 'franca', 'france']-------"Jazz Club Francais", Paris, France
68635) gera------>['illinois', 'berwyn', 'gera']-------Live "Fitzgerald's", Berwyn, Illinois, c. 1985
68665) heide------>['heide']-------Nordheide, July 24 & 31, August 22, September 3, 1982
68700) sahar------>['las vegas', 'sahar']-------Live "Sahara Hotel", Las Vegas, September 21 & 22, 1993
68852) pare------>['montreal', 'pare']-------Live "Chez Paree", Montreal
68923) helsingborg------>['helsingborg', 'helsingor']-------"Helsingborgs Konserthus", Helsingorg, June 27-29, 1990
68923) helsingor------>['helsingborg', 'helsingor']-------"Helsingborgs Konserthus", Helsingorg, June 27-29, 1990
69374) bron------>['copenhagen', 'bron']-------"Bronby Strand Kirke", Copenhagen, June 18-20, 1991
69407) brea------>['brea', 'minneapolis']-------Live "Harlem Breakfast Club", Minneapolis, MN
69538) hamburg------>['hamburg']-------Hamburgsund, August 14 & 15, 1987
70632) okha------>['england', 'okha']-------Cookham, England
71026) skane------>['germany', 'skane', 'illingen']-------Live "Franziskaner Concert Hall", Villingen, Germany
71483) sebu------>['sebu']-------Rosebud
71810) aichi------>['japan', 'nagoya', 'aichi']-------Concert "Aichibunkakode Hall", Nagoya, Japan
71849) anak------>['japan', 'naka', 'anak']-------Live "3361 Hall", Yamanakako, Japan
72069) giron------>['bordeaux', 'france', 'giron']-------Bordeaux Gironde, France
72170) langen------>['langen', 'bochum']-------Bochum-Langendreer
72365) highland------>['carmel', 'highland', 'california']-------Carmel Highlands, California
72595) carnegie------>['carnegie', 'new york', 'tual']-------Concert "From Spirituals to Swing","Carnegie Hall", New York
72996) amato------>['amato']-------Live "Taruho", Yamato
73027) trang------>['trang', 'kanagawa']-------Live "Strange Fruit", Kanagawa
73209) colonia------>['concord', 'colonia']-------"Colonial Inn", Concord, Mass., Oct 29 & November 12, 1991
74335) tire------>['tire', 'england']-------Live "Entire Club", England, 1968
74988) uster------>['holland', 'uster']-------Austerlitz, Holland

75250) arima------>['arima', 'como']-------Carimato, Como, c. 1983
75472) embu------>['embu']-------private recording, Luxemburg
75718) barda------>['salo', 'italy', 'barda', 'lombard', 'massa', 'vicenza']-------Live at "Jazz Club Di Massalombarda", Vicenza, Italy
75718) lombard------>['salo', 'italy', 'barda', 'lombard', 'massa', 'vicenza']-------Live at "Jazz Club Di Massalombarda", Vicenza, Italy
75718) massa------>['salo', 'italy', 'barda', 'lombard', 'massa', 'vicenza']-------Live at "Jazz Club Di Massalombarda", Vicenza, Italy
76262) passi------>['berlin', 'passi']-------Live at "Passionskirche", Berlin
76718) adra------>['berlin', 'adra']-------Munchen/Berlin/Madras, c. 1985 ?
77010) lido------>['lido', 'osun', 'stockholm']-------"S/S Blidosund", Stockholm
77010) osun------>['lido', 'osun', 'stockholm']-------"S/S Blidosund", Stockholm
77018) nara------>['edinburg', 'scotland', 'nara']-------Dragonara Hotel, Edinburgh, Scotland, August 20 & 21, 1987
77248) dara------>['japan', 'dara', 'tokyo', 'anda']-------"Mandara Kithijoji Coffee House", Tokyo, Japan
77701) wichita------>['wichita', 'itai']-------Wichitaitis, c. 1978
77701) itai------>['wichita', 'itai']-------Wichitaitis, c. 1978
77909) amora------>['meta', 'amora']-------Metamora, MI
78520) benton------>['benton', 'everett']-------Leverett, Mass. & Bentonia, Miss.
79072) woerden------>['woerden', 'verl']-------Woerdense Verlaat
79964) mbake------>['mbake', 'new orleans']-------WDSU Broadcast "Dixieland Jambake", New Orleans
80047) tenno------>['japan', 'tenno', 'osaka']-------Tennoji-Kaikam Hall, Osaka, Japan
80252) saalfeld------>['austria', 'saalfeld']-------Live "Festival Jazz Im Stall", Saalfelden, Austria
80732) arris------>['germany', 'arris', 'hamburg']-------Concert "Garrison Theatre", Hamburg, Germany
80946) harrison------>['harrison']-------Harrisonburg, VA, March 19 & 20, 1992
81096) lisbon------>['lisbon', 'bonn']-------Lisbonne, March 26 & 28, 1977
81096) bonn------>['lisbon', 'bonn']-------Lisbonne, March 26 & 28, 1977
81647) ahar------>['ahar', 'iona', 'arish']-------Maharishi International University
81672) save------>['italy', 'save', 'palermo']-------"San Saverio Auditorium", Palermo, Italy
82766) pest------>['pest']-------Pestalozza, February 22 & 23, 1983
83438) peto------>['lage', 'johannesburg', 'peto']-------"Castle Lager Jazz Festival", Johannesburg or Capetown
83836) bath------>['bath', 'toronto', 'hurst']-------"Bathhurst Street Theatre", Toronto, April 24 & 25, 1987
84044) iran------>['slovenia', 'iran', 'pala', 'rano']-------Concert "Tartini Palace", Pirano, Slovenia
84403) boden------>['austria', 'boden']-------Live "Spielboden Dornbrin", Austria
85032) enna------>['italy', 'chur', 'enna']-------Concert "St. Lorenzo Church", Chavenna, Italy
85066) alicia------>['chile', 'alicia', 'santiago']-------Santiago de Chile, Radio Cooperativa Vitalicia
85572) hami------>['hami', 'bermuda']-------Hamiliton, Bermuda
85640) kassel------>['germany', 'kassel']-------Oberkassel, Germany, early 1990's ?
86758) falcon------>['copenhagen', 'falcon']-------Live "Falconer Center", Copenhagen, March 13, 14 & 15, 1994
86968) moca------>['moca', 'toronto']-------Live "El Mocambo", Toronto, December 1-3, 1980
87091) goes------>['goes', 'new jersey']-------Ringoes, New Jersey
87144) herborn------>['herborn']-------Live "Sherborn Inn", Sherborn, MA
87404) david------>['david', 'charlotte']-------"Hodson Hall, Davidson College", Charlotte, N.C.
87415) moro------>['iona', 'moro']-------Gold Castle National Festival, Moroka-Jabavu
87998) seto------>['seto']-------AFRS "One Night Stand 1894", Seton Hall University, N.J.
88286) mino------>['north hollywood', 'palo', 'mino']-------Live "Palomino Club", North Hollywood, CA
88470) vannes------>['vannes', 'switzerland']-------Live "Cafe Calvado", Tavannes, Switzerland
90548) hollywood------>['hollywood', 'chesterfield']-------CBS Broadcast "Chesterfield Show",Hollywood
90687) mach------>['england', 'london', 'mach']-------The German Wehrmacht Hour Program #1, London, England
90723) kano------>['kano', 'new jersey']-------Live, Acquackanonck Studio, New Jersey, February-April, 1993
91156) peer------>['peer', 'chur', 'michigan']-------Calvary Bible Church, Lapeer, Michigan

91160) kula------>['kula', 'poznan']-------Live "Eskulap Club", Poznan Jazz Fair
91230) durant------>['italy', 'ragusa', 'durant']-------Live "Checco Durante's Public Theatre", Ragusa Ibla, Italy
91340) nago------>['nago', 'new york', 'galle']-------Live "Nonagon Art Gallery", New York
91444) soro------>['soro', 'hungary', 'hull', 'paks']-------Uj Hullam-Holsten sorozo, Paks, Hungary
91444) hull------>['soro', 'hungary', 'hull', 'paks']-------Uj Hullam-Holsten sorozo, Paks, Hungary
91796) eastern------>['eastern', 'boston', 'northeast']-------Live "Northeastern University", Boston
91850) shan------>['shan']-------Live, Salishan, PA
92185) oros------>['oros', 'spain']-------Concert "Plaza De Toros", Spain
92678) dura------>['dura']-------Muldura Jazz Jamboree, Riverboat Trip
92808) ennis------>['germany', 'ennis', 'hamburg']-------Live "Dennis' Swing Club", Hamburg, Germany
93403) eket------>['rhode island', 'eket']-------Pawtueket, Rhode Island, c. 1990
93580) asha------>['asha', 'tokyo']-------Live "The Club Ginbasha", Tokyo
94199) prague------>['prague']-------Sprague Hall, Yale University, June 7, 1979 & June 8, 1980
94292) stafford------>['aldridge', 'stafford', 'fords']-------Aldridge, Staffordshire
94371) ostermalm------>['ostermalm', 'stockholm']-------"Ostermalmskallaren", Stockholm
94639) ogre------>['chicago', 'illinois', 'ogre']-------Live "Progressive Arts Center", Chicago, Illinois
95331) balti------>['germany', 'balti', 'kiel']-------Jazz Baltica '92 Festival, Opera, Kiel, Germany
95468) mibu------>['mibu', 'buhl', 'switzerland', 'zurich']-------Live "Gymnasium Ramibuhl", Zurich, Switzerland
95468) buhl------>['mibu', 'buhl', 'switzerland', 'zurich']-------Live "Gymnasium Ramibuhl", Zurich, Switzerland
95768) minbu------>['aomori', 'minbu']-------Concert "Aomori Shiminbunka Hall", Aomori
96130) stuttgart------>['halle', 'stuttgart']-------Live "Beethovensaal der Stuttgarter Liederhalle", Suttgart
96257) terme------>['terme', 'vancouver']-------Live "Intermedia", Vancouver
96304) kusa------>['kusa', 'japan', 'saku', 'tokyo']-------Live "Asakusa Theatre", Tokyo, Japan
96304) saku------>['kusa', 'japan', 'saku', 'tokyo']-------Live "Asakusa Theatre", Tokyo, Japan
96523) gedo------>['gedo', 'new orleans']-------Live "Stagedoor Canteen", New Orleans, LA
96833) butte------>['butte', 'welling', 'hamburg']-------Hamburg-Wellingsbuttel, September 12 & 13, 1984
96833) welling------>['butte', 'welling', 'hamburg']-------Hamburg-Wellingsbuttel, September 12 & 13, 1984
96894) onex------>['geneva', 'onex']-------Live "Right Side Jazz Club", Grand-Sacconex/Geneva
98075) cambe------>['france', 'cambe']-------Cambes, France
99878) waltham------>['waltham', 'stow']-------Live "The Tower Hotel", Walthamstow
100463) vastervik------>['vastervik']-------Vastervikvaren
101400) arak------>['arak', 'athens', 'george']-------Live "George Barakos Jazz Club", Athens
101900) bender------>['san francisco', 'bender']-------Concert "Beanbender's", San Francisco, CA
102245) soest------>['soest', 'brazil']-------"NossoEstudio", Sao Paul, Brazil
102514) jona------>['boston', 'jona']-------Live "Jonathan Swift's", Boston
102621) sigli------>['sigli', 'mila', 'basi']-------Live, Basiglio (Milan)
102834) tela------>['tela']-------Live "De Schuur", Bottelaere
103090) heves------>['nagykanizsa', 'heves', 'tura']-------Hevesi Sandor Cultural Center (*), Nagykanizsa
103481) togo------>['togo', 'pully', 'switzerland']-------Live "l'Octogone", Pully, Switzerland, Sept 29 & 30, 1988
103965) debar------>['holland', 'arak', 'debar', 'zutphen']-------Live, Debarak, Zutphen, Holland
104375) blaj------>['blaj']-------Ljublajana Jazz Festival, June 3-6, 1971
104509) penha------>['penha', 'denmark']-------Copenhagan, Denmark, July/August, 1960
105191) newberg------>['newberg']-------Eli Newberger's residence
105359) baro------>['baro', 'new york', 'aron']-------Live "Baron's", New York
107098) unna------>['unna']-------Sunna, Sweden
107526) lincoln------>['england', 'boston', 'lincoln']-------Boston, Lincolnshire, England
109148) metu------>['metu', 'massachusetts']-------Metuhen, Massachusetts
110285) ewell------>['caldwell', 'ewell', 'morganton']-------Gamewell or Morganton, Caldwell County, N.C., summer 1956

110676) alton------>['alton']-------Walton
111360) reus------>['germany', 'munster', 'reus', 'sens']-------Live "Preussenstadion", Intl Jazz Festival, Munster, Germany
111587) halland------>['halmstad', 'halland']-------Live "Hotel Hallandia", Halmstad, Sweden
111602) yoichi------>['japan', 'yoichi', 'osaka']-------Live "Ryoichi Kawai's Mahogany Hall", Osaka, Japan
111990) lalago------>['italy', 'lalago']-------Live, Villalago, Italy
112313) perm------>['perm', 'asse']-------Opperman Hall, F.S.U., Tallahasse, FL, c. 1992
112655) atar------>['atar', 'new york']-------Avatar, New York, July 30, 31 & September 8, 1996
112831) rota------>['germany', 'hanover', 'rota']-------Live "Rotation Club", Hanover, Germany
112886) klin------>['klin', 'switzerland', 'zurich']-------Live "Jecklin", Zurich, Switzerland
113479) sava------>['rome', 'sava']-------Live, Piano Bar del Savaoy Hotel, Rome
114159) emet------>['emet', 'hungary']-------3rd Int'l Unicum-Bohem Ragtime-Jazz Meet., Keskemet, Hungary
114232) klang------>['germany', 'klang']-------Klangstudio, Leyh, Germany
115573) orel------>['orel']-------Studio Lorelei, June & August 1992
116236) marl------>['marl', 'germany', 'torgau']-------St. Marlen Stadtkirche, Torgau, Germany April 13 & 14, 1997
117109) beni------>['beni', 'prague', 'pala']-------Live "Jazzove Velebeni", Palac Kultury, Prague
117389) neka------>['neka']-------Inekas Studios, Sweden, Spring & Autumn, 1989
118427) rome------>['leeuwarden', 'rome']-------Theater Romein, Leeuwarden, June 5 & 6, 1994
118641) sandi------>['berkeley', 'sandi']-------Sandisfield, MA & Berkeley, CA
119051) olpe------>['germany', 'olpe', 'rath']-------Wolperath, Germany
119114) haren------>['haren', 'warsaw']-------Live "Harenda Club", Warsaw
120514) asaka------>['asaka']-------Live "Toshi Center Hall", Akasaka
121007) ambon------>['ambon', 'el cerrito']-------Live "Hambone Kelly's", El Cerrito, CA, during 1949
121135) lapa------>['lapa', 'mexico']-------Live "Sala Chica Del Teatro Del Estado", Xalapa, Mexico
121137) mula------>['caracas', 'venezuela', 'galle', 'mula']-------Live "Casa De Romula Gallegos", Caracas, Venezuela
121155) lamu------>['lamu']-------Kalamunda
121530) herten------>['holland', 'herten']-------Live "De Hertenkamp", Laren, Holland
121962) anbu------>['bury', 'brighton', 'anbu']-------Live "Brighton Jazz Club", Hanbury Arms, Brighton
122345) chorzow------>['chorzow']-------Teatr Rozrywki, Chorzowie
122644) istok------>['istok']-------Concert, "Kelly College", Tavistok
122788) mamou------>['mamou', 'morocco']-------La Mamounia Hotel, Marrakech, Morocco
124876) bama------>['bama', 'galle', 'leigh', 'birmingham']-------Live "Leigh Gallery", Birmingham, Alambama
125041) russia------>['russia', 'san francisco']-------Russian Hill, San Francisco, CA
125106) atwater------>['atwater', 'portland']-------Live "Atwaters", Portland, OR
126734) nyon------>['nyon']-------Live "Cathedral of St. John the Divine" & the Grand Canyon
126989) noto------>['norway', 'noto']-------Live, The Notodden Blues Festival, Norway, Aug 24 & 25, 1991
128033) alma------>['senegal', 'dakar', 'alma']-------Live "Club Taski Les Almadies", Dakar, Senegal
128089) kadi------>['kadi', 'istanbul']-------Kadikoy, Istanbul, summer 1998
128588) maba------>['maba', 'tokyo']-------Live "Todai Komaba", Tokyo during "Noise in X'es"
128948) kaka------>['kaka', 'netherlands']-------Live "Jazzcafe De Kakatoe", Den Bosch, The Netherlands
129407) morbi------>['morbi', 'san francisco']-------Morbius Studio, San Francisco, CA ?
129531) vence------>['paris', 'salo', 'vence']-------Paris, May 1995 & Salon De Provence, September 1995
129882) telde------>['telde', 'berlin']-------Berlin Jazz Festival 71, Teldec Studio, Berlin
129910) leer------>['leer', 'troy']-------Live "Renseleer Polytechnic Institute", Troy, NY
130323) halden------>['halden']-------Remshalden
130349) albi------>['albi', 'sydney']-------Albion Hotel, Sydney, April 18 & 25, 1999
130440) saki------>['saki']-------Club Misaki
130502) bulgaria------>['bulgaria', 'iona']-------Bulgarian National Radio
130505) oyan------>['bulgaria', 'oyan']-------Boyana studio, Bulgaria

130558) norton------>['norton']-------Chipping Nortons, December 8 & 9, 1994
130714) coram------>['rama', 'paris', 'coram']-------Europe 1 broadcast "Musicorama Concert", Salle Pleyel, Paris
130779) estonia------>['levis', 'estonia']-------Live, Estonian television
130970) ystad------>['ystad']-------Leystad, Schauspielhaus, 2000s
131163) assaba------>['assaba', 'lido']-------Concert, Iseo al Lido di Sassabanek, July 21-31, 1999
131405) asan------>['asan']-------Mt. Pleasant, PA, April & May 1998
131498) drama------>['mati', 'novokuznetsk', 'drama']-------Live "Novokuznetsk Dramatic Theatre", April 20-23, 1995
131520) reno------>['reno', 'essex']-------Live "Renouf's Hotel", Essex
131599) ovar------>['southern', 'california', 'ovar']-------Live, Bovard Auditorium, University of Southern California
131723) southwest------>['southwest', 'louisiana', 'western']-------University of Southwestern Louisiana
131723) western------>['southwest', 'louisiana', 'western']-------University of Southwestern Louisiana
131795) solin------>['solin']-------Pasolini
131831) wevelgem------>['wevelgem']-------Live "Sporthal", Zwevelgem
131909) lenbe------>['allentown', 'lenbe']-------Muhlenberg College Arts Center Recital Hall, Allentown, PA
131910) kaya------>['japan', 'kaya']-------The Egg Farm, Fukaya, Japan
132147) bela------>['bela', 'bergamo']-------Bergamo dal Paolo Belandi
132206) atlanta------>['atlanta']-------lAtlanta, GA, July 14, 15 & 16, 1998
133307) whitney------>['whitney']-------Whitneyville, CT
133485) egypt------>['new orleans', 'egypt']-------The Egyptian Room, New Orleans, LA
133940) melle------>['melle']-------Mellery
133981) along------>['bern', 'salo', 'along', 'stockholm']-------Live "Berns Salonger", Stockholm, February 19 & 20, 1976
134932) ordu------>['ordu']-------Ordulph Arms Hotel, Tavistock, Devon
135096) altai------>['altai', 'salt lake city', 'salta']-------Saltair Ballroom, Salt Lake City, May 30-June 8, 1957
135096) salta------>['altai', 'salt lake city', 'salta']-------Saltair Ballroom, Salt Lake City, May 30-June 8, 1957
136336) imus------>['imus']-------Vimus
136427) herve------>['herve']-------Herveld
136804) derby------>['derby']-------Dove Holes, Derbyshire
136957) kari------>['kari', 'denmark']-------Karise, Denmark, September 22-24 & October 28-29, 1991
137759) alot------>['alot', 'budapest', 'lota', 'palo']-------Benczur Palota, Budapest
137759) lota------>['alot', 'budapest', 'lota', 'palo']-------Benczur Palota, Budapest
137874) haiti------>['moscow', 'haiti']-------Live "Baltrushaitis House", Moscow
137965) hondo------>['germany', 'hondo']-------Schondorf, Germany, May 14 & 15, 2001
138142) gero------>['gero', 'austria']-------Monastery of Sankt Gerold, Austria
138162) slawi------>['netherlands', 'slawi']-------Metslawier, Netherlands, June 27 & 28, 1996
138478) lorca------>['lorca', 'palma']-------Palma de Mallorca
139103) mara------>['groningen', 'mara', 'rath']-------Live Jazzfestival "Jazz Marathon", Groningen
139553) wedel------>['wedel']-------Langwedel, November & December 1998
139855) amos------>['adam', 'amos']-------Adamos studios, unidentified city, CA
140586) lynn------>['vermont', 'lynn', 'burlington']-------Live "The Flynn Theatre", Burlington, Vermont
140656) malmo------>['malmo']-------Malmoe, Sweden, January 15-18, 1999
140774) hereford------>['fords', 'hereford']-------Ross-On-Wye, Herefordshire
140780) aargau------>['aarau', 'aargau']-------Live "Aargauer Kunsthaus", Aarau
141478) washington------>['washington']-------radio broadcast, "President's Birthday Ball",Washington D.C.
141497) southland------>['southland', 'boston']-------NBC radio broadcast, "Southlands Cafe", Boston, MA
141920) pula------>['paris', 'iona', 'pula', 'france', 'pala']-------"Theatre National Populaire, Palais Chaillot", Paris, France
141921) alhambra------>['paris', 'france', 'alhambra']-------"Theatre De L'Alhambra", Paris, France
142501) gaeta------>['gaeta', 'pueblo']-------Private recording "Gaetano's", Pueblo, CO, summer 1966
142595) coro------>['italy', 'ondo', 'coro']-------Locorotondo, Italy, September 1985
142607) lima------>['lima', 'italy', 'shali', 'senigallia']-------Live "Shalimar Club", Senigallia, Italy
142607) shali------>['lima', 'italy', 'shali', 'senigallia']-------Live "Shalimar Club", Senigallia, Italy
142610) cento------>['italy', 'margherita', 'nema', 'cine', 'cento']-------Private recording "Cinema Margherita", Tarcento, Italy
142810) donna------>['donna', 'rome']-------Film soundtrack "Big Deal on Madonna St.", Rome, prob. 1960

143322) bati------>['bati', 'switzerland']-------L'Abbatiale De Payerne, Switzerland, November 12-16, 1997
143516) ermont------>['ermont', 'rio de janeiro']-------Rio de Janeiro & Piermont, NY, January & February 2002
144464) reni------>['netherlands', 'reni', 'nijmegen']-------Live "De Vereniging", Nijmegen, The Netherlands
144768) fier------>['fier', 'paris']-------Live "Montgolfier Club", Sofitel Hotel, Paris
144823) aland------>['aland', 'mala', 'denmark']-------Smalanddshavet, Karrebaeksminde, Denmark
144823) mala------>['aland', 'mala', 'denmark']-------Smalanddshavet, Karrebaeksminde, Denmark
145211) lida------>['lida']-------Live "Bilidal's Kyrka", Gothenburg
145462) troms------>['uran', 'troms', 'stockholm']-------Live "Restaurant Stromsborg", Stockholm, Sweden
145486) sevan------>['norway', 'sevan']-------Live "Hotel Vossevangen", Voss, Norway
146080) chad------>['chad', 'eugene']-------Eugene Chadbourne's backyard
146114) gilbert------>['gilbert']-------Live "Gilberto's", Cucamonga, CA
147069) apodi------>['slovenia', 'apodi']-------Capodistria, Slovenia, December, 1994-February, 1995
147177) brecht------>['brecht']-------Albrecht, January 10-13, 1998
147375) mary------>['mary']-------Live, Rosemary Clooney Music Festival, Maysville, KY, c.2001
147782) jasper------>['jasper']-------Jaspers Brush, NSW
148301) born------>['born']-------Sandborn, NY, November 11 & December 23, 1998
148423) sari------>['mila', 'sari']-------Milan, July 23-25, 2001 & Sarin, July 6, 2002
148499) ossett------>['london', 'ossett']-------Concert "Dolly Fossett's", London
148500) douz------>['geneva', 'douz', 'switzerland']-------Cafe Douze, Geneva, Switzerland
148922) hilden------>['hilden']-------Hildenborough
149275) lehi------>['lehi']-------Lehigh University
149364) sano------>['mons', 'italy', 'sano']-------Monsano, Italy
149626) crema------>['crema']-------Live, Trescore Cremasco
149999) toba------>['toba', 'ware', 'asheville']-------Camel Caravan broadcast "Tobacco Warehouse", Asheville, N.C.
150221) newark------>['newark', 'terrace']-------AFRS Magic Carpet #199A,"Terrace Room",Newark,N.J. Dec. 1945
150221) terrace------>['newark', 'terrace']-------AFRS Magic Carpet #199A,"Terrace Room",Newark,N.J. Dec. 1945
150341) husi------>['husi', 'new york']-------Broadcast, "Ted Husing Show", New York
150755) ancash------>['ancash']-------Lancashire, February 12 & 13, 2002
150818) akot------>['akot', 'kota']-------Live "Dakota Club", St. Paul, MN, October 25 & 26, 2002
150861) isawa------>['isawa']-------Kobuchisawa, February 26 & 27, 2002
150920) gela------>['netherlands', 'gela', 'haarlem']-------Concert, Haarlemse Jazz Club "De Egelantier", Netherlands
150925) nnewi------>['netherlands', 'nnewi', 'eindhoven']-------Concert "Zonnewijzer", Eindhoven, Netherlands
151698) marion------>['marion']-------Live, Marions-Nous, December 18-20, 2001
152516) forst------>['forst']-------Throwley Forstal
153376) handa------>['shan', 'handa', 'brooklyn']-------Brooklyn, NY, February & Shandaken, NY, March 2002
153630) baden------>['berlin', 'baden']-------Live "Badenschen Hof", Berlin, May 27-29, 1992
153755) lomme------>['norway', 'meda', 'lomme']-------Lommedalen, Norway, February 1-3, 2001
CPU times: user 1h 30min 27s, sys: 48min 15s, total: 2h 18min 42s
Wall time: 1h 9min 41s

In [0]:
i =23546
print(i,vagfreelist[i],valuesall[i])

23546 ['los angeles'] Los Angeles, 1947

In [0]:
print(vagfreelist)
print(len(uniquelist1))
print(uniquelist1)

In [0]:
# for i in range(0,1000):
#   print(vagfreelist[i])

In [0]:
count0 = 0
count1 = 0
count2 = 0
count3 = 0
count4 = 0
count5 = 0
count6 = 0
count7 = 0
maxlen = 0
for i,rowlist in enumerate(vagfreelist):
  if len(rowlist) ==0:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count0=count0+1
  if len(rowlist) ==1:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count1=count1+1
  if len(rowlist) ==2:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count2=count2+1
  if len(rowlist) ==3:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count3=count3+1
  if len(rowlist) ==4:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count4=count4+1
  if len(rowlist) ==5:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count5=count5+1
  if len(rowlist) ==6:
    print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count6=count6+1
  if len(rowlist) ==7:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count7=count7+1
  if len(rowlist) > maxlen:
    maxlen = len(rowlist)
print("count0",count0)
print("count1",count1)
print("count2",count2)
print("count3",count3)
print("count4",count4)
print("count5",count5)
print("count6",count6)
print("count7",count7)
print("maxlen", maxlen)

112557['russia', 'craiova', 'moscow', 'riga', 'romania', 'latvia']-------------------Concerts, Moscow, Russia; Riga, Latvia; Craiova, Romania
count0 16604
count1 119366
count2 17001
count3 878
count4 85
count5 26
count6 1
count7 0
maxlen 6

In [0]:
# nocommonlist = []

# commonword4 = ["university","create","center","centre","holidays","holiday","same","summit","sunset","nord","orange","liberal","metro","prospect","elizabeth","papa","golden","mobile","sale","than","longview","best","state college","college"]

# for i,rowlist in enumerate(vagfreelist):
#   temprow = []
#   for ele1 in rowlist:
#     if ele1 != 'university' and ele1 != 'create' and ele1 != 'center' and ele1 != 'centre':
#       temprow.append(ele1)
#   nocommonlist.append(temprow)
  
# print(len(nocommonlist))

In [0]:
# %%time
# #remove country
# for i,ele in enumerate(uniquelist1):
#   for ele2 in coulist:
#     ele2 = str(ele2).lower().strip()
#     if ele1 in ele2:
#       print(ele1,ele2)

In [0]:
%%time
#remove country

nocoulist = []
onlycoulist = []
for i,rowlist in enumerate(vagfreelist):
  temprowno = []
  temprowonly = []
  flag2 = 0
  for ele1 in rowlist:
#     ele1 = str(ele1).lower
    flag2 = 0
    for ele2 in coulist:
      ele2 = str(ele2).lower().strip()
      if ele1 in ele2:
        flag2 = 1
        temprowonly.append(ele1)
        
    if flag2 == 0 and ele1 =='england':
      temprowonly.append(ele1)
      
    if flag2 == 0 and ele1 !='england':
      temprowno.append(ele1)
  nocoulist.append(temprowno)
  onlycoulist.append(temprowonly)
  

print(len(nocoulist))
print(len(onlycoulist))

153961
153961
CPU times: user 19.7 s, sys: 3 ms, total: 19.7 s
Wall time: 19.7 s

In [0]:
#onlycoulist show
count0 = 0
count1 = 0
count2 = 0
count3 = 0
count4 = 0
count5 = 0
count6 = 0
count7 = 0
maxlen = 0
for i,rowlist in enumerate(onlycoulist):
  if len(rowlist) ==0:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count0=count0+1
  if len(rowlist) ==1:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count1=count1+1
  if len(rowlist) ==2:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count2=count2+1
  if len(rowlist) ==3:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count3=count3+1
  if len(rowlist) ==4:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count4=count4+1
  if len(rowlist) ==5:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count5=count5+1
  if len(rowlist) ==6:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count6=count6+1
  if len(rowlist) ==7:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count7=count7+1
  if len(rowlist) > maxlen:
    maxlen = len(rowlist)
#     print(str(i) + ")    "+str(rowlist) +"-------------------"+ valuesall[i])
    
print("count0",count0)
print("count1",count1)
print("count2",count2)
print("count3",count3)
print("count4",count4)
print("count5",count5)
print("count6",count6)
print("count7",count7)
print("maxlen", maxlen)

uniquecountry = []
for i,rowlist in enumerate(onlycoulist):
  for ele1 in rowlist:
    if ele1 not in uniquecountry:
      uniquecountry.append(ele1)

print(len(uniquecountry))

count0 139823
count1 13756
count2 367
count3 14
count4 0
count5 1
count6 0
count7 0
maxlen 5
122

In [0]:
#nocoulist show
count0 = 0
count1 = 0
count2 = 0
count3 = 0
count4 = 0
count5 = 0
count6 = 0
count7 = 0
maxlen = 0
for i,rowlist in enumerate(nocoulist):
  if len(rowlist) ==0:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count0=count0+1
  if len(rowlist) ==1:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count1=count1+1
  if len(rowlist) ==2:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count2=count2+1
  if len(rowlist) ==3:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count3=count3+1
  if len(rowlist) ==4:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count4=count4+1
  if len(rowlist) ==5:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count5=count5+1
  if len(rowlist) ==6:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count6=count6+1
  if len(rowlist) ==7:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count7=count7+1
  if len(rowlist) > maxlen:
    maxlen = len(rowlist)
#     print(str(i) + ")    " + str(maxlen)+"------"+str(rowlist) +"-------------------"+ str(valuesall[i]))
print("count0",count0)
print("count1",count1)
print("count2",count2)
print("count3",count3)
print("count4",count4)
print("count5",count5)
print("count6",count6)
print("count7",count7)
print("maxlen", maxlen)

count0 20125
count1 126076
count2 7317
count3 373
count4 66
count5 4
count6 0
count7 0
maxlen 5

In [0]:
# finallist2 #keeping few city even not matched
# impnolist = [2303,2980,12213,16866,19959,23661,27217,30673,33388,41923,50037,56470,60473,74250,108843,128467,129008,129225,131468,133676,133948,137265,145275,152741,153082]
impnamelist= ['los angeles','Los Angeles', 'montreal', 'neumunster', 'gjovik', 'arhus', 'geneve', 'torshavn', 'kungalv', 'dusseldorf', 'sao paulo', 'montlucon', 'liege', 'lulea', 'pitea', 'goteborg', 'wahiawa', 'gdansk', 'nurnberg', 'alesund', 'san luis potosi', 'enkoping', 'kihei', 'gyor', 'malmo', 'levis', 'saarbrucken', 'holbaek']
finallist2 = []
uniquelist3 = []
for i,rowlist in enumerate(nocoulist):
  temprow = []
  for ele1 in rowlist:
    if len(rowlist) < 2:
       temprow.append(ele1)
    else:
      flag2 = 0
      for ele2 in subcoulist:
        ele2 = str(ele2).lower().strip()
        if ele1 in ele2:
          flag2 = 1
          temprow.append(ele1)
          break
      flag3 = 0
      if flag2 == 0:
        for ele3 in namelist:
          ele3 = str(ele3).lower().strip()
          if ele1 in ele3:
            flag3 = 1
            temprow.append(ele1)
            break
      if flag3 == 0 and flag2 ==0:
        flag4 = 0
        if ele1 in impnamelist:
          temprow.append(ele1)
          flag4 = 1
      if flag2 == 0 and flag3 ==0 and flag4 ==0:
        if ele1 not in uniquelist3 and ("NA" not in ele1):
          uniquelist3.append(ele1)
          print(str(i) + ")    "+ str(ele1) +"<====="+ str(rowlist) +"------------------->"+ str(valuesall[i]))
  
  finallist2.append(temprow)
print(len(finallist2))

3836)    vanlose<=====['copenhagen', 'vanlose']------------------->Vanlose Bio, Copenhagen
3942)    panorama<=====['kortrijk', 'panorama']------------------->Jazz Panorama, Stadsschouwburg, Kortrijk
9161)    claudio<=====['montreal', 'claudio']------------------->Live "Claudio's", Montreal, December 16 & 17, 1991
29934)    perez<=====['new orleans', 'perez']------------------->Live "Perez Club", New Orleans, LA
37316)    creteil<=====['paris', 'creteil']------------------->Creteil, Paris
42768)    vastmanland<=====['vastmanland', 'uppsala']------------------->Live "Vastmanland-Dala Nation", Uppsala, Sweden
64008)    chatelet<=====['paris', 'chatelet']------------------->"Theatre du Chatelet", Paris, France
65056)    hurth<=====['aachen', 'hurth']------------------->Live, "Burgerhaus Hurth", Aachen, Germany
107709)    heliopolis<=====['heliopolis', 'cairo']------------------->Heliopolis, Cairo, Egypt
128613)    hofu<=====['hofu', 'yamaguchi']------------------->Live "Cafe Amores", Hofu-Shi, Yamaguchi
130421)    jonquiere<=====['jonquiere', 'quebec']------------------->Jonquiere, Quebec
131469)    lidingo<=====['stockholm', 'lidingo']-------------------> Live "Lidingo Jazzclub", Stockholm
134665)    premia de mar<=====['premia de mar', 'barcelona']------------------->Premia de Mar, Barcelona
140810)    belem<=====['lisbon', 'belem']------------------->Centro Cultural de Belem, Lisbon, December 12, 13 & 14, 1993
153961

In [0]:
# print(impnamelist)

In [0]:
print(len(finallist2))
print(len(uniquelist3))

153961
14

In [0]:
print(finallist2[140810])

['lisbon']

In [0]:
finallist3 = [] 

for i,rowlist in enumerate(finallist2):
  temprow = []
  for ele1 in rowlist:
    if "na-" not in ele1:
      temprow.append(ele1)
#     else:
#       print(str(i) + ")    "+str(rowlist) +"-------------------"+ str(valuesall[i]))
  finallist3.append(temprow)
print(len(finallist3))

153961

In [0]:
#finallist2 show
count0 = 0
count1 = 0
count2 = 0
count3 = 0
count4 = 0
count5 = 0
count6 = 0
count7 = 0
maxlen = 0


# commonword4 = ["holidays","holiday","same","summit","sunset","nord","orange","liberal","metro","prospect","elizabeth","papa","golden","mobile","sale","than","longview","best","state college","college"]

# uniquerow4 = []
for i,rowlist in enumerate(finallist3):
  if len(rowlist) ==0:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count0=count0+1
  if len(rowlist) ==1:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count1=count1+1
  if len(rowlist) ==2:
#     print(str(i) + ")    " + str(rowlist) +"-------------------"+ str(valuesall[i]))
    count2=count2+1
  if len(rowlist) ==3:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count3=count3+1
  if len(rowlist) ==4:
#     print(str(i) + ")    "+str(rowlist) +"-------------------"+ str(valuesall[i]))
    count4=count4+1
  if len(rowlist) ==5:
#     print(str(i) + ")    " + str(rowlist) +"-------------------"+ str(valuesall[i]))
    count5=count5+1
  if len(rowlist) ==6:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count6=count6+1
  if len(rowlist) ==7:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count7=count7+1
  if len(rowlist) > maxlen:
    maxlen = len(rowlist)
#     print(str(i) + ")    " + str(maxlen)+"------"+str(rowlist) +"-------------------"+ str(valuesall[i]))
print("count0",count0)
print("count1",count1)
print("count2",count2)
print("count3",count3)
print("count4",count4)
print("count5",count5)
print("count6",count6)
print("count7",count7)
print("maxlen", maxlen)

# print(len(uniquerow4))

count0 22757
count1 123471
count2 7290
count3 373
count4 66
count5 4
count6 0
count7 0
maxlen 5

In [0]:
# #finallist2 show
# count0 = 0
# count1 = 0
# count2 = 0
# count3 = 0
# count4 = 0
# count5 = 0
# count6 = 0
# count7 = 0
# maxlen = 0


# commonword4 = ["holidays","holiday","same","summit","sunset","nord","orange","liberal","metro","prospect","elizabeth","papa","golden","mobile","sale","than","longview","best","state college","college"]

# uniquerow4 = []
# for i,rowlist in enumerate(finallist2):
#   if len(rowlist) ==0:
# #     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
#     count0=count0+1
#   if len(rowlist) ==1:
# #     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
#     count1=count1+1
#   if len(rowlist) ==2 and "&" not in str(valuesall[i]) and " and" not in str(valuesall[i]):
#     flag1 = 0
#     for ele1 in rowlist:
#       if ele1 in commonword4:
#         flag1 = 1
#     if flag1 == 0:
#       count2=count2+1
#       if rowlist not in uniquerow4:
#         uniquerow4.append(rowlist)
#         print(str(i) + ")    " + str(rowlist) +"-------------------"+ str(valuesall[i]))
    
#   if len(rowlist) ==3:
# #     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
#     count3=count3+1
#   if len(rowlist) ==4:
# #     print(str(i) + ")    " + str(maxlen)+"------"+str(rowlist) +"-------------------"+ str(valuesall[i]))
#     count4=count4+1
#   if len(rowlist) ==5:
# #     print(str(i) + ")    " + str(rowlist) +"-------------------"+ str(valuesall[i]))
#     count5=count5+1
#   if len(rowlist) ==6:
# #     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
#     count6=count6+1
#   if len(rowlist) ==7:
# #     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
#     count7=count7+1
#   if len(rowlist) > maxlen:
#     maxlen = len(rowlist)
# #     print(str(i) + ")    " + str(maxlen)+"------"+str(rowlist) +"-------------------"+ str(valuesall[i]))
# print("count0",count0)
# print("count1",count1)
# print("count2",count2)
# print("count3",count3)
# print("count4",count4)
# print("count5",count5)
# print("count6",count6)
# print("count7",count7)
# print("maxlen", maxlen)

# print(len(uniquerow4))

In [0]:
# 89601 empty
#80136 sub + country
#81266 in city
#75933

In [0]:
# count1 = 0
# count2 = 0

# uniquerowand = []
# uniquerowno = []

# for i,rowlist in enumerate(finallist3):
#   if len(rowlist) >=2:
#     if "&" in str(valuesall[i]) or " and" in str(valuesall[i]):
#       count1+=1
#       if rowlist not in uniquerowand:
#         uniquerowand.append(rowlist)
#         print(str(i) + ")    " + str(rowlist) +"-------------------"+ str(valuesall[i]))
#     else:
#       count2+=1
#       if rowlist not in uniquerowno:
#         uniquerowno.append(rowlist)
# #         print(str(i) + ")    " + str(rowlist) +"-------------------"+ str(valuesall[i]))

# print(len(uniquerowand))
# print(len(uniquerowno))

In [0]:
# finallist4 = []

# # count1 = 0
# # count2 = 0

# uniquerowand2 = []
# uniquerowno2 = []

# for i,rowlist in enumerate(finallist3):
#   temprow = []
#   if len(rowlist) >=2:
#     for ele1 in rowlist:
#       flag1 = 0
#       if ele1 in impnamelist:
#         flag1 = 1
#         temprow.append(ele1)
#       if flag1 ==0:
#         flag2 = 0
#         for ele2 in subcoulist:
#           ele2 = str(ele2).lower().strip()
#           if ele1 in ele2:
#             flag2 = 1
#             temprow.append(ele1)
#             break
#         if flag2 ==0:
# #           if "&" in str(valuesall[i]) or " and" in str(valuesall[i]):
# #             if ele1 not in uniquerowand2:
# #               uniquerowand2.append(ele1)
# #               print(str(i) + ")    " + str(ele1) + str(rowlist) +"-------------------"+ str(valuesall[i]))
# #           else:
#           if ele1 not in uniquerowno2:
#             uniquerowno2.append(ele1)
#             print(str(i) + ")    "  + str(ele1) + "    "+ str(rowlist) +"-------------------"+ str(valuesall[i]))
        
    
    
# print(len(uniquerowand2))
# print(len(uniquerowno2))

# # "san francisco","falun","hollywood",melbourne,st. Louis,arnhem,

47)    laporte    ['colorado', 'laporte']-------------------"Eye in the Sky", Laporte, Colorado, May 24 & 25, 1996
51)    evanston    ['illinois', 'evanston']-------------------Evanston, Illinois, c. 1983
120)    denver    ['colorado', 'denver']-------------------Denver, Colorado
132)    st. louis    ['st. louis', 'missouri']-------------------St. Louis, Missouri
204)    waterloo    ['iowa', 'waterloo']-------------------Waterloo, Iowa
320)    minneapolis    ['minnesota', 'minneapolis']-------------------Minneapolis, Minnesota
331)    des moines    ['iowa', 'des moines']-------------------Des Moines, Iowa
337)    arnhem    ['luxor', 'arnhem']-------------------Luxor Theatre, Arnhem
456)    miami    ['florida', 'miami']-------------------Miami, Florida
458)    glenview    ['glenview', 'illinois']-------------------Glenview, Illinois
471)    hollywood    ['los angeles', 'hollywood']-------------------Los Angeles & Hollywood, CA
518)    chicago    ['chicago', 'illinois']-------------------Chicago, Illinois, c. 1954
520)    newport    ['rhode island', 'newport']-------------------Newport Jazz Festival, Newport, Rhode Island
557)    asahi    ['asahi', 'tokyo']-------------------Live "Asahi Seimei Hall", Tokyo
733)    miami beach    ['florida', 'miami beach']-------------------"Municipal Auditorium", Miami Beach, Florida
874)    seattle    ['washington', 'seattle']-------------------Seattle, Washington, May 23 & June 13, 1981
892)    san francisco    ['los angeles', 'san francisco']-------------------Los Angeles or San Francisco
915)    keystone    ['keystone', 'san francisco']-------------------Live "Keystone Korner", San Francisco, CA
1013)    mitchell    ['mitchell', 'stockholm']-------------------Red Mitchell's apartment, Stockholm
1020)    falun    ['falun', 'vancouver']-------------------Vancouver, B.C., October 1982 & Falun, Sweden, February 1983
1020)    vancouver    ['falun', 'vancouver']-------------------Vancouver, B.C., October 1982 & Falun, Sweden, February 1983
1219)    new orleans    ['santiago', 'new orleans']-------------------Burnell Santiago's Home, New Orleans, LA
1261)    cedar falls    ['iowa', 'cedar falls']-------------------Cedar Falls, Iowa, May 12 & 13, 1986
1300)    epping    ['new hampshire', 'epping']-------------------Epping, New Hampshire
1347)    toronto    ['hollywood', 'toronto']-------------------Toronto, Canada & Hollywood, CA, c. 1975
1422)    warren    ['warren', 'michigan']-------------------Warren, Michigan
1427)    decatur    ['decatur', 'illinois']-------------------"Holiday Inn", Decatur, Illinois, January 30 & 31, 1976
1431)    bradenton    ['florida', 'bradenton']-------------------Bradenton, Florida, April 24 & 25, 1995
1516)    omaha    ['nebraska', 'omaha']-------------------Broadcast "Camel Caravan", Omaha, Nebraska
1538)    portland    ['oregon', 'portland']-------------------Live dance session, Portland, Oregon
1554)    westminster    ['westminster', 'colorado']-------------------Westminster, Golden & Basels, Colorado
1556)    littleton    ['littleton', 'colorado']-------------------Littleton, Colorado
1635)    philadelphia    ['philadelphia', 'arcadia']-------------------Broadcast, Arcadia Restaurant, Philadelphia, PA
1635)    arcadia    ['philadelphia', 'arcadia']-------------------Broadcast, Arcadia Restaurant, Philadelphia, PA
1645)    lincoln    ['new york', 'lincoln']-------------------NBC Broadcast "Hotel Lincoln", New York
1776)    carrboro    ['north carolina', 'carrboro']-------------------Carrboro, North Carolina, November 1990 to March 1992
1867)    springfield    ['springfield', 'virginia']-------------------Springfield, Virginia
1890)    orlando    ['florida', 'orlando']-------------------Orlando, Florida
1899)    breda    ['breda', 'holland']-------------------Live "Turfschip", Breda, Holland
1919)    knoxville    ['knoxville', 'tennessee']-------------------Knoxville, Tennessee, August 19 & 20, 1993
2022)    euclid    ['euclid', 'ohio']-------------------Shore Cultural Centre, Euclid, Ohio, September 18 & 19, 1992
2027)    appleton    ['appleton', 'wisconsin']-------------------Appleton, Wisconsin, June 21-23, 1993
2053)    melbourne    ['melbourne', 'berlin']-------------------Melbourne, Australia, March 16, 1994 & Berlin, Jan 25, 1995
2086)    victoriaville    ['quebec', 'victoriaville']-------------------Live (*), Victoriaville, Quebec, Canada
2180)    paterson    ['paterson', 'new jersey']-------------------Paterson, New Jersey
2197)    eugene    ['eugene', 'oregon']-------------------Eugene, Oregon
2311)    london    ['los angeles', 'london']-------------------Los Angeles, CA & London, England
2393)    cincinnati    ['cincinnati', 'ohio']-------------------Cincinnati, Ohio, August 1979 & January-February 1980
2536)    carnegie    ['carnegie', 'new york']-------------------Carnegie Hall, New York, prob 1970's
2604)    richmond    ['indiana', 'richmond']-------------------Richmond, Indiana
2610)    charlottenburg    ['berlin', 'charlottenburg']-------------------Townhall Charlottenburg, Berlin
2627)    dearborn    ['dearborn', 'michigan']-------------------Dearborn, Michigan
2657)    burbank    ['hollywood', 'burbank']-------------------Hollywood & Burbank, CA
2746)    moers    ['moers', 'berlin']-------------------Moers, May 19 & Berlin, Germany, December 11, 1975
2856)    dallas    ['dallas', 'texas']-------------------Dallas, Texas, May 15 & 16, 1996
2916)    austin    ['texas', 'austin']-------------------Austin, Texas
2986)    north miami beach    ['florida', 'north miami beach']-------------------North Miami Beach, Florida, late 1980
3042)    portsmouth    ['rhode island', 'portsmouth']-------------------Portsmouth, Rhode Island
3043)    nashville    ['los angeles', 'new york', 'nashville']-------------------Los Angeles, New York or Nashville
3157)    paris    ['paris', 'olympia']-------------------Concert, Olympia Theatre, Paris
3157)    olympia    ['paris', 'olympia']-------------------Concert, Olympia Theatre, Paris
3452)    silver spring    ['silver spring', 'springs']-------------------Silver Springs, MD, September 4 & 5 and October 15, 1973
3452)    springs    ['silver spring', 'springs']-------------------Silver Springs, MD, September 4 & 5 and October 15, 1973
3461)    santa monica    ['santa monica', 'virginia']-------------------Santa Monica, CA, April-June 1981 & Virginia, June, 1981
3549)    carlisle    ['carlisle', 'massachusetts']-------------------Carlisle, Massachusetts, July 26 & 27, 1987
3550)    edmonton    ['alberta', 'edmonton']-------------------Live "Yardbird Suite", Edmonton, Alberta, Canada, June 30
3551)    andover    ['massachusetts', 'andover']-------------------Andover, Massachusetts, April 11 & 12, 1995
3564)    halifax    ['halifax', 'nova scotia']-------------------Halifax, Nova Scotia
3573)    islington    ['islington', 'london']-------------------"Hope & Anchor", Islington, London
3576)    royal oak    ['royal oak', 'london']-------------------Live "Bull's Head" & Royal Oak, London
3578)    country club    ['country club', 'london']-------------------Live "Country Club", Hampstead, London
3630)    madison    ['madison', 'wisconsin']-------------------Live "Farley's House of Music", Madison, Wisconsin
3850)    weesp    ['weesp', 'holland']-------------------Weesp, Holland, 1977
3907)    arese    ['mila', 'arese']-------------------Live "Gipico Incontri", Arese, Milan
3949)    cleveland    ['ohio', 'cleveland']-------------------Cleveland, Ohio
4111)    claremont    ['claremont', 'ontario']-------------------Claremont, Ontario, March 18 & 19, 1987
4118)    surrey    ['surrey', 'banstead']-------------------Banstead, Surrey, September 12 & October 15, 1994
4118)    banstead    ['surrey', 'banstead']-------------------Banstead, Surrey, September 12 & October 15, 1994
4120)    kitchener    ['kitchener', 'ontario']-------------------Live, CKCO TV series "Swing Sensation", Kitchener, Ontario
4121)    guelph    ['ontario', 'guelph']-------------------Priory Room, Gardin Place Hotel, Guelph, Ontario
4242)    albany    ['albany', 'new york']-------------------Albany, New York
4367)    rochester    ['los angeles', 'rochester']-------------------Los Angeles, CA & Rochester, NY
4390)    leeuwarden    ['holland', 'leeuwarden']-------------------"Theatre Rumein", Leeuwarden, Holland
4397)    glendale    ['santa ana', 'westminster', 'glendale', 'san rafael']-------------------Santa Ana, Westminster, San Rafael & Glendale, CA
4397)    san rafael    ['santa ana', 'westminster', 'glendale', 'san rafael']-------------------Santa Ana, Westminster, San Rafael & Glendale, CA
4431)    sun city    ['sun city', 'suisun']-------------------Suisun City, CA
4431)    suisun    ['sun city', 'suisun']-------------------Suisun City, CA
4469)    port washington    ['port washington', 'new york']-------------------Port Washington, New York
4481)    pasadena    ['pasadena', 'california']-------------------Concert, "California Institute of Technology", Pasadena, CA
4532)    redmond    ['redmond', 'washington']-------------------Redmond, Washington, September 2 & 3, 1988
4602)    brno    ['brno', 'prague']-------------------Concerts, Brno & Prague, Czechoslovakia, May 29, June 1,1983
4602)    prague    ['brno', 'prague']-------------------Concerts, Brno & Prague, Czechoslovakia, May 29, June 1,1983
4647)    columbus    ['columbus', 'ohio']-------------------Columbus, Ohio, c. early 60's
4665)    imperial    ['new york', 'imperial']-------------------Concert, Imperial Theatre, New York City, NY
4847)    crosby    ['crosby', 'hollywood']-------------------NBC Broadcast, Bing Crosby Kraft Music Hall, Hollywood, CA
4923)    pace    ['pace', 'new york']-------------------Concert, Pace University, New York
4929)    winnipeg    ['manitoba', 'winnipeg']-------------------Winnipeg, Manitoba
4979)    weston    ['connecticut', 'weston']-------------------Weston, Connecticut
4981)    bartlesville    ['oklahoma', 'bartlesville']-------------------Live "Bartlesville Community Center, Bartlesville, Oklahoma

5066)    detroit    ['detroit', 'michigan']-------------------Live "Baker's Keyboard Lounge", Detroit, Michigan
5081)    grand rapids    ['grand rapids', 'michigan']-------------------Grand Rapids, Michigan, May 10 & 11, 1985
5085)    raleigh    ['north carolina', 'raleigh']-------------------Raleigh, North Carolina, September 19 & 20, 1981
5134)    topeka    ['topeka', 'kansas']-------------------Municipal Auditorium, Topeka, Kansas
5233)    hopkins    ['hopkins', 'san francisco']-------------------Live, "Hotel Mark Hopkins", San Francisco, CA
5253)    milwaukee    ['milwaukee', 'wisconsin']-------------------Milwaukee, Wisconsin, c. June 1947
5271)    renton    ['granada', 'hollywood', 'renton', 'seattle']-------------------Renton, WA, Seattle, WA, Hollywood, CA & Granada Hills, CA
5384)    memphis    ['memphis', 'tennessee']-------------------Memphis, Tennessee
5476)    nakano    ['nakano', 'tokyo']-------------------Live "Nakano Sun Plaza Hall", Tokyo, Japan
5547)    houston    ['texas', 'houston']-------------------Houston, Texas
5610)    battle creek    ['battle creek', 'michigan']-------------------"Percy Jones Hospital", Battle Creek, Michigan
5612)    newark    ['new jersey', 'newark', 'terrace']-------------------Broadcast "Terrace Room", Newark, New Jersey
5612)    terrace    ['new jersey', 'newark', 'terrace']-------------------Broadcast "Terrace Room", Newark, New Jersey
5638)    waukesha    ['waukesha', 'wisconsin']-------------------Waukesha, Wisconsin, January 13 & 14, 1994
5654)    louisville    ['louisville', 'kentucky']-------------------Louisville, Kentucky, March 19 & 20, 1995
5663)    keta    ['keta', 'tokyo']-------------------"keta-no-mise", Tokyo, Feb 23, 28, June 26 & July 18, 1982
6036)    lakewood    ['lakewood', 'ohio']-------------------Live "Symposium", Lakewood, Ohio
6039)    stamford    ['stamford', 'connecticut']-------------------Stamford, Connecticut
6047)    bellevue    ['bellevue', 'washington']-------------------Bellevue, Washington
6142)    shorewood    ['shorewood', 'wisconsin']-------------------Shorewood, Wisconsin, March & April 1996
6178)    berkeley    ['berkeley', 'san francisco']-------------------Berkeley, CA & San Francisco, CA
6272)    denton    ['texas', 'denton']-------------------Denton, Texas
6275)    stirling    ['stirling', 'ontario']-------------------Live "Stirling Theatre", Stirling, Ontario
6359)    cork    ['cork', 'westbury']-------------------Live "Cork & Bib", Westbury, N.Y.
6359)    westbury    ['cork', 'westbury']-------------------Live "Cork & Bib", Westbury, N.Y.
6560)    seymour    ['seymour', 'illinois']-------------------Seymour, Illinois
6609)    rome    ['rome', 'montreux']-------------------Rome, Italy c. June & Montreux, Switzerland, July 1966
6609)    montreux    ['rome', 'montreux']-------------------Rome, Italy c. June & Montreux, Switzerland, July 1966
6684)    elgin    ['elgin', 'illinois']-------------------Elgin, Illinois
6820)    lido    ['paris', 'lido']-------------------Live "The Lido", Paris, France
6829)    kiel    ['st. louis', 'kiel']-------------------Dismas House Benefit, Kiel Opera House, St. Louis, MO
6830)    las vegas    ['las vegas', 'nevada']-------------------Copa Room, Sands Hotel, Las Vegas, Nevada
6939)    alvin    ['alvin', 'new york']-------------------Zutty's apartment, Alvin Hotel, New York
6946)    hilversum    ['holland', 'hilversum']-------------------Hilversum, Holland, July 21, 22 & 23, 1994
7126)    vlissingen    ['holland', 'vlissingen']-------------------"Vestzaktheater", Vlissingen, Holland, October 29 & 30, 1989
7127)    eindhoven    ['holland', 'eindhoven']-------------------Cafe Berlage, Eindhoven, Holland
7128)    rotterdam    ['holland', 'rotterdam']-------------------Zaal de Unie, Rotterdam, Holland
7304)    minnetonka    ['minnesota', 'minnetonka']-------------------Minnetonka Minnesota ?
7315)    fullerton    ['fullerton', 'california']-------------------Fullerton, California, January 18-28, 1994
7461)    pawtucket    ['pawtucket', 'rhode island']-------------------Live "Kings and Queens", Pawtucket, Rhode Island, prob
7541)    burlington    ['vermont', 'burlington']-------------------Burlington, Vermont
7575)    dearborn heights    ['dearborn heights', 'michigan']-------------------Dearborn Heights, Michigan, 1994-1995
7908)    fort worth    ['fort worth', 'texas']-------------------Fort Worth, Texas
8037)    hot springs    ['hot springs', 'arkansas']-------------------Hot Springs, Arkansas
8136)    wilmington    ['wilmington', 'delaware']-------------------Club "Baby Grand", Wilmington, Delaware
8146)    paradise    ['paradise', 'new york']-------------------Live "Small's Paradise", New York
8329)    alton    ['los angeles', 'alton']-------------------Alton Purnell's house, Los Angeles
8337)    eltham    ['london', 'eltham']-------------------Eltham, London
8352)    birmingham    ['alabama', 'birmingham']-------------------Birmingham, Alabama
8477)    phoenix    ['phoenix', 'maryland']-------------------Phoenix, Maryland
8478)    rockville    ['rockville', 'maryland']-------------------Rockville, Maryland
8862)    glasgow    ['glasgow', 'scotland']-------------------Glasgow, Scotland, July 6, 7 and 16, 1983
8955)    westport    ['connecticut', 'westport']-------------------Connecticut Jazz Festival, Westport, Connecticut
9120)    bristol    ['bristol', 'tennessee']-------------------Bristol, Tennessee
9246)    brookfield    ['brookfield', 'illinois']-------------------Brookfield, Illinois
9330)    massy    ['paris', 'massy']-------------------Live "First Festival Independent de Massy", Paris
9346)    la defense    ['paris', 'la defense']-------------------Live "La Defense", Paris
9420)    waalwijk    ['holland', 'waalwijk']-------------------Waalwijk, Holland, February 1989/March 1990
9422)    luton    ['manchester', 'luton']-------------------Luton, December 9, 1993 & Manchester, December 11, 1993
9522)    highland park    ['highland park', 'illinois']-------------------Highland Park, Illinois, February 4 & March 26, 1978
9547)    mundelein    ['illinois', 'mundelein']-------------------Mundelein, Illinois
9596)    metairie    ['metairie', 'new orleans']-------------------"Dr. Souchon's Home, Metairie", New Orleans
9765)    bridgeport    ['bridgeport', 'connecticut']-------------------Bridgeport, Connecticut
9911)    grafton    ['wisconsin', 'grafton']-------------------Grafton, Wisconsin
9989)    vineyard    ['vineyard', 'new york']-------------------Live "Vineyard Theatre", New York
10224)    ratingen    ['new york', 'ratingen']-------------------New York, St. Petersburg, Ratingen, October/November 1995
10225)    bloomington    ['indiana', 'bloomington']-------------------Bloomington, Indiana
10408)    greenville    ['greenville', 'south carolina']-------------------"Ye Olde Fireplace", Greenville, South Carolina
10423)    aurora    ['illinois', 'aurora']-------------------Aurora, Illinois
10494)    chelsea    ['vermont', 'chelsea']-------------------Live "Chelsea House", Brattleboro, Vermont
10518)    oakland    ['houston', 'oakland', 'seattle', 'cleveland']-------------------Oakland, Seattle, Houston, Cleveland, 1993 - 1995
10529)    spokane    ['spokane', 'washington']-------------------Spokane, Washington, unknown date, c. 1980's ?
10628)    davenport    ['davenport', 'iowa']-------------------Davenport, Iowa
10630)    west orange    ['rochester', 'west orange']-------------------Rochester, N.Y. & West Orange, N.J.
10895)    white plains    ['white plains', 'new york']-------------------White Plains, New York
11135)    reno    ['nevada', 'reno']-------------------Reno, Nevada
11144)    high point    ['north carolina', 'high point']-------------------High Point, North Carolina, fall 1971
11150)    oswego    ['oswego', 'new york']-------------------Oswego, New York, August 17 & 19, 1979
11154)    ann arbor    ['ann arbor', 'michigan']-------------------Ann Arbor, Michigan, March 22 & 24, 1985

11454)    dome    ['dome', 'wilton']-------------------Live "The Dome", Wilton, Conn.
11454)    wilton    ['dome', 'wilton']-------------------Live "The Dome", Wilton, Conn.
11513)    solano    ['albany', 'solano']-------------------Erle's Solano Club, Albany, CA
11536)    cologne    ['cologne', 'london']-------------------Cologne, Germany & London (*)
11712)    regina    ['regina', 'berlin']-------------------"Regina Cinema", Berlin
11781)    dublin    ['london', 'dublin']-------------------London & Dublin, mid 1979
11922)    ripon    ['ripon', 'wisconsin']-------------------Ripon, Wisconsin
12111)    kalamazoo    ['kalamazoo', 'michigan']-------------------Kalamazoo, Michigan, 1974
12135)    fort lauderdale    ['florida', 'fort lauderdale']-------------------Live "Bubba's", Fort Lauderdale, Florida
12159)    viersen    ['viersen', 'berlin']-------------------Festhalle Viersen, Berlin, Germany
12195)    sanford    ['florida', 'sanford']-------------------Sanford, Florida, March 10, 11 & 12, 1994
12197)    tampa    ['florida', 'tampa']-------------------Tampa, Florida, June 9 & 10, 1997
12213)    rendsburg    ['neumunster', 'rendsburg']-------------------Live "Hotel Stadt Rendsburg", Neumunster, Germany
12224)    tortona    ['tortona', 'lyon']-------------------Lyon's Club, Tortona, Italy
12224)    lyon    ['tortona', 'lyon']-------------------Lyon's Club, Tortona, Italy
12358)    americana    ['florida', 'miami', 'americana']-------------------NBC Telecast "Americana Hotel", Bal Harbor, Miami, Florida
12454)    corvallis    ['rama', 'corvallis', 'oregon']-------------------Java Rama Cafe, prob St. Corvallis, Oregon
12512)    christchurch    ['claremont', 'christchurch']-------------------Christchurch, Claremont
12514)    boskoop    ['florida', 'boskoop']-------------------Live "Hotel Florida", Boskoop
12658)    kansas city    ['kansas city', 'missouri']-------------------Kansas City, Missouri
12764)    tallinn    ['new york', 'tallinn']-------------------New York (Quintet) & Tallinn, Estonia (Orchestra)
12771)    brooklyn    ['brooklyn', 'new york']-------------------Brooklyn, New York, 1995 & 1998
12772)    munich    ['munich', 'stuttgart']-------------------Stuttgart, Munich & Worthsee, unknown date, 1970's ?
12772)    stuttgart    ['munich', 'stuttgart']-------------------Stuttgart, Munich & Worthsee, unknown date, 1970's ?
12795)    new rochelle    ['new york', 'new rochelle']-------------------Broadcast, Glenn Island Casino, New Rochelle, New York
12987)    venice    ['venice', 'culver city']-------------------Culver City & Venice, CA
12987)    culver city    ['venice', 'culver city']-------------------Culver City & Venice, CA
13013)    seaford    ['new york', 'seaford']-------------------(*) Seaford, November 22, 29, 1984 & New York, June 11, 1985
13198)    ramada    ['ramada', 'virginia']-------------------Manassas Jazz Festival, Ramada Inn, Manassas, Virginia
13214)    charlotte    ['charlotte', 'new york']-------------------Charlotte, N.C. & New York, 1982
13253)    concord    ['concord', 'tokyo']-------------------Live "Fujitsu-Concord Jazz Festival", Tokyo, Japan
13491)    halden    ['oslo', 'halden']-------------------Oslo, August 15-17 & Halden, October 1 & 2, 1997
13517)    iserlohn    ['iserlohn', 'dortmund']-------------------Dortmund or Iserlohn, early 1970
13517)    dortmund    ['iserlohn', 'dortmund']-------------------Dortmund or Iserlohn, early 1970
13602)    scheveningen    ['holland', 'scheveningen', 'new orleans']-------------------"New Orleans Jazzclub", Scheveningen, Holland, Oct 25, 1975
13648)    woking    ['surrey', 'woking']-------------------All Saint's Church Hall, Woking, Surrey, England
13660)    north hollywood    ['north hollywood', 'burbank']-------------------Burbank & North Hollywood, CA, Aug 2, 1995 & April 15, 1996
13907)    neu-ulm    ['neu-ulm', 'illertissen']-------------------Stettin, Illertissen, Neu-Ulm, 1995/1996
13907)    illertissen    ['neu-ulm', 'illertissen']-------------------Stettin, Illertissen, Neu-Ulm, 1995/1996
13959)    battersea    ['london', 'battersea']-------------------Albert House, Battersea, London
14102)    watertown    ['massachusetts', 'watertown']-------------------Watertown, Massachusetts, unknown date, 1980's ?
14216)    manhattan    ['manhattan', 'new york']-------------------Live "Manhattan School of Music", New York
14306)    salt lake city    ['salt lake city', 'utah']-------------------Salt Lake City, Utah
14326)    riehen    ['riehen', 'basel']-------------------Riehen/Basel, July 11 & 12, 1975
14511)    provo    ['utah', 'provo']-------------------Provo, Utah
14611)    livonia    ['livonia', 'michigan']-------------------Livonia, Michigan
14948)    larvik    ['larvik', 'oslo']-------------------Oslo, May 1990 (*) & Larvik, March & May 1991
14962)    milwaukie    ['milwaukie', 'oregon']-------------------Milwaukie, Oregon, July 24 & 25 and September 7, 1990
15088)    augsburg    ['augsburg', 'munich']-------------------Live, Augsburg, February 5 & Munich, February 6, 1987
15121)    san antonio    ['texas', 'san antonio']-------------------Texas Hotel, San Antonio, Texas
15142)    helsinki    ['new york', 'helsinki']-------------------Helsinki, 1979/1980 & New York, June 1980
15169)    amsterdam    ['holland', 'amsterdam']-------------------Amsterdam, Holland
15290)    copenhagen    ['copenhagen', 'fontaine']-------------------Live "La Fontaine", Copenhagen, Denmark
15290)    fontaine    ['copenhagen', 'fontaine']-------------------Live "La Fontaine", Copenhagen, Denmark
15293)    leiden    ['leiden', 'holland']-------------------Leiden, Holland
15546)    concordia    ['concordia', 'new york']-------------------Live "Concordia College", New York, June 13 & 14, 1988
15597)    antioch    ['springs', 'antioch']-------------------Live, "Antioch Theatre, Antioch College", Yellow Springs, OH
15786)    salisbury    ['salisbury', 'barnet']-------------------Salisbury, Barnet, Herts.
15786)    barnet    ['salisbury', 'barnet']-------------------Salisbury, Barnet, Herts.
15862)    taylor    ['texas', 'taylor', 'austin']-------------------Taylor home, Austin, Texas
15893)    zeist    ['holland', 'zeist']-------------------Zeist, Holland, May 13 & 14, 1968
15908)    rouen    ['rouen', 'croix']-------------------Live, Salle Ste Croix des Pelletiers, Rouen, France
15958)    boston    ['southland', 'boston']-------------------Broadcast, "Southland Restaurant", Boston
15980)    wichita    ['wichita', 'texas']-------------------Sheppard Field, Wichita Falls, Texas
16153)    woodstock    ['woodstock', 'new york']-------------------Woodstock, New York
16166)    winterthur    ['new york', 'winterthur']-------------------Winterthur, Santis Mountain & New York, May 31-July 2, 1992
16265)    orland park    ['illinois', 'orland park']-------------------Orland Park, Illinois, April 15, 16 & 17, 1997
16548)    lubbock    ['texas', 'lubbock']-------------------Lubbock, Texas, April 28 & 29, 1994
16748)    the hague    ['holland', 'the hague']-------------------Live, North Sea Jazz Festival, The Hague, Holland
16749)    tivoli    ['tivoli', 'holland']-------------------Live "Tivoli", Rijen, Holland
16866)    lillehammer    ['gjovik', 'lillehammer']-------------------Lillehammer & Gjovik
16963)    clermont-ferrand    ['tete', 'clermont-ferrand']-------------------Live, Jazz en Tete Festival, Clermont-Ferrand, France
16965)    akron    ['ohio', 'akron']-------------------Akron, Ohio
16972)    erding    ['erding', 'munich']-------------------Live "Hirschwirt", Erding, Munich, Germany
16973)    painesville    ['painesville', 'ohio']-------------------Painesville, Ohio
17099)    oxon hill    ['oxon hill', 'anna']-------------------Fred & Anna Wahler's basement studio, Oxon Hill, MD
17107)    winschoten    ['holland', 'winschoten']-------------------Live "Gumbo Jazzclub, Hotel Vrijheid", Winschoten, Holland
17115)    fillmore    ['fillmore', 'new york']-------------------Live "Fillmore East", New York
17134)    berea    ['st. louis', 'berea', 'missouri']-------------------Live "Berea Presbyterian Church", St. Louis, Missouri
17199)    yonkers    ['new york', 'yonkers']-------------------Yonkers, New York
17262)    charleston    ['north carolina', 'charleston']-------------------Charleston, North Carolina
17289)    beek    ['holland', 'beek']-------------------Live "Het Oude Raadhuis", Beek en Donk, Holland
17290)    lansing    ['eastern', 'lansing', 'michigan']-------------------Eastern High School Auditorium, Lansing, Michigan
17300)    libertyville    ['illinois', 'libertyville']-------------------Live "The Cabriolet", Libertyville, Illinois

17647)    roosevelt    ['new orleans', 'roosevelt']-------------------AFRS "One Night Stand", Roosevelt Hotel, New Orleans
17649)    atlantic city    ['new jersey', 'atlantic city']-------------------CBS Broadcast, Steel Pier, Atlantic City, New Jersey
17769)    hillside    ['hillside', 'englewood']-------------------Hillside Sound Studio, Englewood, N.J.
17769)    englewood    ['hillside', 'englewood']-------------------Hillside Sound Studio, Englewood, N.J.
17824)    farmington hills    ['farmington hills', 'michigan']-------------------Farmington Hills, Michigan, March & April 1996
17888)    hickory    ['hickory', 'new york']-------------------NBC Broadcast "Hickory House", New York
17917)    hudson    ['hudson', 'new york', 'hastings']-------------------Hastings on Hudson, New York
17917)    hastings    ['hudson', 'new york', 'hastings']-------------------Hastings on Hudson, New York
18015)    markham    ['markham', 'ontario']-------------------Markham, Ontario
18108)    middelburg    ['holland', 'middelburg']-------------------Live "De Kuipershoek", Middelburg, Holland
18110)    tilburg    ['holland', 'tilburg']-------------------Live "Cultureel Centrum", Tilburg, Holland
18147)    westlake    ['westlake', 'seattle']-------------------Live "Westlake Center", Seattle, WA
18196)    lake oswego    ['oregon', 'lake oswego']-------------------Lake Oswego, Oregon, March 24 & 25, 1997
18234)    sacramento    ['sacramento', 'san jose']-------------------Concerts, Sacramento & San Jose, CA, spring 1960
18234)    san jose    ['sacramento', 'san jose']-------------------Concerts, Sacramento & San Jose, CA, spring 1960
18315)    richmond hill    ['ontario', 'richmond hill']-------------------Richmond Hill, Ontario, May 18, 19 & June 1, 2, 1998
18348)    west hollywood    ['west hollywood', 'burbank']-------------------Burbank & West Hollywood, CA
18428)    yokohama    ['kanagawa', 'yokohama']-------------------Live "Yokohama City Jazz Club DOLPHY", Kanagawa
18551)    beltsville    ['maryland', 'beltsville']-------------------Beltsville, Maryland, summer 1994
18552)    wheaton    ['washington', 'wheaton']-------------------Washington, DC & Wheaton, MD, July 23-25, 1996
18586)    noci    ['bari', 'noci']-------------------Noci, Bari
18813)    amherst    ['amherst', 'the valley']-------------------Live "2nd Fire in The Valley Festival", Amherst, MA
18813)    the valley    ['amherst', 'the valley']-------------------Live "2nd Fire in The Valley Festival", Amherst, MA
18894)    hinsdale    ['illinois', 'hinsdale']-------------------"Union Church", Hinsdale, Illinois
19013)    pennsauken    ['new jersey', 'pennsauken']-------------------Live "Red Hill Club", Pennsauken, New Jersey
19050)    georgetown    ['washington, d.c.', 'georgetown']-------------------Live "Charlie's", Georgetown, Washington, D.C.
19054)    saratoga    ['saratoga', 'mason']-------------------Live "Paul Mason Mountain Winery", Saratoga, CA
19054)    mason    ['saratoga', 'mason']-------------------Live "Paul Mason Mountain Winery", Saratoga, CA
19131)    coral gables    ['fort lauderdale', 'miami', 'coral gables']-------------------Miami, Coral Gables, Fort Lauderdale
19266)    baltimore    ['maryland', 'baltimore']-------------------Baltimore, Maryland, 1971-1972
19344)    south hill    ['south hill', 'bracknell']-------------------"South Hill Park", Bracknell, April 24 & 25, 1978
19344)    bracknell    ['south hill', 'bracknell']-------------------"South Hill Park", Bracknell, April 24 & 25, 1978
19665)    atlantis    ['atlantis', 'basel']-------------------Live "Atlantis", Basel, August 12 & 13, 1977
19772)    warwick    ['rhode island', 'warwick']-------------------Community College, Warwick, Rhode Island
20251)    takamatsu    ['kagawa', 'takamatsu']-------------------Takamatsu, Kagawa-ken, Nihon Takamatsu Ten Hall
20390)    alkmaar    ['alkmaar', 'heemskerk']-------------------Live " 't Wapen van Heemskerk", Alkmaar
20390)    heemskerk    ['alkmaar', 'heemskerk']-------------------Live " 't Wapen van Heemskerk", Alkmaar
20602)    frankfurt    ['paris', 'frankfurt']-------------------Live, Paris, April 17 & Frankfurt, April 24, 1972
21033)    ferndale    ['ferndale', 'michigan']-------------------Ferndale, Michigan, December 15 & 16, 1998
21278)    troy    ['troy', 'michigan']-------------------Troy, Michigan
21435)    baton rouge    ['louisiana', 'baton rouge']-------------------Baton Rouge, Louisiana, October 1940
21532)    bordeaux    ['bordeaux', 'alhambra']-------------------Live "Alhambra", Bordeaux, France
21532)    alhambra    ['bordeaux', 'alhambra']-------------------Live "Alhambra", Bordeaux, France
21670)    south bend    ['indiana', 'south bend']-------------------Live "Notre Dame Collegiate Festival", South Bend, Indiana
21671)    new albany    ['indiana', 'new albany']-------------------New Albany, Indiana, 1974
21829)    heemstede    ['holland', 'heemstede']-------------------Heemstede, Holland
21889)    peabody    ['peabody', 'memphis']-------------------Peabody Hotel, Memphis
22065)    huntsville    ['texas', 'huntsville']-------------------Huntsville, State Penitentiary, Texas, c. April 1934
22654)    ocoee    ['florida', 'ocoee']-------------------Ocoee, Florida
22697)    scottsdale    ['arizona', 'scottsdale']-------------------Scottsdale, Arizona
22749)    plantation    ['plantation', 'columbia']-------------------Brevard Plantation, Adams Hill, Columbia, 1939
22878)    liverpool    ['london', 'victoria', 'liverpool']-------------------"Liverpool & Victoria Hall", London
23026)    livingston    ['livingston', 'alabama']-------------------Livingston, Alabama, 1937
23027)    livingstone    ['alabama', 'livingstone']-------------------Livingstone, Alabama, 1940
23439)    belle glade    ['florida', 'belle glade']-------------------Belle Glade, Florida, 1935
23629)    modena    ['mila', 'modena']-------------------Modena, February 10, 1990 * & Milan, February 12 & 13, 1990
23747)    scarborough    ['scarborough', 'ontario']-------------------Scarborough, Ontario
23935)    bellingham    ['bellingham', 'washington']-------------------Bellingham, Washington
23939)    walker    ['minnesota', 'walker', 'minneapolis']-------------------Live "Walker Art Center", Minneapolis, Minnesota
24030)    vicksburg    ['mississippi', 'vicksburg']-------------------Vicksburg, Mississippi, 1939
24119)    windsor    ['windsor', 'ontario']-------------------Windsor, Ontario
24685)    dayton    ['ohio', 'dayton']-------------------Broadcast, Dayton, Ohio, 1939
25540)    wright    ['wright', 'yarmouth']-------------------Yarmouth, Isle of Wright
25540)    yarmouth    ['wright', 'yarmouth']-------------------Yarmouth, Isle of Wright
25582)    brighton    ['brighton', 'dome']-------------------The Dome, Brighton
25595)    halle    ['halle', 'berlin']-------------------Deutschland Halle, Berlin
25713)    amersfoort    ['amersfoort', 'flint']-------------------Concert "De Flint", Amersfoort
25713)    flint    ['amersfoort', 'flint']-------------------Concert "De Flint", Amersfoort
25969)    bimbo    ['bimbo', 'san francisco']-------------------Live "Bimbo's, San Francisco
25991)    clarksdale    ['clarksdale', 'memphis']-------------------Memphis (*), Clarksdale (+)
26042)    nijmegen    ['holland', 'nijmegen']-------------------Nijmegen, Holland
26043)    weert    ['holland', 'weert']-------------------Weert, Holland
26157)    riverside    ['riverside', 'new york']-------------------Live "Riverside Part Arts Festival", New York

26791)    waldorf    ['waldorf', 'new york']-------------------Broadcast "Waldorf Astoria", New York
26975)    nordhorn    ['hollywood', 'nordhorn', 'glendale']-------------------Nordhorn, Blaricum, Glendale & Hollywood, 1980's
27073)    sarasota    ['florida', 'sarasota']-------------------Sarasota, Florida, January 24 & 25, 1981
27131)    pittsburgh    ['carnegie', 'pittsburgh']-------------------Live "Carnegie Lecture Hall", Pittsburgh, Penn.
27329)    beverly    ['beverly', 'wellesley']-------------------(*) Wellesley, MA & Beverly, MA
27329)    wellesley    ['beverly', 'wellesley']-------------------(*) Wellesley, MA & Beverly, MA
27423)    peoria    ['illinois', 'peoria']-------------------Peoria, Illinois (*), 1978 & 1979
27617)    hoboken    ['hoboken', 'brooklyn']-------------------Hoboken, N.J. & Brooklyn N.Y. (*), 1991
27993)    sydney    ['melbourne', 'sydney']-------------------Live, Melbourne (*) and Sydney, Australia
28066)    youngstown    ['youngstown', 'ohio']-------------------Broadcast, Youngstown, Ohio
28616)    missoula    ['missoula', 'montana']-------------------Missoula, Montana
28745)    leatherhead    ['surrey', 'leatherhead']-------------------Leatherhead, Surrey
28890)    napier    ['london', 'napier']-------------------"The Lord Napier", Thorton Heath, London
29479)    san jacinto    ['san jacinto', 'new orleans']-------------------"San Jacinto Hall", New Orleans, December 28-31, 1964
29613)    antibes    ['los angeles', 'antibes']-------------------Los Angeles & Antibes, France
30017)    boulder    ['colorado', 'boulder']-------------------Boulder, Colorado
30077)    bergen    ['agar', 'bergen', 'paramus']-------------------Bergen Community College, Paramus, N.J., June 24, 1979, Agar
30077)    paramus    ['agar', 'bergen', 'paramus']-------------------Bergen Community College, Paramus, N.J., June 24, 1979, Agar
30142)    mountlake terrace    ['seattle', 'mountlake terrace']-------------------Mountlake Terrace & Seattle WA., c. 1991, 1992
30387)    gainesville    ['florida', 'gainesville']-------------------Live "The Thomas Center", Gainesville, Florida
30724)    baarn    ['holland', 'baarn']-------------------Baarn, Holland, January 1972
30753)    frascati    ['frascati', 'amsterdam']-------------------"Frascati Theater", Amsterdam
30863)    chelmsford    ['chelmsford', 'essex']-------------------Chelmsford, Essex, c. 1977
30863)    essex    ['chelmsford', 'essex']-------------------Chelmsford, Essex, c. 1977
30912)    carmelo    ['los angeles', 'carmelo']-------------------Live "Carmelo's & Paquales", Los Angeles, CA.
31075)    bratislava    ['bratislava', 'brno']-------------------Brno or Bratislava, 1975/1976
31184)    howard    ['washington, d.c.', 'howard']-------------------Live "Howard University", Washington, D.C.
31200)    lynnwood    ['lynnwood', 'ontario']-------------------In concert "Lynnwood Arts Centre", Simcoe, Ontario, Canada
31435)    augusta    ['bell', 'augusta']-------------------Concert "Bell Auditorium", Augusta, Ga.
31786)    thornton    ['thornton', 'napier']-------------------Live "The Lord Napier", Thornton Heath
31928)    potomac    ['maryland', 'potomac']-------------------Potomac, Maryland
32507)    sheridan    ['oregon', 'sheridan']-------------------Sheridan, Oregon, October 23, 24  & 25, 1978
32842)    coney island    ['coney island', 'new york']-------------------Coney Island, New York
32917)    toledo    ['ohio', 'toledo']-------------------Toledo, Ohio, c. 1974
33421)    corpus christi    ['texas', 'corpus christi']-------------------Corpus Christi, Texas, mid 1950's
33504)    calgary    ['alberta', 'calgary']-------------------"Alberta College of Art", Calgary, Alberta
33941)    cagliari    ['sardinia', 'cagliari']-------------------Cagliari, Sardinia, Italy, January 4/6, 1992
34342)    udine    ['udine', 'rome']-------------------Moruzzo, Udine, April 1974 & Rome, May 10-14, 1974
34353)    tuscaloosa    ['tuscaloosa', 'alabama']-------------------Ferg Forum, University of Alabama, Tuscaloosa, Alabama
34354)    jackson    ['mississippi', 'jackson']-------------------McClung Gallery, Jackson, Mississippi
34359)    bologna    ['bologna', 'pistoia']-------------------Moruzzi, Bologna & Pistoia, November 1977 to August 1980
34359)    pistoia    ['bologna', 'pistoia']-------------------Moruzzi, Bologna & Pistoia, November 1977 to August 1980
34429)    greensboro    ['new york', 'greensboro']-------------------New York, March 1980 & Greensboro, N.C., June 1980
34852)    dartmouth    ['dartmouth', 'hanover', 'new hampshire']-------------------Dartmouth College, Hanover, New Hampshire, winter 1969-70
34852)    hanover    ['dartmouth', 'hanover', 'new hampshire']-------------------Dartmouth College, Hanover, New Hampshire, winter 1969-70
35005)    stockport    ['manchester', 'stockport']-------------------"Stockport", Manchester
35088)    villejuif    ['paris', 'villejuif']-------------------Paris, December 20, 1975 & Villejuif, January 25, 1976
35105)    camden    ['camden', 'south carolina']-------------------Camden, South Carolina
35220)    waltham    ['london', 'waltham']-------------------Theobalds College, Waltham Cross, London
35253)    warsaw    ['moscow', 'leningrad', 'warsaw']-------------------Warsaw Concert Hall, Moscow & Leningrad Capella
35298)    irving    ['new york', 'irving']-------------------Live "Irving Plaza", Kool Jazz Festival 1984, New York
35310)    monroe    ['monroe', 'new york']-------------------Live "Monroe's Uptown House", New York, May 1941
35352)    colorado springs    ['colorado springs', 'palmer']-------------------Live "Palmer House", Colorado Springs, Colorado
35352)    palmer    ['colorado springs', 'palmer']-------------------Live "Palmer House", Colorado Springs, Colorado
35547)    boca raton    ['florida', 'boca raton']-------------------Live, Boca Raton, Florida
35652)    altamonte springs    ['florida', 'altamonte springs']-------------------Altamonte Springs, Florida
35657)    johnstown    ['florida', 'johnstown']-------------------Johnstown, Florida
35765)    atlanta    ['atlanta', 'chicago']-------------------Chicago & Atlanta
36392)    grand prairie    ['texas', 'grand prairie']-------------------Grand Prairie, Texas, summer 1979
36657)    nottingham    ['london', 'nottingham']-------------------Nottingham & London
36698)    dix hills    ['new york', 'dix hills']-------------------Dix Hills, New York
36945)    blackheath    ['london', 'blackheath']-------------------Eaglesfield School, Blackheath, London
36996)    peterborough    ['peterborough', 'ontario']-------------------Peterborough, Ontario, Canada
37006)    west end    ['new york', 'west end']-------------------Live "West End Cafe", New York, 1987
37111)    chesterfield    ['chesterfield', 'new york']-------------------Chesterfield Audition Show, New York, spring 1945
37571)    tacoma    ['washington', 'tacoma']-------------------Tacoma, Washington, c. mid 1972
37611)    cannes    ['paris', 'cannes']-------------------Paris, January 22, 1978 & Live "Midem", Cannes, Feb 1978
37836)    los altos    ['berkeley', 'los altos']-------------------Los Altos Hills & Berkeley, CA, c. 1992
38167)    newcastle    ['newcastle', 'london']-------------------Newcastle & London, 1975
38740)    walla walla    ['walla walla', 'washington']-------------------Broadcast "Air Base Walla Walla", Washington
38934)    belmont    ['belmont', 'atlantic city']-------------------"Grace's Little Belmont", Atlantic City
39121)    rochford    ['rochford', 'essex']-------------------Rochford, Essex, England
40055)    annapolis    ['annapolis', 'maryland']-------------------Live "The Maryland Inn", Annapolis, Maryland

40557)    davis    ['new york', 'davis']-------------------Broadcast, Davis' home, New York
40712)    save    ['chicago', 'save']-------------------Film-soundtrack "Save the children", Chicago
40775)    grandview    ['columbus', 'ohio', 'grandview']-------------------Live "The Grandview Inn", Columbus, Ohio, April 6-10, 1966
40925)    lansdowne    ['lansdowne', 'toronto']-------------------Concert "Lansdowne Assembly Hall", Toronto
41159)    buffalo    ['buffalo', 'boston']-------------------Buffalo & Boston, spring/autumn 1975
41278)    den helder    ['holland', 'den helder']-------------------"Casino", Den Helder, Holland, 1936
41960)    bonn    ['bonn', 'remagen']-------------------Remagen (near Bonn), Germany
41960)    remagen    ['bonn', 'remagen']-------------------Remagen (near Bonn), Germany
42180)    carbondale    ['illinois', 'carbondale']-------------------Live "Southern Illinois University", Carbondale
42360)    bussum    ['bussum', 'amsterdam']-------------------Bussum or Amsterdam, c. 1955
42502)    bradley    ['bradley', 'new york']-------------------Live "Bradley's", New York
42545)    new milford    ['new milford', 'providence']-------------------Sherman & New Milford CT, and Brown Univ., Providence, R.I.
42680)    dordrecht    ['rotterdam', 'dordrecht']-------------------Rotterdam, 1982-83 & Dordrecht, July 1983
42781)    syracuse    ['syracuse', 'new york']-------------------Live, Syracuse/New York
43289)    rhede    ['new orleans', 'rhede']-------------------Live "New Orleans", Rhede, March 4 & 5, 1978
43840)    long beach    ['long beach', 'california']-------------------Broadcast, Long Beach, California
43844)    wooster    ['ohio', 'wooster']-------------------Broadcast, Navy School, Wooster, Ohio
44195)    petaluma    ['bali', 'petaluma', 'san francisco']-------------------San Francisco, Bali Inonisia, Petaluma Ca., 1989-1991
44222)    stanley    ['stanley', 'ontario']-------------------Port Stanley, Ontario, Canada, 1957-1958
44312)    pinellas park    ['florida', 'pinellas park']-------------------Pinellas Park, Florida
44344)    morton grove    ['morton grove', 'illinois']-------------------Morton Grove, Illinois
44653)    goodyear    ['goodyear', 'alabama']-------------------Goodyear Municipal Auditorium, Gadsen, Alabama
45429)    falcon    ['los angeles', 'falcon']-------------------"Falcon's Lair", Los Angeles, 1959
45861)    ottawa    ['ottawa', 'ontario']-------------------Ottawa, Ontario
45921)    brandon    ['florida', 'brandon']-------------------Brandon, Florida, c. 1992
45928)    franklin    ['franklin', 'brandon']-------------------Franklin, Tenn. & Brandon Fl, 1992
45954)    sugar hill    ['sugar hill', 'houston']-------------------Live "Sugar Hill Recording Studios", Houston, TX, c. 1991
46255)    hunt valley    ['maryland', 'hunt valley', 'baltimore']-------------------Baltimore & Hunt Valley, Maryland, unknown date
46278)    sherbrooke    ['quebec', 'sherbrooke']-------------------Sherbrooke, Quebec, Canada, 1979
46445)    tucson    ['arizona', 'tucson']-------------------Tucson, Arizona
46530)    naples    ['naples', 'rome']-------------------Rome & Naples
46797)    cine    ['buenos aires', 'cine']-------------------Live "Cine Teatro Gran Rex", Buenos Aires, Argentina
46804)    hull    ['quebec', 'hull', 'gatineau']-------------------Camp Fortune, Gatineau Hills, Hull, Quebec, Canada
46804)    gatineau    ['quebec', 'hull', 'gatineau']-------------------Camp Fortune, Gatineau Hills, Hull, Quebec, Canada
46830)    san martin    ['buenos aires', 'san martin']-------------------"Teatro Municipal General San Martin", Buenos Aires
46863)    northfield    ['minnesota', 'northfield']-------------------Northfield, Minnesota
46938)    whitney    ['new york', 'whitney']-------------------Whitney Museum, New York
46983)    bradford    ['george', 'bradford']-------------------Live, "St. George's Hall", Bradford
47138)    jacksonville    ['florida', 'jacksonville']-------------------Live "Florida Theatre", Jacksonville, Florida
47561)    buchanan    ['new york', 'buchanan']-------------------Live "Buchanan Hall", New York
47570)    mesa    ['hollywood', 'mesa', 'kearny']-------------------Rancho Bernardo, Kearny Mesa & Hollywood, June'86/April 1987
47570)    kearny    ['hollywood', 'mesa', 'kearny']-------------------Rancho Bernardo, Kearny Mesa & Hollywood, June'86/April 1987
48285)    reims    ['paris', 'massy', 'reims']-------------------Massy, Paris & Reims, January-November 1975
48407)    owings mills    ['maryland', 'owings mills']-------------------Owings Mills, Maryland
48599)    freiburg    ['cologne', 'freiburg']-------------------Freiburg, April 28/29 & Cologne, December 13, 1991
50070)    allentown    ['pennsylvania', 'allentown']-------------------Allentown, Pennsylvania, May 14 & 15, 1973
50071)    bethlehem    ['pennsylvania', 'bethlehem']-------------------Bethlehem, Pennsylvania
50194)    norwich    ['norwich', 'bedford']-------------------Norwich, June 26, 1978 & Bedford, England, June 27, 1978
50194)    bedford    ['norwich', 'bedford']-------------------Norwich, June 26, 1978 & Bedford, England, June 27, 1978
50345)    roseville    ['california', 'roseville']-------------------Roseville, California
50365)    sassari    ['sardinia', 'sassari']-------------------Sassari, Sardinia, November 30 & December 2, 1985
50394)    schaumburg    ['illinois', 'schaumburg']-------------------Schaumburg, Illinois, c. 1984
50453)    tigard    ['tigard', 'oregon']-------------------Tigard, Oregon
50471)    somerville    ['boston', 'somerville']-------------------"Somerville Theatre", Boston, Mass.
50533)    sheffield    ['george', 'sheffield']-------------------"George IV", Sheffield, England
50534)    leeds    ['leeds', 'adelphi']-------------------"Termite Club - The Adelphi", Leeds Bridge End, England
50534)    adelphi    ['leeds', 'adelphi']-------------------"Termite Club - The Adelphi", Leeds Bridge End, England
50535)    conway    ['london', 'conway']-------------------"Club Integral - Conway Hall", London, England
50814)    woodbury    ['connecticut', 'woodbury']-------------------"Old Town Hall", Woodbury, Connecticut
51109)    hermitage    ['hermitage', 'montreal']-------------------"The Hermitage", Montreal
51282)    belfast    ['northern ireland', 'belfast']-------------------Belfast, Northern Ireland
51338)    clinton    ['new york', 'clinton']-------------------Live "Clinton Recording Studio", New York
52068)    albuquerque    ['albuquerque', 'new mexico']-------------------Albuquerque (?), New Mexico, unknown date
52162)    arnold    ['stockholm', 'arnold']-------------------Harry Arnold's TV-Show, Stockholm, Sweden
52356)    versailles    ['hollywood', 'versailles']-------------------"Versailles Room", Hollywood, c. 1959
52675)    monterey    ['los angeles', 'monterey']-------------------Concert "Monterey Jazz Festival", Los Angeles, CA
53127)    davie    ['florida', 'davie']-------------------Davie, Florida
53423)    kenner    ['louisiana', 'kenner']-------------------Kenner, Louisiana, February 11 & 12, 1992
54069)    perth    ['perth', 'sydney']-------------------Sydney & Perth
54215)    normal    ['paris', 'normal']-------------------Live "L'Ecole Normal Superieure", Paris, France
54419)    delft    ['holland', 'delft']-------------------Delft, Holland
54425)    avignon    ['paris', 'avignon']-------------------Avignon, March 1981 & Paris, April 1982
54540)    innsbruck    ['innsbruck', 'olympia']-------------------"Olympia Hotel", Innsbruck

54880)    orangeville    ['orangeville', 'ontario']-------------------Prob. Orangeville, Ontario, Canada
55124)    torrance    ['torrance', 'california']-------------------Torrance, California
55332)    haarlem    ['holland', 'haarlem']-------------------Haarlem, Holland
55696)    lake forest    ['chicago', 'lake forest']-------------------Lake Forest, Chicago, October/December 1957
55943)    formigine    ['bologna', 'formigine']-------------------Bologna & Formigine
56006)    flower mound    ['texas', 'flower mound']-------------------Flower Mound, Texas
56049)    sherman oaks    ['north hollywood', 'sherman oaks']-------------------North Hollywood & Sherman Oaks, CA
56477)    buka    ['buka', 'tokyo', 'musashino']-------------------Live "Musashino Shimin Buka Kaikan", Tokyo, Japan
56477)    musashino    ['buka', 'tokyo', 'musashino']-------------------Live "Musashino Shimin Buka Kaikan", Tokyo, Japan
56803)    new delhi    ['new delhi', 'new york']-------------------New Delhi & New York, 1970 & October 1986
57078)    irvine    ['irvine', 'laguna']-------------------"Irvine Bowl", Laguna Beach, CA
57078)    laguna    ['irvine', 'laguna']-------------------"Irvine Bowl", Laguna Beach, CA
57079)    police    ['los angeles', 'police']-------------------Los Angeles Police Academy, Chavez Ravine, Los Angeles
57614)    little rock    ['little rock', 'arkansas']-------------------Broadcast, Little Rock, Arkansas
57783)    emmen    ['emmen', 'holland']-------------------Live "De Muzeval", Emmen, Holland
57889)    san diego    ['berkeley', 'san diego']-------------------Concerts, Berkeley, Ca., July 16 & San Diego, July 18, 1977
58015)    chandler    ['north carolina', 'chandler']-------------------Chandler, North Carolina, c. late 1970's
58020)    asheville    ['north carolina', 'asheville']-------------------Asheville, North Carolina
58276)    algonquin    ['algonquin', 'new york']-------------------"The Algonquin Hotel", New York, c. 1991
58363)    fontainebleau    ['paris', 'fontainebleau']-------------------"Theatre de Fontainebleau", Paris
58397)    coventry    ['coventry', 'warwick']-------------------Warwick University, Coventry, England
58889)    caldwell    ['idaho', 'caldwell']-------------------Live "Ste. Chapplle Winery", Caldwell, Idaho
59134)    edinburg    ['edinburg', 'scotland']-------------------Edinburg, Scotland
59302)    centerville    ['centerville', 'fremont']-------------------"Centerville Presbyterian Church", Fremont, CA
59302)    fremont    ['centerville', 'fremont']-------------------"Centerville Presbyterian Church", Fremont, CA
60014)    morton    ['morton', 'illinois']-------------------Morton, Illinois, April & October 1980
60480)    soest    ['soest', 'holland']-------------------Soest, Holland, January 31 & February 1, 1988
60930)    canoga park    ['canoga park', 'calabasas']-------------------Canoga Park, CA. and Calabasas, CA., November-December 1990
60930)    calabasas    ['canoga park', 'calabasas']-------------------Canoga Park, CA. and Calabasas, CA., November-December 1990
61227)    wiesbaden    ['wiesbaden', 'hannover']-------------------Hannover, January 18 & Wiesbaden, January 23, 1976
61227)    hannover    ['wiesbaden', 'hannover']-------------------Hannover, January 18 & Wiesbaden, January 23, 1976
61795)    northglenn    ['northglenn', 'colorado']-------------------Northglenn, Colorado, December 1991 & January 1992
62064)    delray beach    ['florida', 'delray beach']-------------------Live "Erny's", Delray Beach, Florida
62199)    volendam    ['weesp', 'volendam', 'the hague']-------------------Weesp, Volendam, The Hague
62575)    nemuro    ['hokkaido', 'nemuro']-------------------Live "Nemuro Shimin Kaikan", Hokkaido, Japan
62785)    mannheim    ['hannover', 'mannheim', 'berlin']-------------------Live concerts in Berlin, Mannheim & Hannover, c. mid 1980's
62911)    edwardsville    ['illinois', 'edwardsville']-------------------"University of Southern Illinois", Edwardsville, Ill.
62918)    wayne    ['santa monica', 'wayne']-------------------Wayne Stahnke's house, Santa Monica, CA
62985)    kenmore    ['boston', 'kenmore']-------------------3 Broadcasts, "Hotel Kenmore", Boston
63118)    lewiston    ['lewiston', 'maine']-------------------Lewiston, Maine
63282)    godfrey    ['godfrey', 'new york']-------------------"Arthur Godfrey Time", Radio broadcast, CBS, New York
63867)    schiedam    ['holland', 'schiedam']-------------------Live "Podium", Schiedam, Holland
63889)    el cajon    ['california', 'el cajon']-------------------El Cajon, California, October 1987/January 1988
64475)    zion    ['zion', 'new orleans']-------------------Zion Hill Baptist Church, New Orleans
64728)    wageningen    ['holland', 'wageningen']-------------------Wageningen, Holland
65305)    paramount    ['hollywood', 'paramount']-------------------Paramount short film soundtrack, Hollywood, 1934
65735)    cambridge    ['riverside', 'pennsylvania', 'cambridge', 'springs']-------------------Live "Riverside Inn", Cambridge Springs, Pennsylvania
65800)    uithoorn    ['uithoorn', 'amsterdam', 'utrecht']-------------------Live at Uithoorn, Amsterdam & Utrecht, September 14-17, 1977
66413)    menlo park    ['menlo park', 'berlin']-------------------Menlo Park CA, Nov 10, 1986, Ljublijana, May 25/87, Berlin
66978)    minden    ['minden', 'ontario']-------------------Canadian Blues and Jazz Festival, Minden, Ontario, Canada
66998)    nice    ['los angeles', 'nice']-------------------Los Angeles & Nice, France, c. 1964
67081)    pescara    ['pescara', 'esplanada']-------------------"Esplanada Club", Pescara, Italy
67081)    esplanada    ['pescara', 'esplanada']-------------------"Esplanada Club", Pescara, Italy
67176)    colombes    ['paris', 'colombes']-------------------Live "La Salle de Spectacles de Colombes", Paris, France
67510)    staten island    ['staten island', 'new york']-------------------CBS Radio, "Pabst Blue Ribbon Show", Staten Island, New York
67688)    superior    ['superior', 'wisconsin']-------------------Radio broadcast, "Wisconsin State College", Superior, Wisc.
67761)    clearwater    ['florida', 'clearwater']-------------------Royal Coach Hotel, Clearwater, Florida
67787)    dixon    ['dixon', 'new orleans']-------------------"Dixon Hall", New Orleans
67847)    schwabach    ['schwabach', 'stuttgart']-------------------Stuttgart & Schwabach, April 1976 to July 1979
67915)    hamamatsu    ['hamamatsu', 'shizuoka']-------------------Live "Hamamatsu Grand Hotel", Shizuoka
68047)    lexington    ['texas', 'lexington']-------------------Concert, Lexington, Texas
68108)    lugano    ['lugano', 'montreux']-------------------Lugano, July 5 & Montreux, July 24, 1983

68635)    berwyn    ['illinois', 'berwyn']-------------------Live "Fitzgerald's", Berwyn, Illinois, c. 1985
68939)    el paso    ['texas', 'el paso']-------------------El Paso, Texas, February 16-21, 1993
69186)    tonk    ['tonk', 'dendermonde']-------------------Live "Honky Tonk Jazz Club", Dendermonde
69186)    dendermonde    ['tonk', 'dendermonde']-------------------Live "Honky Tonk Jazz Club", Dendermonde
69873)    bowling green    ['bowling green', 'ohio']-------------------Bowling Green State University, Bowling Green, Ohio
71841)    nagoya    ['nice', 'nagoya']-------------------Live "So Nice", Nagoya, Japan
72015)    bethesda    ['maryland', 'bethesda']-------------------Bethesda, Maryland, March 6 & 20, 1971
72097)    harlingen    ['texas', 'harlingen']-------------------"Victory Parade of Spotlight Bands", Harlingen AFB, Texas
72269)    redondo beach    ['redondo beach', 'california']-------------------Redondo Beach, California
72365)    carmel    ['carmel', 'california']-------------------Carmel Highlands, California
72590)    independence    ['independence', 'missouri']-------------------Independence, Missouri
73123)    west new york    ['new jersey', 'west new york']-------------------West New York, New Jersey
73553)    dumont    ['new york', 'dumont']-------------------"Cavalcade of Bands Show", Dumont Network, New York
73575)    ithaca    ['new york', 'ithaca']-------------------Concert "Bailey Hall", Cornell University, Ithaca, New York
73639)    lincoln park    ['lincoln park', 'new bedford']-------------------NBC Broadcast, Lincoln Park, New Bedford, Mass.
73639)    new bedford    ['lincoln park', 'new bedford']-------------------NBC Broadcast, Lincoln Park, New Bedford, Mass.
73727)    ukiah    ['california', 'ukiah']-------------------Country Fair building, Ukiah, California
73793)    brant    ['brant', 'ontario', 'burlington']-------------------Broadcast, "Brant Inn", Burlington, Ontario, Canada
73805)    young    ['young', 'utah', 'provo']-------------------"De Jong Concert Hall" Brigham Young University, Provo, Utah
73806)    fairfield    ['surrey', 'fairfield']-------------------Concert "Fairfield Hall", Croydon, Surrey, England
73838)    veghel    ['holland', 'veghel']-------------------"Blauwe Kei", Veghel, Holland
73840)    palatine    ['palatine', 'harper']-------------------"Student Center" William Rainey Harper College, Palatine, Il
73840)    harper    ['palatine', 'harper']-------------------"Student Center" William Rainey Harper College, Palatine, Il
74447)    corcoran    ['washington, d.c.', 'corcoran']-------------------Concert "Corcoran Gallery of Art", Washington, D.C.
74820)    chapel hill    ['chapel hill', 'north carolina']-------------------Live University of North Carolina, Chapel Hill
75181)    wuppertal    ['wuppertal', 'berlin']-------------------Berlin, November 1978 & Wuppertal, December 1978
75226)    la crosse    ['wisconsin', 'la crosse']-------------------Live "The Place of Jazz", La Crosse, Wisconsin
75311)    westend    ['westend', 'zurich']-------------------"Theater Westend", Zurich, Switzerland, October 22-24, 1990
75332)    santa tecla    ['santa tecla', 'mila']-------------------Live "Santa Tecla", Milan, Italy
75564)    kawasaki    ['kanagawa', 'kawasaki']-------------------Kawasaki, Kanagawa, August-October 26, 1989
75907)    drensteinfurt    ['berlin', 'drensteinfurt']-------------------Live "Floz", Berlin, January 29 & Drensteinfurt, May 5, 1981
76174)    willoughby    ['willoughby', 'lakeland']-------------------Lakeland Community College, Summer Jazz Camp, Willoughby, OH
76174)    lakeland    ['willoughby', 'lakeland']-------------------Lakeland Community College, Summer Jazz Camp, Willoughby, OH
76253)    methuen    ['massachusetts', 'methuen']-------------------Methuen Memorial Music Hall, Methuen, Massachusetts
76273)    brenham    ['texas', 'brenham']-------------------Brenham, Texas
76372)    racine    ['racine', 'wisconsin']-------------------Radio broadcast, "Spotlight Bands", Racine, Wisconsin
76375)    clovis    ['clovis', 'new mexico']-------------------AFRS broadcast, Clovis Army Air Field, New Mexico
77163)    costa mesa    ['los angeles', 'costa mesa']-------------------Los Angeles & Costa Mesa, CA, February 28-April 9, 1994
77512)    rockland    ['new york', 'rockland']-------------------New York, Southbury Conn., Rockland County NY, 1982
77961)    castelli    ['new york', 'castelli']-------------------Live "Leo Castelli Gallery", New York
77990)    acton    ['london', 'acton']-------------------White Hart, Acton, London, early 1958
78015)    pinner    ['london', 'pinner']-------------------Pinner, London, 1968
78050)    blenheim    ['london', 'blenheim']-------------------18 Blenheim Road, Chiswick, London
78276)    wenatchee    ['wenatchee', 'washington']-------------------Wenatchee, Washington, October 21 & 24, 1984
78449)    hackensack    ['hackensack', 'new jersey']-------------------Hackensack, New Jersey
78451)    cranbrook    ['detroit', 'cranbrook']-------------------Concert, Cranbrook Academy of Art, Detroit
79012)    moore    ['moore', 'new york']-------------------Broadcast "Gary Moore Show", New York
79805)    santa barbara    ['los angeles', 'santa barbara']-------------------Los Angeles & Santa Barbara, CA
79976)    oxford    ['miami', 'oxford', 'ohio']-------------------Miami University, Oxford, Ohio
79982)    benton    ['benton', 'oxford', 'ohio']-------------------Concert (first half), "Benton Hall", Oxford, Ohio
80818)    harburg    ['harburg', 'hamburg']-------------------Hamburg, Harburg, Germany
80858)    stoughton    ['stoughton', 'massachusetts']-------------------Stoughton, Massachusetts
80932)    bergenfield    ['texas', 'bergenfield', 'flower mound']-------------------Flower Mound, Texas & Bergenfield, N.J.
81157)    alice    ['alice', 'new york', 'lincoln']-------------------Alice Tully Hall, Lincoln Center, New York
81744)    slidell    ['slidell', 'new orleans']-------------------Slidell, New Orleans, La.
82207)    butte    ['butte', 'montana']-------------------"Hotel Finlen", Butte, Montana
82549)    algiers    ['louisiana', 'algiers']-------------------Live "Hope Hall", Algiers, Louisiana
82788)    pittsburg    ['pennsylvania', 'pittsburg']-------------------Pittsburg, Pennsylvania, October 28 & November 5, 1979

83458)    honolulu    ['hawaii', 'honolulu']-------------------Honolulu, Hawaii, June & July, 1981
83706)    lausanne    ['geneva', 'lausanne']-------------------Geneva or Lausanne, c. 1990
83916)    ashland    ['west virginia', 'ashland', 'huntington', 'kentucky']-------------------Ashland Kentucky August 13, 1989 & Huntington, West Virginia
83916)    huntington    ['west virginia', 'ashland', 'huntington', 'kentucky']-------------------Ashland Kentucky August 13, 1989 & Huntington, West Virginia
83997)    johannesburg    ['johannesburg', 'brussels']-------------------Johannesburg & Brussels
84072)    lindau    ['lindau', 'zurich']-------------------Lindau, Zurich, Switzerland, February 5 & 6, 1980
84132)    catania    ['sicily', 'catania']-------------------Catania, Sicily
84133)    pozzallo    ['pozzallo', 'siracusa']-------------------Siracusa, June 12, 1992 & Pozzallo, July 23 & 24, 1992
84133)    siracusa    ['pozzallo', 'siracusa']-------------------Siracusa, June 12, 1992 & Pozzallo, July 23 & 24, 1992
84426)    nazareth    ['rochester', 'nazareth']-------------------Live "Nazareth College", Rochester, N.Y.
85253)    bochum    ['cologne', 'bochum']-------------------Cologne & Bochum, West Germany
85267)    anderson    ['anderson', 'new york', 'binghamton']-------------------"Anderson Center", Binghamton, New York
85267)    binghamton    ['anderson', 'new york', 'binghamton']-------------------"Anderson Center", Binghamton, New York
85312)    mineola    ['new york', 'mineola']-------------------Mineola, New York, October & November 1992
85389)    lakeside    ['stamford', 'lakeside', 'new york']-------------------New York, Stamford, CT, Lakeside, CT
85517)    vernon    ['vernon', 'new orleans']-------------------Live "Vernon's Supper Club", New Orleans, 1956-1966
85519)    rogers    ['rogers', 'new orleans']-------------------Myra Clare Rogers Memorial Chapel, New Orleans, LA
85645)    compton    ['los angeles', 'compton']-------------------Live "Compton Community College", Los Angeles
85648)    angeles city    ['los angeles', 'angeles city']-------------------Live "Los Angeles City College", Los Angeles
85831)    stow    ['massachusetts', 'stow']-------------------Stow, Massachusetts
85896)    aachen    ['bonn', 'aachen']-------------------Aachen, March 7, 1982 & Bonn, March 8, 1982
86023)    deerfield beach    ['florida', 'deerfield beach']-------------------Deerfield Beach, Florida
86711)    irvington    ['new york', 'irvington']-------------------Irvington, New York
86777)    milano    ['milano', 'magna']-------------------Live "Aula Magna di l'Universita Statale di Milano", Milan
86793)    durham    ['durham', 'new hampshire']-------------------Live "University of New Hampshire", Durham, New Hamphire
86795)    brookline    ['maine', 'brookline']-------------------Brookline, Maine
87121)    purley    ['surrey', 'purley']-------------------Concert "Wattenden School", Purley, Surrey, England
87506)    edina    ['minnesota', 'edina']-------------------Edina, Minnesota
87532)    palermo    ['sicily', 'palermo']-------------------Palermo, Sicily, Italy
87609)    saint paul    ['saint paul', 'strasbourg']-------------------Church of Saint Paul, "Musica Festival", Strasbourg, Germany
87609)    strasbourg    ['saint paul', 'strasbourg']-------------------Church of Saint Paul, "Musica Festival", Strasbourg, Germany
87819)    yakima    ['yakima', 'washington']-------------------Yakima, Washington
88224)    seminole    ['florida', 'seminole']-------------------Seminole, Florida
88718)    el dorado    ['el dorado', 'arkansas']-------------------prob El Dorado, Arkansas, June 1 & 2, 1984
88763)    norwalk    ['norwalk', 'connecticut']-------------------Norwalk, Connecticut
88787)    enterprise    ['burbank', 'enterprise']-------------------"The Pit", Reseda, CA/"The Enterprise", Burbank, early 90's
89136)    gallatin    ['gallatin', 'tennessee']-------------------Gallatin, Tennessee
89320)    pensacola    ['florida', 'pensacola']-------------------Pensacola, Florida
89360)    lafayette    ['indiana', 'lafayette']-------------------Live "Arnie's Market Square Lounge", Lafayette, Indiana
89371)    indianapolis    ['anderson', 'indianapolis']-------------------Live, (*) Anderson & Indianapolis, Indiana
89819)    ludwigsburg    ['cologne', 'ludwigsburg']-------------------Cologne, Germany, June 1980 & Ludwigsburg, July 1983
90175)    valley stream    ['new york', 'valley stream']-------------------Valley Stream, New York
90460)    sun valley    ['hollywood', 'sun valley']-------------------"Sun Valley Serenade" * , Hollywood, March 24 - May 3, 1941
90501)    schenectady    ['schenectady', 'chesterfield', 'new york']-------------------CBS Broadcast "Chesterfield Show", Schenectady, New York
90552)    rockford    ['chesterfield', 'rockford']-------------------CBS Broadcast "Chesterfield Show", Camp Grant, Rockford, Ill
90798)    osaka    ['tokyo', 'osaka']-------------------Osaka and Tokyo, Japan
91423)    boulogne-billancourt    ['boulogne-billancourt', 'paris']-------------------Concert "Theatre Boulogne-Billancourt", Paris, France
91467)    badger    ['badger', 'bournemouth']-------------------Live "The Badger", Bournemouth
91467)    bournemouth    ['badger', 'bournemouth']-------------------Live "The Badger", Bournemouth
91593)    hueytown    ['hueytown', 'alabama']-------------------Hueytown, Alabama
92094)    montgomery    ['montgomery', 'alabama']-------------------James Field's barn, Montgomery, Alabama, 7-10 pm
92435)    beloit    ['beloit', 'wisconsin']-------------------prob. Beloit, Wisconsin, c. late 1980s ?
92695)    billings    ['billings', 'montana']-------------------Live "The Stock Exchange", Billings, Montana
92740)    cedar rapids    ['iowa', 'cedar rapids']-------------------Live "The Tender Trap Club", Cedar Rapids, Iowa
92741)    rock island    ['illinois', 'rock island']-------------------Rock Island, Illinois
92799)    amstelveen    ['holland', 'amstelveen', 'amsterdam']-------------------Live "Bajes Club", Amstelveen, Amsterdam, Holland
92823)    southfield    ['southfield', 'michigan']-------------------Southfield, Michigan
92994)    glen cove    ['glen cove', 'mineola']-------------------Mineola & Glen Cove, N.Y.

93379)    montclair    ['montclair', 'jackson']-------------------Live "Montclair Supper Club", Jackson Heights, IL, late 1955
93620)    tajimi    ['tajimi', 'gifu']-------------------Live "Studio F", Tajimi, Gifu
94213)    buffalo grove    ['illinois', 'buffalo grove']-------------------Buffalo Grove, Illinois
94248)    santos    ['concord', 'santos']-------------------Live "Todos Santos Plaza", Concord, CA
94259)    marks    ['marks', 'new york']-------------------Concert St. Marks Church, New York
94578)    pulheim    ['cologne', 'pulheim']-------------------Cologne & Pulheim, Germany, November 1988 - January 1989
94806)    stockton    ['california', 'stockton']-------------------Concert "Stockton High School", California
94807)    hoover    ['san diego', 'hoover']-------------------Concert "Hoover High School", San Diego, CA
95348)    willimantic    ['connecticut', 'willimantic']-------------------Willimantic, Connecticut, spring 1992
95535)    north miami    ['florida', 'north miami']-------------------North Miami, Florida
95650)    sopot    ['sopot', 'george']-------------------St. George's Church, Sopot
96035)    st. john's    ["st. john's", 'london']-------------------St. John's Wood, London
96072)    medford    ['medford', 'massachusetts']-------------------Live "Paige Hall, Tutts University", Medford, Massachusetts
96095)    tempe    ['arizona', 'tempe']-------------------Tempe, Arizona, May 16 & 17, 1994
96236)    preston    ['los angeles', 'preston']-------------------Don Preston's basement, Los Angeles
96300)    derby    ['derby', 'melbourne']-------------------Live, Harding Arms, Melbourne, Derby, England
96301)    newton    ['derby', 'newton']-------------------Live, Kings Newton near Derby, England
96380)    acireale    ['acireale', 'terme']-------------------Live, Parco Delle Terme s. Venera Acireale, Italy
96380)    terme    ['acireale', 'terme']-------------------Live, Parco Delle Terme s. Venera Acireale, Italy
96412)    celle    ['hannover', 'celle']-------------------Live "Jazzclub Hannover", Celle
96533)    gretna    ['pennsylvania', 'gretna']-------------------Live "The Playhouse", Mount Gretna, Pennsylvania
96544)    kerkrade    ['holland', 'kerkrade']-------------------Live, Kerkrade, Holland
96548)    maastricht    ['holland', 'maastricht']-------------------Live, Maastricht, Holland
96554)    jamaica plain    ['jamaica plain', 'pennsylvania']-------------------Jamaica Plain, Pennsylvania
96864)    shiroi    ['shiroi', 'kobe']-------------------Live "Shiroi Ijinken", Kobe
96864)    kobe    ['shiroi', 'kobe']-------------------Live "Shiroi Ijinken", Kobe
97149)    lacey    ['lacey', 'washington']-------------------Film soundtrack, Lacey, Washington
97562)    whitley bay    ['whitley bay', 'high point']-------------------Live "High Point Hote", Whitley Bay
97580)    fort wayne    ['indiana', 'fort wayne']-------------------Fort Wayne, Indiana, c. 1967
97829)    sunrise    ['connecticut', 'sunrise']-------------------Sunrise Resort, Moodus, Connecticut
97908)    stratford    ['stratford', 'ontario']-------------------Stratford, Ontario
97998)    plainfield    ['plainfield', 'new jersey']-------------------Plainfield, New Jersey
98102)    addison    ['illinois', 'addison']-------------------Addison, Illinois
98112)    shimoda    ['shimoda', 'shizuoka']-------------------Live "Chieshah Cat", Shimoda, Shizuoka
98172)    huizen    ['huizen', 'holland']-------------------Live at De Boerderij, Huizen, Holland
98346)    spoleto    ['charleston', 'spoleto']-------------------Live "Spoleto Festival", Charleston, 1977
98585)    danvers    ['carlisle', 'danvers']-------------------Danvers & Carlisle, Mass.
98606)    woodland    ['woodland', 'milwaukee', 'wisconsin']-------------------Live "Woodland Pattern", Milwaukee, Wisconsin
98735)    hoffman estates    ['hoffman estates', 'illinois']-------------------Hoffman Estates, Illinois, August 30 - September 1, 1992
99623)    la victoria    ['boston', 'la victoria']-------------------"Villa Victoria Cultural Center", Boston, MA
99684)    sartrouville    ['sartrouville', 'paris']-------------------Live "Le Theatre de Sartrouville", Paris
100074)    uster    ['uster', 'zurich']-------------------Cinema Central, Uster, Zurich
100344)    beverley    ['los angeles', 'beverley']-------------------Live "Beverley Cavern", Los Angeles, 1949
100513)    bear    ['bear', 'san francisco']-------------------Live "Bear Cave", San Francisco, CA, January-June 1990
100608)    hobart    ['tasmania', 'hobart']-------------------Hobart, Tasmania
101400)    athens    ['athens', 'george']-------------------Live "George Barakos Jazz Club", Athens
101609)    texarkana    ['arkansas', 'texarkana']-------------------Live "Embers Restaurant", Texarkana, Arkansas
101735)    framingham    ['boston', 'framingham']-------------------Live "Christy's", Framingham, Boston, MA
101747)    altadena    ['california', 'altadena']-------------------Zorathian's Ranch, Altadena, California
101956)    huntington station    ['new york', 'huntington station']-------------------Huntington Station, New York, prob. late 1950's
102128)    woonsocket    ['rhode island', 'woonsocket']-------------------Live "Chan's", Woonsocket, Rhode Island, c. 1985
102516)    riccione    ['venice', 'mila', 'naples', 'riccione', 'rome']-------------------Live, Naples, Riccione, Rome, Milan & Venice
102555)    ferguson    ['tuscaloosa', 'ferguson', 'alabama']-------------------"Ferguson Theatre", University of Alabama, Tuscaloosa, Ala.
102949)    kawaguchi    ['saitama', 'kawaguchi']-------------------Kawaguchi, Saitama, Japan, February 4 & 5, 1970
103242)    taunton    ['taunton', 'plymouth']-------------------(*) Plymouth, March 10, 1991 & (#) Taunton, March 11, 1991
103242)    plymouth    ['taunton', 'plymouth']-------------------(*) Plymouth, March 10, 1991 & (#) Taunton, March 11, 1991

103401)    abashiri    ['abashiri', 'hokkaido']-------------------Concert "Abashiri-Shimin-Kaikan", Abashiri, Hokkaido, Japan
103470)    mississauga    ['mississauga', 'ontario']-------------------Mississauga, Ontario, 1991 & 1992
103965)    zutphen    ['holland', 'zutphen']-------------------Live, Debarak, Zutphen, Holland
103982)    aloha    ['oregon', 'aloha']-------------------Aloha, Oregon
104694)    wilkes-barre    ['wilkes-barre', 'pennsylvania']-------------------Wilkes University, Wilkes-Barre, Pennsylvania
104704)    dover    ['concord', 'dover']-------------------Dover, Mass, Nov. 1 & 15 and Concord, Mass, Dec. 5, 1976
105122)    newberg    ['newberg', 'oregon', 'washington', 'seattle']-------------------Seattle, Washington and Newberg, Oregon
105449)    lawrence    ['lawrence', 'appleton']-------------------Lawrence University, Appleton, WI, July 25 & 26, 1995
105450)    oshkosh    ['oshkosh', 'wisconsin']-------------------Grand Theatre, Oshkosh, Wisconsin
105531)    macclesfield    ['london', 'macclesfield']-------------------"Premises", London & "Ascension", Macclesfield
106127)    sidney    ['sidney', 'oregon', 'portland']-------------------Live "Sidney's Club", Portland, Oregon
107179)    longueuil    ['quebec', 'longueuil']-------------------Longueuil, Quebec, April & May 1993
107601)    kehl    ['kehl', 'frankfurt']-------------------Live "Ste Georgen/Kehl/Frankfurt, September 27-29, 1989
107740)    ajax    ['ajax', 'ontario']-------------------Ajax, Ontario
107918)    arvada    ['colorado', 'denver', 'arvada']-------------------Concert, Arvada, Denver, Colorado
108563)    long branch    ['west end', 'long branch']-------------------"West End Casino", Long Branch, N.J.
109127)    westmont    ['santa barbara', 'westmont']-------------------"Porter Hall", Westmont College, Santa Barbara, CA
109150)    nashua    ['nashua', 'new hampshire']-------------------Nashua, New Hampshire, November 19 & 20, 1994
109489)    wethersfield    ['connecticut', 'wethersfield']-------------------Wethersfield, Connecticut
110013)    east orange    ['east orange', 'new york']-------------------East Orange, NJ & New York
110234)    neunkirchen    ['neunkirchen', 'berlin']-------------------Neunkirchen, July 1975 & Berlin, October, 1975
110285)    morganton    ['caldwell', 'morganton']-------------------Gamewell or Morganton, Caldwell County, N.C., summer 1956
110422)    heidelberg    ['ludwigsburg', 'heidelberg']-------------------Concert, Heidelberg, May 13 & Ludwigsburg, May 14, 1970
110656)    golden valley    ['minnesota', 'golden valley']-------------------Golden Valley, Minnesota, February 19 & August 20, 1995
110979)    urbana    ['urbana', 'illinois']-------------------Urbana, Illinois
111015)    oshawa    ['oshawa', 'ontario']-------------------"Jubilee Ballroom", Oshawa, Ontario
111030)    phoenixville    ['pennsylvania', 'phoenixville']-------------------AFRS Spotlight Bands 785, (*), Phoenixville, Pennsylvania
111431)    amiens    ['cologne', 'amiens']-------------------Cologne, Jan 1989, Vandoeuvres, July 1989 & Amiens, Jan 1991
111532)    milford    ['connecticut', 'milford']-------------------Milford, Connecticut
111547)    gorinchem    ['holland', 'gorinchem']-------------------Live, Gorinchem, Holland
112008)    deland    ['florida', 'deland']-------------------Cafe Da Vinci, Deland, Florida
112012)    daytona beach    ['florida', 'daytona beach']-------------------Cafe Bravo, Daytona Beach, Florida
112125)    bobigny    ['paris', 'bobigny']-------------------Concert, (*), Bobigny, Paris, France
112294)    franklin square    ['new york', 'franklin square']-------------------Franklin Square, New York
112557)    craiova    ['craiova', 'moscow', 'riga']-------------------Concerts, Moscow, Russia; Riga, Latvia; Craiova, Romania
112817)    overijse    ['overijse', 'brussels']-------------------Overijse (near Brussels), September 7 & 8, 1991
114058)    helmond    ['holland', 'helmond']-------------------Helmond, Holland
114574)    marseille    ['marseille', 'paris', 'mila']-------------------Paris, Marseille & Milan, October/November 1982
114646)    farmington    ['farmington', 'michigan']-------------------Farmington, Michigan, 1974
114704)    tampere    ['tampere', 'zurich']-------------------Tampere Jazz Happening & The Int'l Jazz Festival, Zurich
114758)    east providence    ['rhode island', 'east providence']-------------------Live "Bovi's Town Tavern", East Providence, Rhode Island
114837)    dedham    ['massachusetts', 'dedham']-------------------Live "Domino Club", Dedham, Massachusetts, 1960's
115154)    elkhart    ['indiana', 'elkhart']-------------------Elkhart, Indiana
115273)    elmhurst    ['elmhurst', 'kentucky']-------------------Live "Elmhurst College Jazz Festival", Kentucky
115347)    eau claire    ['eau claire', 'wisconsin']-------------------Gantner Auditorium, UW-Eau Claire, Wisconsin
116445)    tustin    ['costa mesa', 'tustin']-------------------LA, Tustin & Costa Mesa, CA, c. 1990
116883)    carthage    ['los angeles', 'carthage', 'franklin', 'nashville']-------------------Nashville, Franklin, Carthage, TN & Los Angeles
116992)    sioux city    ['iowa', 'sioux city']-------------------(*), Concert, Sioux City, Iowa, February 7 & 8, 1997
117117)    parnas    ['prague', 'parnas']-------------------Live "Parnas Club", Prague, May 20, 21 & 22, 1980
117755)    carouge    ['geneva', 'carouge']-------------------Restaurant, "Belle Epoque", Carouge/Geneva
118447)    mainz    ['mainz', 'new castle']-------------------New Jazz Meeting, New Castle, Mainz, Germany
118447)    new castle    ['mainz', 'new castle']-------------------New Jazz Meeting, New Castle, Mainz, Germany
118910)    aberdeen    ['maryland', 'aberdeen']-------------------AFRS Spotlight Bands #280, Aberdeen, Maryland

118962)    arlington    ['arlington', 'potomac']-------------------Live, Potomac River Jazz Club, Marriott Hotel, Arlington, VA
119081)    urayasu    ['urayasu', 'tokyo']-------------------Live "Urayasu Shimin-Kaikan", Tokyo, Japan
119088)    yerres    ['marseille', 'yerres']-------------------Yerres/Marseille, France, November 14 & 15, 1988
119227)    college park    ['maryland', 'college park']-------------------Live, College Park, Maryland
119765)    perugia    ['umbria', 'perugia']-------------------Live "Umbria Jazz Festival", Perugia, Italy
120273)    ancaster    ['ancaster', 'ontario']-------------------Ancaster, Ontario
120472)    naha    ['seoul', 'naha', 'tokyo']-------------------Seoul, Korea & Naha, Tokyo, June-August 1995
121425)    ribera    ['ribera', 'new mexico']-------------------Ribera, New Mexico, December 9 & 10, 1996
121998)    laurel    ['laurel', 'maryland']-------------------Live "Montpelier Cultural Arts Center", Laurel, Maryland
122248)    hawthorne    ['country club', 'hawthorne', 'dartmouth']-------------------Live "Hawthorne Country Club", Dartmouth, MA
122286)    kreuzberg    ['kreuzberg', 'berlin']-------------------West Berlin-Kreuzberg, Germany, June 13-17, 1990
122353)    pasing    ['pasing', 'munich']-------------------Munich-Pasing
122571)    keswick    ['alhambra', 'keswick']-------------------Live "Alhambra Cinema", Keswick
122725)    northampton    ['chicago', 'northampton']-------------------Chicago, IL & Northampton, MA, July & November 1998
122805)    cheltenham    ['cheltenham', 'mary']-------------------St. Mary's Church, Cheltenham
123014)    norton    ['buffalo', 'norton']-------------------Norton Student Union, NY State University, Buffalo, N.Y.
123018)    bucharest    ['bucharest', 'americana']-------------------Biblioteca Americana, Bucharest
123075)    ewell    ['surrey', 'ewell']-------------------Ewell, Surrey
124057)    tourcoing    ['groningen', 'tourcoing']-------------------Groningen, October 13, 1995 & Tourcoing December 1, 1995
124068)    wigan    ['stockport', 'wigan']-------------------Stockport & Wigan, November 1993 & January 1994
124106)    tiffin    ['ohio', 'tiffin']-------------------Ritz Theatre, Tiffin, Ohio
124197)    toulouse    ['toulouse', 'blagnac']-------------------Toulouse-Blagnac, France, July 7, 8 & 9, 1999
124197)    blagnac    ['toulouse', 'blagnac']-------------------Toulouse-Blagnac, France, July 7, 8 & 9, 1999
124424)    tulsa    ['oklahoma', 'tulsa']-------------------Tulsa, Oklahoma
124742)    edison    ['new york', 'edison']-------------------Edison Studios, New York
124876)    leigh    ['leigh', 'birmingham']-------------------Live "Leigh Gallery", Birmingham, Alambama
125091)    atwater    ['atwater', 'portland']-------------------Live "Atwater's", Portland, OR
125775)    havana    ['london', 'havana']-------------------Havana & London, summer 1999
126180)    villa park    ['villa park', 'illinois']-------------------Live, Villa Park, Illinois, summer 1977
127093)    bloomfield    ['connecticut', 'bloomfield']-------------------Bloomfield, Connecticut
127335)    parker    ['parker', 'carnegie', 'new york']-------------------Live, Charlie Parker Memorial, "Carnegie Hall", New York
127358)    cary    ['geneva', 'woodstock', 'cary']-------------------Woodstock, N.Y., Lake Geneva, Wisc., & Cary Bluff, c. 1981
127711)    detmold    ['holland', 'detmold', 'anta']-------------------Live "Detmold, Neue Anta, Holland
127922)    brixton    ['brixton', 'london', 'acton']-------------------Acton, London & Brixton, London 1984-85
128467)    roth    ['roth', 'nurnberg']-------------------Live "Kulturfabrik Roth", Nurnberg, Germany
128521)    shirley    ['shirley', 'new orleans']-------------------Live "Crazy Shirley's", New Orleans, c. 1980's ?
128591)    salamanca    ['salamanca', 'gifu']-------------------Salamanca Hall, Gifu, April 23 & 24, May 20 & 21, 1997
128598)    sapporo    ['sapporo', 'hokkaido']-------------------Sapporo, Hokkaido, August 9-11, 1994
129263)    bremerhaven    ['bremen', 'bremerhaven', 'paderborn']-------------------Live, Bremen, Bremerhaven & Paderborn, Germany
129263)    paderborn    ['bremen', 'bremerhaven', 'paderborn']-------------------Live, Bremen, Bremerhaven & Paderborn, Germany
129437)    forest hills    ['new york', 'forest hills']-------------------Forest Hills, New York
130044)    evans    ['paris', 'evans']-------------------Studio Gil Evans, Paris, France ?, December 16-21, 1995
130168)    marktoberdorf    ['marktoberdorf', 'berlin']-------------------Marktoberdorf & Berlin, March 14 & 16, 1989
130246)    skien    ['oslo', 'skien']-------------------Oslo & Skien, October & December 2001 and August 2002
130289)    sendai    ['sendai', 'miyagi']-------------------Live "Sendai, Tokoku University, Kyoyobu", Miyagi
130317)    muroran    ['muroran', 'hokkaido']-------------------"Dee Dee" Muroran, Hokkaido
130354)    mumbai    ['crete', 'mumbai', 'athens']-------------------Athens, Crete, Greece & Mumbai, India, Sept 1999-Sept 2000
130418)    stavanger    ['oslo', 'stavanger']-------------------Live "Stavanger Jazzclub", Oslo
130506)    colinas    ['dallas', 'colinas']-------------------Dallas, Las Colinas & Wylie, TX
130552)    brisbane    ['brisbane', 'san francisco']-------------------San Francisco & Brisbane, CA
130884)    palma    ['rome', 'palma']-------------------Live "La Palma Jazz Club", Rome, April 24, 25 & 26, 2002
131062)    murray    ['new york', 'murray']-------------------Ken Murray TV Show, New York City
131630)    edgewater    ['florida', 'edgewater']-------------------Edgewater, Florida, January & February 1974
132587)    brugge    ['brugge', 'amsterdam', 'brussels']-------------------Brussels, Brugge & Amsterdam
132907)    gardner    ['gardner', 'washington']-------------------radio broadcast, Gardner Field, Washington
132924)    winter garden    ['new york', 'winter garden']-------------------NBC radio broadcast, Winter Garden Theatre, New York
132963)    palm springs    ['crosby', 'palm springs']-------------------"The Bing Crosby Show", Palm Springs, poss. ca. Feb., 1951
133034)    medina    ['chicago', 'medina']-------------------concert, "Medina Temple", Chicago
133101)    pottstown    ['pottstown', 'pennsylvania']-------------------Broadcast, Pottstown, Pennsylvania, June 1961
133126)    sandusky    ['ohio', 'sandusky']-------------------Broadcast, Upper Sandusky, Ohio
133137)    fort hood    ['texas', 'fort hood']-------------------ABC-TV show "Operation Entertainment", Fort Hood, Texas
133161)    corona    ['corona', 'new york']-------------------Corona, New York
133413)    dekalb    ['illinois', 'dekalb']-------------------Northern Illinois University (NIU), DeKalb, IL
133436)    tarragona    ['tarragona', 'el vendrell']-------------------El Vendrell, Tarragona
133436)    el vendrell    ['tarragona', 'el vendrell']-------------------El Vendrell, Tarragona
133537)    izumo    ['shimane', 'izumo']-------------------Live "Izumo Shiminkaikan", Shimane, January 25 & 26, 1995
133948)    szentendre    ['szentendre', 'budapest', 'nagykanizsa', 'gyor']-------------------Live (*), Gyor, Budapest, Szentendre & Nagykanizsa

133948)    nagykanizsa    ['szentendre', 'budapest', 'nagykanizsa', 'gyor']-------------------Live (*), Gyor, Budapest, Szentendre & Nagykanizsa
134076)    princeton    ['boston', 'princeton']-------------------Princeton, N.J., summer 2000 & Boston, MA, November 18, 2000
134232)    downey    ['downey', 'morton']-------------------radio broadcast, "Morton Downey Show", Spring 1951
134835)    collingwood    ['melbourne', 'collingwood']-------------------Collingwood Football Club, Melbourne, May 5, 6 & 7, 2000
135768)    nassau    ['paradise', 'nassau']-------------------La Cabaret Casino, Paradise Island, Nassau, Bahamas
136127)    greenwood    ['new york', 'greenwood']-------------------Greenwood Lake & New York City, NY
136463)    vulcan    ['vulcan', 'sydney']-------------------Live "Vulcan Hotel", Sydney
136757)    papeete    ['manica', 'papeete']-------------------Santa Manica, CA & Papeete, Tahiti
137252)    montreuil    ['paris', 'montreuil']-------------------Live (*), Montreuil, Paris, September 22-25, 1994
137447)    canton    ['canton', 'gilbert']-------------------J. Richard Gilbert Recital Hall, Canton, NY
137721)    southsea    ['southsea', 'cambridge']-------------------Live "The Cambridge", Southsea
137801)    eagle    ['london', 'eagle']-------------------Live "Apples & Snakes", The Eagle, Farringdon Road, London
138212)    graz    ['graz', 'karlsruhe', 'kiel', 'aachen', 'nurnberg']-------------------Live in Kiel, Aachen, Karlsruhe, Graz, Nurnberg
138212)    karlsruhe    ['graz', 'karlsruhe', 'kiel', 'aachen', 'nurnberg']-------------------Live in Kiel, Aachen, Karlsruhe, Graz, Nurnberg
138612)    wilsonville    ['oregon', 'wilsonville']-------------------Wilsonville, Oregon, c. 1996
138694)    weiden    ['weiden', 'halle']-------------------Live "Max-Reger-Halle", Weiden in der Oberpfalz, Germany (*)
139280)    lodi    ['mila', 'lodi']-------------------Lodi's Cathedral, Milan, August 29 & 30, 1998
139514)    sulphur    ['springs', 'sulphur']-------------------Spotlight bands broadcast #524, White Sulphur Springs, W.VA
139899)    asia    ['new york', 'asia']-------------------Live "Asia Society", New York
140223)    dresden    ['dresden', 'erfurt']-------------------Concerts, Erfurt, June 18, 1993 & Dresden July 17, 1993
140223)    erfurt    ['dresden', 'erfurt']-------------------Concerts, Erfurt, June 18, 1993 & Dresden July 17, 1993
140265)    beverly hills    ['hollywood', 'beverly hills']-------------------Beverly Hills & Hollywood, CA, c. 1994
140585)    bethany    ['bethany', 'vermont']-------------------Live "Bethany Church", Montpelier, Vermont
140790)    northport    ['maine', 'northport']-------------------Northport, Maine
141041)    canberra    ['canberra', 'sydney']-------------------Concert, Sydney, November 18 and/or Canberra, November, 1978
141065)    burnaby    ['burnaby', 'vancouver']-------------------Burnaby, Vancouver, B.C., October 19 & 20, 2002
141088)    katoomba    ['sydney', 'katoomba']-------------------Live, Katoomba Jazz Festival, Sydney
141493)    coronado    ['coronado', 'st. louis']-------------------NBC radio broadcast, Coronado Hotel, St. Louis, MO
141525)    fargo    ['fargo', 'north dakota', 'crystal']-------------------"Crystal Ballroom", Lake Inn, Fargo, North Dakota
141525)    crystal    ['fargo', 'north dakota', 'crystal']-------------------"Crystal Ballroom", Lake Inn, Fargo, North Dakota
141534)    southgate    ['los angeles', 'southgate']-------------------radio broadcast, Trianon ballroom", Southgate, Los Angeles
141620)    evansville    ['indiana', 'franklin', 'evansville']-------------------ABC Broadcast, "Franklin Gardens", Evansville, Indiana
141679)    golden gate    ['san francisco', 'golden gate']-------------------Broadcast "Golden Gate Theater", San Francisco
141756)    st. thomas    ['copenhagen', 'st. thomas']-------------------"Restaurant St. Thomas", Copenhagen, Denmark
141826)    coeur d'alene    ['idaho', "coeur d'alene"]-------------------Coeur D'Alene, Idaho
142043)    sundbyberg    ['sundbyberg', 'solna', 'stockholm']-------------------Solna-Sundbyberg, near Stockholm, Sweden
142043)    solna    ['sundbyberg', 'solna', 'stockholm']-------------------Solna-Sundbyberg, near Stockholm, Sweden
142217)    cuyahoga falls    ['cuyahoga falls', 'ohio']-------------------Blossom Music Center, Cuyahoga Falls, Ohio
142229)    vasa    ['vasa', 'stockholm']-------------------Gustav Vasa Kyrkan, Stockholm, Sweden
142254)    fontana    ['mila', 'fontana']-------------------Studio Fontana, Milan, Italy
142291)    kenosha    ['eagle', 'wisconsin', 'kenosha']-------------------"Eagle's Ballroom", Kenosha, Wisconsin
142292)    centennial    ['winnipeg', 'centennial']-------------------Concert "Centennial Concert Hall", Winnipeg, Canada
143454)    champaign    ['urbana', 'illinois', 'champaign']-------------------Concert, University of Illinois (*), Urbana-Champaign, IL
143517)    camden town    ['london', 'camden town']-------------------Live, Camden Town Jazz Festival, London, 2002
144057)    david    ['david', 'wales', 'cardiff']-------------------St. David's Hall, Cardiff, Wales
144057)    cardiff    ['david', 'wales', 'cardiff']-------------------St. David's Hall, Cardiff, Wales
144091)    naarden    ['holland', 'naarden']-------------------Naarden-Vesting, Holland
144156)    dunakeszi    ['budapest', 'dunakeszi']-------------------Budapest & Dunakeszi
145070)    penicuik    ['penicuik', 'scotland']-------------------Penicuik, Scotland, April & July 2002
145080)    adler    ['frankfurt', 'adler']-------------------Live "Adler-Werke", Frankfurt
145318)    cypress    ['cypress', 'san francisco']-------------------Live "Cypress Club", San Francisco, CA, c. late 1990's
145534)    worcester    ['worcester', 'piedmont']-------------------Piedmont Center for Arts, Worcester, MA
145578)    repentigny    ['quebec', 'repentigny']-------------------Repentigny, Quebec
145980)    ascheberg    ['dortmund', 'ascheberg']-------------------Live, Dortmund, May 8 and Ascheberg, May 9 & 10, 1981
145988)    welwyn garden city    ['welwyn garden city', 'northampton']-------------------Welwyn Garden City & Northampton, January 28 & 29, 2001
146001)    varese    ['varese', 'malnate']-------------------Varese, July 28 (*), Malnate, Aug 19 (#) & Italy, Sept, 1995
146001)    malnate    ['varese', 'malnate']-------------------Varese, July 28 (*), Malnate, Aug 19 (#) & Italy, Sept, 1995
146016)    meyrin    ['meyrin', 'bellavista']-------------------L'Ecole Bellavista, Meyrin, February 9, 11, 12 & 13, 1996
146016)    bellavista    ['meyrin', 'bellavista']-------------------L'Ecole Bellavista, Meyrin, February 9, 11, 12 & 13, 1996
146374)    lubin    ['lubin', 'new york']-------------------Live "Eisner & Lubin Auditorium", New York University, NYC
146408)    akademgorodok    ['akademgorodok', 'novosibirsk']-------------------Concert "House of Scientists", Akademgorodok, Novosibirsk
146782)    antwerpen    ['antwerpen', 'brussels']-------------------Antwerpen or Brussels
147289)    cheyenne    ['colorado springs', 'cheyenne']-------------------Cheyenne Mtn. High School, Colorado Springs, CO

147791)    pickering    ['ontario', 'pickering']-------------------Pickering, Ontario, June 13 & 14, 2001
147856)    almelo    ['holland', 'almelo']-------------------Theehuis Beeklust, Almelo, Holland
147953)    hialeah    ['florida', 'hialeah']-------------------Hialeah, Florida, February 21, 1994 and April 18 & 19, 1994
148022)    marquette    ['marquette', 'wisconsin']-------------------Varsity Theatre, Marquette University, Marquette, Wisconsin
148229)    minato    ['minato', 'yokohama']-------------------Live "Yokohama Minato Mirai Hall", Yokohama, Japan
148365)    redwood city    ['los altos', 'redwood city']-------------------Los Altos Hills, CA & Redwood City  CA
148601)    logan    ['london', 'logan']-------------------Live "Logan Hall", London, England
148634)    pompano beach    ['florida', 'pompano beach']-------------------Pompano Beach, Florida, July 30 & 31, 1990
148723)    puyallup    ['puyallup', 'washington']-------------------Puyallup, Washington, September 22, 1994 and June 3, 1995
148807)    del rio    ['del rio', 'san antonio']-------------------Live "The Landing", Paseo del Rio, San Antonio
149053)    takoma park    ['takoma park', 'washington']-------------------Takoma Park, MD & Washington, DC
149415)    baden-baden    ['baden-baden', 'freiburg']-------------------Baden-Baden & Freiburg
149739)    simi valley    ['alhambra', 'sherman oaks', 'simi valley']-------------------Sherman Oaks, Simi Valley & Alhambra, CA
150550)    griffin    ['griffin', 'new york']-------------------Merv Griffin tv show, New York
150848)    bergkamen    ['munster', 'bergkamen']-------------------Munster & Bergkamen
150960)    encinitas    ['san marcos', 'encinitas']-------------------San Marcos & Encinitas, CA, May 31-July 22, 2002
151167)    greeley    ['boulder', 'greeley']-------------------Greeley & Boulder, CO
151232)    hamtramck    ['hamtramck', 'dearborn', 'lansing']-------------------Hamtramck, Dearborn & Lansing, MI, January-August, 2000 (*)
151300)    gliwice    ['copenhagen', 'warsaw', 'gliwice']-------------------Copenhagen, Warsaw & Gliwice
151328)    east point    ['ann arbor', 'bloomfield', 'east point']-------------------Ann Arbor, West Bloomfield & East Pointe, MI (*)
151355)    glassboro    ['philadelphia', 'glassboro']-------------------Philadelphia & Glassboro, N.J., September 2002-June 2003 (*)
151508)    chattanooga    ['chicago', 'chattanooga', 'new york']-------------------Chattanooga, TN, Chicago, IL & New York, March 6-11,2000 (*)
151939)    scordia    ['catania', 'scordia']-------------------Scordia, Catania, May 12 & 13, 2000
152072)    kashiwa    ['kashiwa', 'tokyo']-------------------Live "Kashiwa", Tokyo
152292)    patterson    ['paris', 'patterson']-------------------Patterson, N.J., April 2002 & Paris, May 2002
152418)    sparks    ['sparks', 'reno']-------------------Reno NV, Jan 27 & Sparks, NV, March 25 & April 26, 2001
152489)    reading    ['dallas', 'reading', 'youngstown']-------------------Youngstown, OH, Dallas, TX & Reading, PA
152614)    iowa city    ['los angeles', 'iowa city']-------------------Los Angeles & Iowa City, IA, September 1999-December 2000 *
153259)    alboraya    ['valencia', 'alboraya']-------------------Alboraya Valencia, Spain, March 5 & 6, 2002
153262)    poitiers    ['salzburg', 'poitiers']-------------------Poitiers, France & Salzburg, Austria, 1997 & 1999 (*)
153424)    tallahassee    ['new york', 'tallahassee']-------------------New York & Tallahassee, FL, 1995 & 1997
153512)    hopkinsville    ['louisville', 'versailles', 'lexington', 'hopkinsville']-------------------Louisville, Hopkinsville, Versailles & Lexington, KY
153684)    prince albert    ['ontario', 'prince albert']-------------------Prince Albert, Ontario, June 1999-January 2001
153692)    sudbury    ['sudbury', 'pawtucket']-------------------Pawtucket, R.I. & Sudbury, MA
153772)    beaconsfield    ['beaconsfield', 'quebec']-------------------Beaconsfield, Quebec, February 27 & 28, 2002
153838)    oviedo    ['brooklyn', 'oviedo']-------------------Oviedo, Spain & Brooklyn, NY
0
934

In [0]:
#lastfinallist
uniquerowand3 = []
uniquerowno3 = []


lastfinallist = []


hardsortlist = ['sudbury', 'pawtucket', 'bloomington', 'louisville', 'louisville', 'versailles', 'lexington', 'hopkinsville','cambridge', 'somerville', 'reading','montclair', 'long branch','dallas', 'reading','sparks', 'reno','richmond', 'menlo park','catania','columbus', 'phoenix', 'bloomfield', 'east point', 'dearborn', 'lansing','boulder', 'greeley', 'nijmegen','avignon', 'paramus','tallinn', 'osaka', 'san antonio','los altos', 'redwood city','helsinki', 'brookline','yokohama','phoenix', 'tempe','boulder','louisville', 'greensboro','meyrin', 'malnate','welwyn garden city', 'northampton','winnipeg','westport','dresden', 'erfurt','nashville', 'alhambra','weiden','southsea','torrance', 'santa barbara', 'nassau','tarragona', 'palm springs','dallas', 'irving','colinas','carmel', 'monterey', 'stamford','dearborn', 'hudson', 'wethersfield', 'birmingham','toulouse', 'blagnac', 'stockport', 'wigan','bucharest', 'keswick', 'dartmouth','pasadena','hastings','marseille', 'yerres','arlington', 'mainz','costa mesa', 'tustin','ludwigsburg', 'heidelberg','caldwell','laguna','yokohama', 'osaka','taunton', 'plymouth', 'appleton', 'long branch','santa barbara','orlando', 'tampa','miami', 'havana','belmont', 'portland','carlisle', 'danvers','charleston','whitley bay', 'kobe', 'celle','acireale','derby','san diego','concord','kansas city','jackson','glen cove', 'mineola', 'bournemouth', 'rockford', 'sheridan','kansas city','san diego','baltimore','wiesbaden', 'hannover','the hague','pozzallo', 'siracusa','sherman oaks', 'strasbourg','anderson', 'indianapolis','carlisle', 'stoughton', 'durham','johannesburg', 'oakland','willoughby','palatine','new bedford','atlanta', 'nagoya', 'dendermonde','schwabach','pescara','santa monica','newport', 'milwaukee','houston','cologne', 'stuttgart','Laguna Beach','syracuse','coventry', 'fremont', 'cannes','canoga park', 'calabasas','innsbruck', 'hanover','leeds','norwich', 'bedford', 'freiburg', 'reims','kearny', 'minneapolis','naples','franklin', 'brandon','newark','rotterdam', 'dordrecht','bussum','bonn','buffalo', 'boston', 'atlantic city','colorado springs','scheveningen', 'villejuif','bologna', 'pistoia','udine','thornton','bratislava', 'essex', 'baarn','seattle', 'mountlake terrace','rotterdam', 'amsterdam','melbourne', 'sydney','hoboken','beverly', 'wellesley','pittsburgh','fort lauderdale','amersfoort','brighton','Yarmouth', 'memphis','bordeaux', 'frankfurt','brooklyn', 'paterson','alkmaar', 'bracknell','saratoga','amherst','west hollywood', 'burbank','sacramento', 'san jose', 'englewood', 'barnet','las vegas','copenhagen','neu-ulm','north hollywood','iserlohn', 'dortmund', 'culver city','venice','munich','claremont','tortona', 'dublin','cincinnati', 'detroit','albany','wilton', 'montreux','westbury','paris', 'burbank', 'vancouver','seattle','rochester', 'west orange','denver','cleveland','new orleans','st. louis','rome', 'montreux','berkeley','chicago','brno', 'prague','suisun','falun','san francisco','hollywood', 'toronto','philadelphia','burbank','paris','london', 'silver spring','surrey','glendale', 'san rafael','westminster']
hardsortlist = np.unique(hardsortlist)
print("hardsortlist:",len(hardsortlist))
for i,rowlist in enumerate(finallist3):
  temprow = []
  if len(rowlist) > 1:
    flag3 = 0
    for ele1 in rowlist:
      flag1 = 0
      if ele1 in impnamelist:
        flag1 = 1
        flag3 = 1
        temprow.append(ele1)
        
      flag2 = 0
      if flag1 ==0:
        for ele2 in subcoulist:
          ele2 = str(ele2).lower().strip()
          if ele1 in ele2:
            flag2 = 1
            flag3 = 1
            temprow.append(ele1)
            break
            
      flag4 = 0
      if flag1 ==0:
        if ele1 in hardsortlist:
          flag4 = 1
          flag3 = 1
          temprow.append(ele1)
    if flag3 ==0:
#       flag5=0
#       for ele1 in rowlist:
#         if ele1 not in uniquerowno3:
#           uniquerowno3.append(ele1)
#           flag5=1
#       if flag5 == 1:    
      print(str(i) + ")    "+ str(rowlist) +"-------------------"+ str(valuesall[i]))        
  else:
    temprow = rowlist
    
    
  lastfinallist.append(temprow)  
# print(len(uniquerowand3))
# print(len(uniquerowno3))
print(len(lastfinallist))

# hardsortlist = ['innsbruck', 'hanover','leeds','norwich', 'bedford', 'freiburg', 'reims','kearny', 'minneapolis','naples','franklin', 'brandon','newark','rotterdam', 'dordrecht','bussum','bonn','buffalo', 'boston', 'atlantic city','colorado springs','scheveningen', 'villejuif','bologna', 'pistoia','udine','thornton','bratislava', 'essex', 'baarn','seattle', 'mountlake terrace','rotterdam', 'amsterdam','melbourne', 'sydney','hoboken','beverly', 'wellesley','pittsburgh','fort lauderdale','amersfoort','brighton','Yarmouth', 'memphis','bordeaux', 'frankfurt','brooklyn', 'paterson','alkmaar', 'bracknell','saratoga','amherst','west hollywood', 'burbank','sacramento', 'san jose', 'englewood', 'barnet','las vegas','copenhagen','neu-ulm','north hollywood','iserlohn', 'dortmund', 'culver city','venice','munich','claremont','tortona', 'dublin','cincinnati', 'detroit','albany','wilton', 'montreux','westbury','paris', 'burbank', 'vancouver','seattle','rochester', 'west orange','denver','cleveland','new orleans','st. louis','rome', 'montreux','berkeley','chicago','brno', 'prague','suisun','falun','san francisco','hollywood', 'toronto','philadelphia','burbank','paris','london', 'silver spring','surrey','glendale', 'san rafael','westminster']





# 'johannesburg', 'oakland','willoughby','palatine','new bedford','atlanta', 'nagoya', 'dendermonde','schwabach','pescara','santa monica','newport', 'milwaukee','houston','cologne', 'stuttgart'



# 'orlando', 'tampa','miami', 'havana','belmont', 'portland','carlisle', 'danvers','charleston','whitley bay', 'kobe', 'celle','acireale','derby','san diego','concord','kansas city','jackson','glen cove', 'mineola', 'bournemouth', 'rockford', 'sheridan','kansas city','san diego','baltimore','wiesbaden', 'hannover','the hague','pozzallo', 'siracusa','sherman oaks', 'strasbourg','anderson', 'indianapolis','carlisle', 'stoughton',, 'durham'

# 'sudbury', 'pawtucket', 'bloomington', 'louisville', 'louisville', 'versailles', 'lexington', 'hopkinsville','cambridge', 'somerville', 'reading','montclair', 'long branch','dallas', 'reading','sparks', 'reno','richmond', 'menlo park','catania','columbus', 'phoenix', 'bloomfield', 'east point', 'dearborn', 'lansing','boulder', 'greeley', 'nijmegen','avignon', 'paramus','tallinn', 'osaka', 'san antonio','los altos', 'redwood city','helsinki', 'brookline','yokohama','phoenix', 'tempe','boulder','louisville', 'greensboro','meyrin', 'malnate','welwyn garden city', 'northampton','winnipeg','westport','dresden', 'erfurt','nashville', 'alhambra','weiden','southsea','torrance', 'santa barbara', 'nassau','tarragona', 'palm springs','dallas', 'irving','colinas','carmel', 'monterey', 'stamford','dearborn', 'hudson', 'wethersfield', 'birmingham','toulouse', 'blagnac', 'stockport', 'wigan','bucharest', 'keswick', 'dartmouth','pasadena','hastings','marseille', 'yerres','arlington', 'mainz','costa mesa', 'tustin','ludwigsburg', 'heidelberg','caldwell','laguna','yokohama', 'osaka','taunton', 'plymouth', 'appleton', 'long branch','santa barbara',

hardsortlist: 245
15597)    ['springs', 'antioch']-------------------Live, "Antioch Theatre, Antioch College", Yellow Springs, OH
25540)    ['wright', 'yarmouth']-------------------Yarmouth, Isle of Wright
134232)    ['downey', 'morton']-------------------radio broadcast, "Morton Downey Show", Spring 1951
139514)    ['springs', 'sulphur']-------------------Spotlight bands broadcast #524, White Sulphur Springs, W.VA
153961

In [0]:
#lastfinallist show
count0 = 0
count1 = 0
count2 = 0
count3 = 0
count4 = 0
count5 = 0
count6 = 0
count7 = 0
maxlen = 0


# commonword4 = ["holidays","holiday","same","summit","sunset","nord","orange","liberal","metro","prospect","elizabeth","papa","golden","mobile","sale","than","longview","best","state college","college"]

# uniquerow4 = []
for i,rowlist in enumerate(lastfinallist):
  if len(rowlist) ==0:
#     print(str(i) + str(rowlist) +"-------------------"+ str(valuesall[i]))
    count0=count0+1
  if len(rowlist) ==1:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count1=count1+1
  if len(rowlist) ==2:
#     print(str(i) + ")    " + str(rowlist) +"-------------------"+ str(valuesall[i]))
    count2=count2+1
  if len(rowlist) ==3:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count3=count3+1
  if len(rowlist) ==4:
#     print(str(i) + ")    "+str(rowlist) +"-------------------"+ str(valuesall[i]))
    count4=count4+1
  if len(rowlist) ==5:
#     print(str(i) + ")    " + str(rowlist) +"-------------------"+ str(valuesall[i]))
    count5=count5+1
  if len(rowlist) ==6:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count6=count6+1
  if len(rowlist) ==7:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count7=count7+1
  if len(rowlist) > maxlen:
    maxlen = len(rowlist)
#     print(str(i) + ")    " + str(maxlen)+"------"+str(rowlist) +"-------------------"+ str(valuesall[i]))
print("count0",count0)
print("count1",count1)
print("count2",count2)
print("count3",count3)
print("count4",count4)
print("count5",count5)
print("count6",count6)
print("count7",count7)
print("maxlen", maxlen)

# print(len(uniquerow4))

count0 22761
count1 126697
count2 4253
count3 209
count4 40
count5 1
count6 0
count7 0
maxlen 5

In [0]:
filename = "lastfinallist.csv"
my_df = pd.DataFrame(lastfinallist)
my_df.to_csv(filename)

from google.colab import files
downloaded = files.download(filename)

In [0]:
# filename = "hardsortlist.csv"
# my_df = pd.DataFrame(hardsortlist)
# my_df.to_csv(filename)

# from google.colab import files
# downloaded = files.download(filename)

In [0]:
# filename = "finallist3.csv"
# my_df = pd.DataFrame(finallist3)
# my_df.to_csv(filename)

# from google.colab import files
# downloaded = files.download(filename)

In [0]:
# filename = "finallist2.csv"
# my_df = pd.DataFrame(finallist2)
# my_df.to_csv(filename)

# from google.colab import files
# downloaded = files.download(filename)

In [0]:
# filename = "longlist.csv"
# my_df = pd.DataFrame(longlist)
# my_df.to_csv(filename)

# from google.colab import files
# downloaded = files.download(filename)

In [0]:
lastfinallist2 = lastfinallist

for i,rowlist in enumerate(lastfinallist2):
  for j,ele1 in enumerate(rowlist):
    for k,ele2 in enumerate(namelist):
      ele2 = str(ele2).lower().strip()
      if ele1 in ele2:
        lastfinallist2[i][j] = str(subcoulist[k]).lower().strip()
        break
  lastfinallist2[i] = np.unique(lastfinallist2[i])
   
print(len(lastfinallist2))

153961

In [0]:
#lastfinallist show
count0 = 0
count1 = 0
count2 = 0
count3 = 0
count4 = 0
count5 = 0
count6 = 0
count7 = 0
maxlen = 0


# commonword4 = ["holidays","holiday","same","summit","sunset","nord","orange","liberal","metro","prospect","elizabeth","papa","golden","mobile","sale","than","longview","best","state college","college"]

# uniquerow4 = []
for i,rowlist in enumerate(lastfinallist2):
  if len(rowlist) ==0:
#     print(str(i) + str(rowlist) +"-------------------"+ str(valuesall[i]))
    count0=count0+1
  if len(rowlist) ==1:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count1=count1+1
  if len(rowlist) ==2:
#     print(str(i) + ")    " + str(rowlist) +"-------------------"+ str(valuesall[i]))
    count2=count2+1
  if len(rowlist) ==3:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count3=count3+1
  if len(rowlist) ==4:
#     print(str(i) + ")    "+str(rowlist) +"-------------------"+ str(valuesall[i]))
    count4=count4+1
  if len(rowlist) ==5:
#     print(str(i) + ")    " + str(rowlist) +"-------------------"+ str(valuesall[i]))
    count5=count5+1
  if len(rowlist) ==6:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count6=count6+1
  if len(rowlist) ==7:
#     print(str(i) + str(rowlist) +"-------------------"+ valuesall[i])
    count7=count7+1
  if len(rowlist) > maxlen:
    maxlen = len(rowlist)
#     print(str(i) + ")    " + str(maxlen)+"------"+str(rowlist) +"-------------------"+ str(valuesall[i]))
print("count0",count0)
print("count1",count1)
print("count2",count2)
print("count3",count3)
print("count4",count4)
print("count5",count5)
print("count6",count6)
print("count7",count7)
print("maxlen", maxlen)

# print(len(uniquerow4))

count0 22761
count1 126785
count2 4171
count3 204
count4 40
count5 0
count6 0
count7 0
maxlen 4

In [0]:
filename = "lastfinallist2.csv"
my_df = pd.DataFrame(lastfinallist2)
my_df.to_csv(filename)

from google.colab import files
downloaded = files.download(filename)

In [0]:
# count0 22761
# count1 126697
# count2 4253
# count3 209
# count4 40
# count5 1



# count0 22761
# count1 126785
# count2 4171
# count3 204
# count4 40

In [0]:
df = pd.DataFrame({
    'col1' : ['A', 'A', 'B', np.nan, 'D', 'C'],
    'col2' : [2, 1, 9, 8, 7, 4],
    'col3': [0, 1, 9, 4, 2, 3]})

In [0]:
print(df)

  col1  col2  col3
0    A     2     0
1    A     1     1
2    B     9     9
3  NaN     8     4
4    D     7     2
5    C     4     3

In [0]:
print(df.columns)

Index(['col1', 'col2', 'col3'], dtype='object')

In [0]:
df2 = df.sort_values(by=['col1'])

In [0]:
print(df2)

  col1  col2  col3
0    A     2     0
1    A     1     1
2    B     9     9
5    C     4     3
4    D     7     2
3  NaN     8     4